### ISSUE TITLE
10X单细胞转录组测序数据的 SRA转fastq踩坑那些事

### ISSUE THREAD

**Issue by ixxmu** [ixxmu/mp_duty#1407]
https://mp.weixin.qq.com/s/XxTKUDFzgGxrWrAyLOY6Rw

**Comment by yxx200929** [comment]
运行的命令：nohup fasterq-dump --split-files --include-technical --threads 10 SRR15216331.sra -O ./ &
输入和输出文件：
166437525132 10月 25 17:18 SRR15216331_1.fastq
166437525132 10月 25 17:18 SRR15216331_2.fastq
 63665159184 10月 19 00:42 SRR15216331.sra
您好！请教一下我这个为什么只产生2个fastq文件
