### ISSUE TITLE
基因表达量预测药物反应的R包pRRophetic近期报错解决方案

### ISSUE THREAD

**Issue by ixxmu** [ixxmu/mp_duty#2691]
https://mp.weixin.qq.com/s/SwnmKCjzURNV4B848nCvsw

**Comment by ixxmu** [comment]
基因表达量预测药物反应的R包pRRophetic近期报错解决方案 by 果子学生信
------
<div><section><h4><span>两个想法</span></h4><p>干湿结合，我一直有两个未曾改变的诉求:</p><ul><li><p><span>第一，从细胞处理的转录组数据中提取核心通路或者基因，用于指导实验。</span></p></li><li><p><span>第二，根据细胞系或者患者样本的表达量，推测可能有效的药物。</span></p></li></ul><p>第一个想法，他能够解放成千上万的小作坊课题组，节约试剂，减缓毕业压力，甚至延长研究生寿命。<br>第二个想法，他能够把实验室的结果，最快的跟临床实践联系起来，并对外宣布，我们并不是天天只关注汤汤水水，我们也关注患者生命的延长。</p><p>这两个想法，在领域内都有一些是可供尝试的方案，但是目前还不够完善，任何课题组只要尝试并解决其中一个，我觉得都是功德无量的。<br>如果大家看到了什么可行的方案，代码走不通或者配置搞不定的，告诉我，我都愿意尝试并且帮忙。</p><h4><span>问题溯源</span></h4><p>今天要讲的是R包pRRophetic的报错解决方案，这个包是常用的通过基因表达量预测药物反应的是工具。<br>近期有很多人提出这样的问题:</p><pre><code>pRRopheticPredict(data, drug, selection=<span>1</span>)”这个后出现“<span>Error</span> <span>in</span> <span>if</span> (<span>class</span>(testExprData) != <span>"matrix"</span>) <span>stop</span>(<span>"ERROR: \"</span>testExprData\<span>" must be a matrix."</span>) : the condition has length &gt; <span>1</span>”这样的报错该怎么解决啊？<br></code></pre><p>这要是Y叔的包，你绝对不用担心，随便在哪联系到他，写信给他，他估计连夜都能给你解决了。这应该就是clusterProfiler这个R包能红火到今天的原因吧，与时俱进，从不掉队。</p><p>但是这个R包，太老了，2014年发的文章，而且文档写的一点都不好。<br></p><figure><img data-ratio="0.2418111753371869" data-src="https://mmbiz.qpic.cn/mmbiz_png/NDy5aEnReX0NiboHyialFoKkJOaUcX56EYVTAnpu7UfqmvXbbgamRctVRo9r6QYUs7kMNic4hMOqjRicC501SlC6Wg/640?wx_fmt=png" data-type="png" data-w="1038" title="" src="https://mmbiz.qpic.cn/mmbiz_png/NDy5aEnReX0NiboHyialFoKkJOaUcX56EYVTAnpu7UfqmvXbbgamRctVRo9r6QYUs7kMNic4hMOqjRicC501SlC6Wg/640?wx_fmt=png"></figure><p>作者都不想管的工具，不知道为什么还有那么多人要用。我看了一下这个报错，应该是由于R语言升级后对Matrix的属性认识不同造成的。<br>我们看一下Matrix的帮助文档</p><pre><code>?matrix<br></code></pre><p>在里面写了这样一句话：</p><blockquote><p>A matrix is the special case of a two-dimensional array. Since R 4.0.0, inherits(m, "array") is true for a matrix m.</p></blockquote><p>说Matrix是一种特殊的array，自从R4.0开始，就继承了array这个属性。<br>直白的表示就是，一个maxtrix，以前查看属性只有一个matrix，但是现在有连个，举例如下:</p><pre><code>mdat &lt;- matrix(c(<span>1</span>,<span>2</span>,<span>3</span>, <span>11</span>,<span>12</span>,<span>13</span>), nrow = <span>2</span>, ncol = <span>3</span>, byrow = TRUE,<br>               dimnames = list(c(<span>"row1"</span>, <span>"row2"</span>),<br>                               c(<span>"C.1"</span>, <span>"C.2"</span>, <span>"C.3"</span>)))<br>mdat<br><span><span>class</span>(<span>mdat</span>)</span><br></code></pre><figure><img data-ratio="0.2607626076260763" data-src="https://mmbiz.qpic.cn/mmbiz_png/NDy5aEnReX0NiboHyialFoKkJOaUcX56EYooS5AldKEsoJdNnRbAqibJyq8s6ibBtXpMXWYfuPfvAiaDGKnBUzSaf6A/640?wx_fmt=png" data-type="png" data-w="1626" title="" src="https://mmbiz.qpic.cn/mmbiz_png/NDy5aEnReX0NiboHyialFoKkJOaUcX56EYooS5AldKEsoJdNnRbAqibJyq8s6ibBtXpMXWYfuPfvAiaDGKnBUzSaf6A/640?wx_fmt=png"></figure><p>这样带来的问题是，如果某一步需要判断是不是matrix才能往下操作，之前的代码就很容易报错</p><p>比如</p><pre><code><span>if</span>(<span><span>class</span>(<span>mdat</span>) </span>== <span>"matrix"</span>){<br>  print(<span>"The data is wright, Go ahead!"</span>)<br>}<br></code></pre><p>他会报错<br></p><figure><img data-ratio="0.1486318407960199" data-src="https://mmbiz.qpic.cn/mmbiz_png/NDy5aEnReX0NiboHyialFoKkJOaUcX56EYD6llicULwQ8Hc3iaUf278YSHOrCrEFfebHsT3DOBA2NCVBSBDX1kqJMg/640?wx_fmt=png" data-type="png" data-w="1608" title="" src="https://mmbiz.qpic.cn/mmbiz_png/NDy5aEnReX0NiboHyialFoKkJOaUcX56EYD6llicULwQ8Hc3iaUf278YSHOrCrEFfebHsT3DOBA2NCVBSBDX1kqJMg/640?wx_fmt=png"></figure><p>这个报错信息，跟学生们提问的是一样的，说明我们找到了问题的症结。<br>只要我们把作者R包里面的源代码中涉及到矩阵判断的部分全部改一下就行，<br>举例如下:</p><pre><code><span>if</span>(<span><span>class</span>(<span>mdat</span>)[1] == "<span>matrix</span>")</span>{<br>  <span>print</span>(<span>"The data is wright, Go ahead!"</span>)<br>}<br></code></pre><p>就是只提取第一个属性matix<br></p><figure><img data-ratio="0.11614906832298137" data-src="https://mmbiz.qpic.cn/mmbiz_png/NDy5aEnReX0NiboHyialFoKkJOaUcX56EYtBUDuJsfk9rprEqsja7o5jjyWJibQoE3PvG8H53AQ8BNJxSOHHHLJrg/640?wx_fmt=png" data-type="png" data-w="1610" title="" src="https://mmbiz.qpic.cn/mmbiz_png/NDy5aEnReX0NiboHyialFoKkJOaUcX56EYtBUDuJsfk9rprEqsja7o5jjyWJibQoE3PvG8H53AQ8BNJxSOHHHLJrg/640?wx_fmt=png"></figure><h4><span>重新安装R包</span></h4><p>我们把修改后的R包重新安装一下</p><pre><code><span>### 1.加载镜像</span><br>options(<span>"repos"</span>=c(CRAN=<span>"https://mirrors.tuna.tsinghua.edu.cn/CRAN/"</span>))<br>options(BioC_mirror=<span>"https://mirrors.tuna.tsinghua.edu.cn/bioconductor"</span>)<br><br><span>###2.安装R包</span><br><span>if</span>(!requireNamespace(<span>"car"</span>,quietly = <span>TRUE</span>)) install.packages(<span>"car"</span>,update = <span>F</span>,ask = <span>F</span>)<br><span>if</span>(!requireNamespace(<span>"ridge"</span>,quietly = <span>TRUE</span>)) install.packages(<span>"ridge"</span>,update = <span>F</span>,ask = <span>F</span>)<br><span>if</span>(!requireNamespace(<span>"preprocessCore"</span>,quietly = <span>TRUE</span>)) BiocManager::install(<span>"preprocessCore"</span>,update = <span>F</span>,ask = <span>F</span>)<br><span>if</span>(!requireNamespace(<span>"genefilter"</span>,quietly = <span>TRUE</span>)) BiocManager::install(<span>"genefilter"</span>,update = <span>F</span>,ask = <span>F</span>)<br><span>if</span>(!requireNamespace(<span>"sva"</span>,quietly = <span>TRUE</span>)) BiocManager::install(<span>"sva"</span>,update = <span>F</span>,ask = <span>F</span>)<br>install.packages(<span>"./resource/pRRophetic_Guozi/"</span>, repos = <span>NULL</span>,type = <span>"source"</span>)<br></code></pre><p>然后一切就回归正常了。</p><h4><span>如何修改？</span></h4><p>那是如何实现的啊，就是找到这个R包代码中所有需要判断matrix的地方，依次修改就行。<br>这是个苦差事，也是个硬实力。<br>我把这个修改后的R包以R poject形式放在了公众号，回复"pRRophetic"自助获取。<br>当然我也可能没有修改完，至少以下代码现在可以正常执行了</p><pre><code><span>###3.使用测试</span><br>library(pRRophetic)<br>library(ggplot2)<br>set.seed(<span>12345</span>)<br><span>data</span>(<span>"bortezomibData"</span>) <span>#exprDataBortezomib, bortIndex, studyResponse and studyIndex</span><br>pRRopheticQQplot(<span>"Bortezomib"</span>)<br><br>cvOut &lt;- pRRopheticCV(<span>"Bortezomib"</span>, cvFold=<span>5</span>, testExprData=exprDataBortezomib)<br>summary(cvOut)<br>plot(cvOut)<br><br>predictedPtype &lt;- pRRopheticPredict(exprDataBortezomib, <span>"Bortezomib"</span>, selection=<span>1</span>)<br>predictedPtype_blood &lt;- pRRopheticPredict(exprDataBortezomib, <span>"Bortezomib"</span>, <span>"blood"</span>, selection=<span>1</span>)<br>predictedPtype_solid &lt;- pRRopheticPredict(exprDataBortezomib, <span>"Bortezomib"</span>, <span>"allSolidTumors"</span>, selection=<span>1</span>)<br><br><br>t.test(predictedPtype[((studyResponse == <span>"PGx_Responder = NR"</span>) &amp; bortIndex)],<br>       predictedPtype[((studyResponse == <span>"PGx_Responder = R"</span>) &amp; bortIndex)],<br>       alternative=<span>"greater"</span>)<br><br>t.test(predictedPtype_blood[((studyResponse == <span>"PGx_Responder = NR"</span>) &amp; bortIndex)],<br>       predictedPtype_blood[((studyResponse == <span>"PGx_Responder = R"</span>) &amp; bortIndex)],<br>       alternative=<span>"greater"</span>)<br><br>t.test(predictedPtype_solid[((studyResponse == <span>"PGx_Responder = NR"</span>) &amp; bortIndex)],<br>       predictedPtype_solid[((studyResponse == <span>"PGx_Responder = R"</span>) &amp; bortIndex)],<br>       alternative=<span>"greater"</span>)<br><br><span>### 画图</span><br>df &lt;- stack(<span>list</span>(NR=predictedPtype_blood[((studyResponse == <span>"PGx_Responder = NR"</span>)&amp; bortIndex)], <br>                 R=predictedPtype_blood[((studyResponse == <span>"PGx_Responder = R"</span>) &amp; bortIndex)]))<br>ggplot(<span>data</span>=df, aes(y=<span>values</span>, x=ind)) +<br>  geom_boxplot(alpha=<span>.3</span>, fill=c(<span>"#CC0033"</span>, <span>"#006633"</span>)) + <br>  theme_bw() + <br>  ylab(<span>"Predicted Bortezomib Sensitivity"</span>) + <br>  xlab(<span>"Clinical Response"</span>)<br></code></pre><p>会出一个这样反应两组患者IC50的图。<br></p><figure><img data-ratio="0.8921815889029003" data-src="https://mmbiz.qpic.cn/mmbiz_png/NDy5aEnReX0NiboHyialFoKkJOaUcX56EYwLkn0G7zR4VlZmNl05y5s128sLCibGbRibaiaoqmXSibk9dh1Mcue8h7FA/640?wx_fmt=png" data-type="png" data-w="1586" title="" src="https://mmbiz.qpic.cn/mmbiz_png/NDy5aEnReX0NiboHyialFoKkJOaUcX56EYwLkn0G7zR4VlZmNl05y5s128sLCibGbRibaiaoqmXSibk9dh1Mcue8h7FA/640?wx_fmt=png"></figure><p>同时另外的方案是，这个作者重新写了一个类似的R包，发在了BIB上面，可以用起来试一试<br></p><figure><img data-ratio="0.35601659751037346" data-src="https://mmbiz.qpic.cn/mmbiz_png/NDy5aEnReX0NiboHyialFoKkJOaUcX56EYDicHX1qqsHIJPGribPxp4icdlZ1XgxnDpHYzicCSDQbKbGJD73OEdrw37g/640?wx_fmt=png" data-type="png" data-w="1205" title="" src="https://mmbiz.qpic.cn/mmbiz_png/NDy5aEnReX0NiboHyialFoKkJOaUcX56EYDicHX1qqsHIJPGribPxp4icdlZ1XgxnDpHYzicCSDQbKbGJD73OEdrw37g/640?wx_fmt=png"></figure><h4><span>一些思考</span></h4><p>我在这里没有写这个包的用法，是因为我觉得他的结果不怎么好，自己预测自己相关性只有0.5左右。我演示这个包的修改过程，就是为了展示一个R包报错的解决过程，<br>我的常用步骤如下:<br></p><figure><img data-ratio="1.7847222222222223" data-src="https://mmbiz.qpic.cn/mmbiz_png/NDy5aEnReX0NiboHyialFoKkJOaUcX56EYx5icQw6aTsP3mMuHrhYicMAzWSrMMzfgbaZNcQlnaGTdoVVdAw9z9oYA/640?wx_fmt=png" data-type="png" data-w="1440" title="" src="https://mmbiz.qpic.cn/mmbiz_png/NDy5aEnReX0NiboHyialFoKkJOaUcX56EYx5icQw6aTsP3mMuHrhYicMAzWSrMMzfgbaZNcQlnaGTdoVVdAw9z9oYA/640?wx_fmt=png"></figure><p>本次报错因为是多人举报，我就直接用了第四个能力解决。希望你也能学会，我们共同进步。</p></section></div>

**Comment by naiem-99** [comment]
pRRophetic
