### ISSUE TITLE
使用gtf文件自行构建注释包txdb

### ISSUE THREAD

**Issue by ixxmu** [ixxmu/mp_duty#2804]
https://mp.weixin.qq.com/s/7HV11-R_Wd4UhqFNOWhNaw

**Comment by ixxmu** [comment]
使用gtf文件自行构建注释包txdb by 生信小知识
------
<div><section><h2><span>使用gtf文件自行构建注释包txdb</span></h2><blockquote><p>微信公众号：<strong>生信小知识</strong><br>关注可了解更多的生物信息学教程及知识。问题或建议，请公众号留言;</p></blockquote><h3><span>目录</span></h3><p><span><span>前言</span></span><span><span>1. 使用 GenomicFeatures 包制作注释数据</span></span><span><span>2. 保存以及载入注释数据</span></span><span><span>3. 探索</span></span><span><span><span>3.1 总转录本数目</span></span></span><span><span><span>3.2 经典方法提取数据</span></span></span><span><span><span>3.3 检索GRange对象</span></span></span><span><span><span>3.4 分组统计</span></span></span><span><span>后记</span></span></p><h3><span>前言</span></h3><p>最近通过探索<a href="https://mp.weixin.qq.com/s?__biz=MjM5NTk0Mzg2Nw==&amp;mid=2247488296&amp;idx=1&amp;sn=8247602ecc1f5caebd2c8222abbced7b&amp;scene=21#wechat_redirect" data-linktype="2">RefSeq和Known Genes注释文件有什么区别</a>，让我对已经做成R包的注释文件有一定的怀疑。</p><p>为了让自己放心，决定使用下载好的gtf文件，利用 <code>GenomicFeatures</code> 包来制作注释数据，顺便复习下 <code>GenomicFeatures</code> 包的相关使用方法。</p><p>关于 <code>GenomicFeatures</code> 包的使用说明可以参考：</p><ul><li><p><a href="https://mp.weixin.qq.com/s?__biz=MjM5NTk0Mzg2Nw==&amp;mid=2247486105&amp;idx=1&amp;sn=be2bc415b172836425c0ae25d549883c&amp;scene=21#wechat_redirect" data-linktype="2">了解Bioconductor中的注释包</a></p></li></ul><h3><span>1. 使用 GenomicFeatures 包制作注释数据</span></h3><pre><code><span># 载入环境</span><br><span>if</span> (T) {<br>  rm(list = ls())<br>  options(stringAsFactors = F)<br>  library(stringr)<br>  library(GenomicFeatures)<br>}<br><br><span># 制作注释数据</span><br><span>if</span> (T) {<br>  txdb &lt;- makeTxDbFromGFF(<span>"gencode.v40.annotation.gtf.gz"</span>)<br>}<br></code></pre><p>整个过程耗时比较长，所以建议将制作好的注释数据保存下来，下次直接载入。</p><h3><span>2. 保存以及载入注释数据</span></h3><pre><code><span># 数据保存</span><br>saveDb(txdb, file=<span>"gencode.v40.annotation.sqlite"</span>)<br></code></pre><h3><span>3. 探索</span></h3><h4><span>3.1 总转录本数目</span></h4><pre><code><span># 载入环境和数据</span><br><span>if</span> (<span>T</span>) {<br>  rm(list = ls())<br>  txdb &lt;- loadDb(<span>"gencode.v40.annotation.sqlite"</span>)<br>  txdb<br>}<br><span>## TxDb object:</span><br><span>## # Db type: TxDb</span><br><span>## # Supporting package: GenomicFeatures</span><br><span>## # Data source: gencode.v40.annotation.gtf.gz</span><br><span>## # Organism: NA</span><br><span>## # Taxonomy ID: NA</span><br><span>## # miRBase build ID: NA</span><br><span>## # Genome: NA</span><br><span>## # Nb of transcripts: 246624</span><br><span>## # Db created by: GenomicFeatures package from Bioconductor</span><br><span>## # Creation time: 2022-10-09 16:49:51 +0800 (Sun, 09 Oct 2022)</span><br><span>## # GenomicFeatures version at creation time: 1.46.5</span><br><span>## # RSQLite version at creation time: 2.2.9</span><br><span>## # DBSCHEMAVERSION: 1.2</span><br></code></pre><p>可以看到，在 <code>gencode.v40.annotation.gtf.gz</code> 文件中应该有246624个转录本。我们在linux中进行验证：</p><pre><code>$ zgrep -v <span>"^#"</span> gencode.v40.annotation.gtf.gz|awk -F<span>"\t"</span> <span>'{print $3}'</span>|sort|uniq -c<br> 851482 CDS<br>1573262 exon<br>  61544 gene<br>    119 Selenocysteine<br>  95353 start_codon<br>  88894 stop_codon<br> 246624 transcript<br> 366584 UTR<br></code></pre><h4><span>3.2 经典方法提取数据</span></h4><pre><code><span># 通用方法</span><br><span>if</span> (<span>T</span>) {<br>  keytypes(txdb)<br>  sapply(keytypes(txdb), <span>function</span>(x){<br>    head(keys(txdb,x))<br>  })<br>}<br><span>## $CDSID</span><br><span>## [1] "1" "2" "3" "4" "5" "6"</span><br><span>## </span><br><span>## $CDSNAME</span><br><span>## [1] NA</span><br><span>## </span><br><span>## $EXONID</span><br><span>## [1] "1" "2" "3" "4" "5" "6"</span><br><span>## </span><br><span>## $EXONNAME</span><br><span>## [1] "ENSE00002234944.1" "ENSE00001948541.1" "ENSE00001671638.2" "ENSE00001758273.2" "ENSE00003582793.1" "ENSE00001799933.2"</span><br><span>## </span><br><span>## $GENEID</span><br><span>## [1] "ENSG00000000003.15" "ENSG00000000005.6"  "ENSG00000000419.14" "ENSG00000000457.14" "ENSG00000000460.17" "ENSG00000000938.13"</span><br><span>## </span><br><span>## $TXID</span><br><span>## [1] "1" "2" "3" "4" "5" "6"</span><br><span>## </span><br><span>## $TXNAME</span><br><span>## [1] "ENST00000456328.2" "ENST00000450305.2" "ENST00000473358.1" "ENST00000469289.1" "ENST00000607096.1" "ENST00000606857.1"</span><br></code></pre><p>这里需要注意：所谓的TXNAME，并不是基因symbol，而是转录ID</p><p>这里同样为了验证下结果，我们利用几个GENEID，去检查下对应的TXNAME：</p><pre><code><span># 检索指定信息</span><br><span>if</span> (<span>T</span>) {<br>  keys &lt;- c(<span>"ENSG00000000460.17"</span>,<span>"ENSG00000000938.13"</span>)<br>  select(txdb,keys=keys,keytype=<span>"GENEID"</span>,column=c(<span>"TXNAME"</span>,<span>"TXID"</span>))  <br>}<br><span>##                GENEID  TXID             TXNAME</span><br><span>## 1  ENSG00000000460.17  8329  ENST00000498289.5</span><br><span>## 2  ENSG00000000460.17  8330  ENST00000472795.5</span><br><span>## 3  ENSG00000000460.17  8331  ENST00000359326.9</span><br><span>## 4  ENSG00000000460.17  8332  ENST00000496973.5</span><br><span>## 5  ENSG00000000460.17  8333  ENST00000481744.5</span><br><span>## 6  ENSG00000000460.17  8334  ENST00000466580.6</span><br><span>## 7  ENSG00000000460.17  8335  ENST00000459772.5</span><br><span>## 8  ENSG00000000460.17  8336 ENST00000286031.10</span><br><span>## 9  ENSG00000000460.17  8337  ENST00000413811.3</span><br><span>## 10 ENSG00000000938.13 13150  ENST00000374005.8</span><br><span>## 11 ENSG00000000938.13 13151  ENST00000399173.5</span><br><span>## 12 ENSG00000000938.13 13152  ENST00000374004.5</span><br><span>## 13 ENSG00000000938.13 13153  ENST00000374003.7</span><br><span>## 14 ENSG00000000938.13 13154  ENST00000457296.5</span><br><span>## 15 ENSG00000000938.13 13155  ENST00000475472.5</span><br><span>## 16 ENSG00000000938.13 13156  ENST00000468038.1</span><br></code></pre><p>可以看到，我选择了2个基因，这两个基因分别对应不同的转录本数目：</p><table width="100"><thead><tr><th>GENEID</th><th>The number of Transcripts</th></tr></thead><tbody><tr><td>ENSG00000000460.17</td><td>9</td></tr><tr><td>ENSG00000000938.13</td><td>7</td></tr></tbody></table><p>接下来我们去gtf文件中进行验证：</p><pre><code>$ zgrep <span>"ENSG00000000460.17"</span> gencode.v40.annotation.gtf.gz|awk -F<span>"\t"</span> <span>'{if($3=="transcript")print $0}'</span>|wc<br>      9     326    3949<br>$ zgrep <span>"ENSG00000000938.13"</span> gencode.v40.annotation.gtf.gz|awk -F<span>"\t"</span> <span>'{if($3=="transcript")print $0}'</span>|wc<br>      7     264    3069<br></code></pre><p>可以看到，结果是一致的。</p><h4><span>3.3 检索GRange对象</span></h4><p>以下是几种最常用的函数：</p><ul><li><p><code>transcripts</code> :可以通过 <code>filter</code> 参数对染色体、正负链、转录本ID和NAME进行限制</p></li><li><p><code>exons</code> :可以通过 <code>filter</code> 参数对染色体、正负链、外显子ID和NAME进行限制</p></li><li><p><code>cds</code> :可以通过 <code>filter</code> 参数对染色体、正负链、CDS的ID和NAME进行限制</p></li><li><p><code>promoters</code> :可以通过 <code>upstream</code> 和 <code>downstream</code> 参数对TSS上下游范围进行限定</p></li></ul><pre><code><span># 检索GRange对象</span><br><span>if</span> (<span>T</span>) {<br>  <span># transcripts</span><br>  <span>if</span> (<span>T</span>) {<br>    <span># 全部转录本</span><br>    GR &lt;- transcripts(txdb)<br>    GR<br>    <span># 加上限制条件，一般仅针对chrom和strand,也可对id,name进行限制</span><br>    GR &lt;- transcripts(txdb,filter=list(tx_chrom=<span>"chr6"</span>,tx_strand=<span>"+"</span>))<br>    GR<br>  }<br>  <span># promoter,需要人为定义上下游距离</span><br>  <span>if</span> (<span>T</span>) {<br>    PR &lt;- promoters(txdb, upstream=<span>2000</span>, downstream=<span>400</span>)<br>    PR<br>  }<br>  <span># cds和exons用法与transcripts一致</span><br>}<br></code></pre><p>这些函数取得Grange对象后，后面的操作则主要是针对grange对象进行，具体可以参考</p><ul><li><p><a href="https://mp.weixin.qq.com/s?__biz=MjM5NTk0Mzg2Nw==&amp;mid=2247483787&amp;idx=1&amp;sn=f4e15077059f65306562fde01256042d&amp;scene=21#wechat_redirect" data-linktype="2">IRanges对象和GRanges对象的介绍</a></p></li><li><p><span>https://www.jianshu.com/p/b473a1ba95b2</span></p></li></ul><pre><code><span># grange对象的一系列操作(https://www.jianshu.com/p/b473a1ba95b2)</span><br><span>if</span> (<span>T</span>) {<br>  <span># seqnames</span><br>  <span>if</span> (<span>T</span>) {<br>    seqnames(GR)<br>  }<br>  <span># start and end</span><br>  <span>if</span> (<span>T</span>) {<br>    start(GR)<br>    end(GR)<br>  }<br>  <span># range</span><br>  <span>if</span> (<span>T</span>) {<br>    range(GR)<br>  }<br>  <span># strand</span><br>  <span>if</span> (<span>T</span>) {<br>    tx_strand &lt;- strand(GR)<br>    tx_strand<br>    sum(runLength(tx_strand))<br>  }<br>  <span># 一次性提取seqnames、ranges、strand</span><br>  <span>if</span> (<span>T</span>) {<br>    <span># GRanges函数用于建立对象</span><br>    <span># granges函数用于从对象中提取granges信息</span><br>    granges(GR)<br>  }<br>  <span># 一次性提取meta信息</span><br>  <span>if</span> (<span>T</span>) {<br>    <span># get a dataframe</span><br>    mcols(GR)<br>  }<br><br>  <span># total row number</span><br>  <span>if</span> (<span>T</span>) {<br>    length(GR)<br>  }<br>  <span># width</span><br>  <span>if</span> (<span>T</span>) {<br>    summary(width(GR))<br>  }<br>}<br></code></pre><h4><span>3.4 分组统计</span></h4><p>主要涉及的函数包括：</p><ul><li><p><code>transcriptsBy</code> :可以通过cds，exon或者gene对transcripts进行分组</p></li><li><p><code>exonsBy</code> :可以通过transcript或者gene对exons进行分组</p></li><li><p><code>cdsBy</code> :可以通过transcript或者gene对cds进行分组</p></li><li><p><code>intronsByTranscript</code> :可以通过transcript对introns进行分组</p></li><li><p><code>fiveUTRsByTranscript</code> :可以通过transcript对5UTRs进行分组</p></li><li><p><code>threeUTRsByTranscript</code> :可以通过transcript对3UTRs进行分组</p></li></ul><pre><code><span># 分组讨论</span><br><span>if</span> (<span>T</span>) {<br>  <span># transcriptsBy</span><br>  <span>if</span> (<span>T</span>) {<br>    transcriptsBy(txdb,by=<span>"gene"</span>)<br>    transcriptsBy(txdb,by=<span>"exon"</span>)<br>    transcriptsBy(txdb,by=<span>"cds"</span>)<br>  }<br>  <span># exonsBy</span><br>  <span>if</span> (<span>T</span>) {<br>    exonsBy(txdb,by=<span>"tx"</span>)<br>    exonsBy(txdb,by=<span>"gene"</span>)<br>  }<br>  <span># cdsBy</span><br>  <span>if</span> (<span>T</span>) {<br>    cdsBy(txdb,by=<span>"tx"</span>)<br>    cdsBy(txdb,by=<span>"gene"</span>)<br>  }<br>  <span># intronsByTranscript</span><br>  <span>if</span> (<span>T</span>) {<br>    intronsByTranscript(txdb)<br>  }<br>  <span># fiveUTRsByTranscript</span><br>  <span>if</span> (<span>T</span>) {<br>    fiveUTRsByTranscript(txdb)<br>  }<br>  <span># threeUTRsByTranscript</span><br>  <span>if</span> (<span>T</span>) {<br>    threeUTRsByTranscript(txdb)<br>  }<br>}<br></code></pre><p>因为这里得到的也是grange对象，所以后面的操作几乎都是依赖于grange对象的，看来后面我们有必要对grange对象做一个系统回顾了。</p><h3><span>后记</span></h3><p>日后有需要再做补充~</p></section><p><br></p><p><mp-style-type data-value="3"></mp-style-type></p></div>

**Comment by DooYal** [comment]
请问一下怎么取txdb的子集，那种可以exonsby, transcriptby可以识别的形式，我直接用data.frame然后subset取了子集后exonsby, transcriptby就不能识别了
