### ISSUE TITLE
免疫相关lncRNAs的泛癌特征识别潜在致癌生物标志物

### ISSUE THREAD

**Issue by ixxmu** [ixxmu/mp_duty#2870]
https://mp.weixin.qq.com/s/2TAze8-eiO55-rRZSh8gaA

**Comment by ixxmu** [comment]
免疫相关lncRNAs的泛癌特征识别潜在致癌生物标志物 by R语言数据分析指南
------
<div><section data-tool="mdnice编辑器" data-website="https://www.mdnice.com"><h3 data-tool="mdnice编辑器"><span></span><span><span></span>欢迎关注R语言数据分析指南</span><span></span></h3><blockquote data-tool="mdnice编辑器"><span>❝</span><p>本节小编来分享一篇2020年在 <strong>「nature communications(IF=17.694)」</strong> 的文章，研究免疫相关lncRNAs的泛癌特征识别潜在致癌生物标志物</p><span>❞</span></blockquote><figure data-tool="mdnice编辑器"><img data-ratio="0.3688340807174888" data-src="https://mmbiz.qpic.cn/mmbiz_png/EibnicgwScTAYpUqJpWtAcSryhHHjPRiaeaibFg6dqNJn9400bv42PLflwKthINgUwnW1K7awDUgBFwZvBzTA7dabA/640?wx_fmt=png" data-type="png" data-w="892" src="https://mmbiz.qpic.cn/mmbiz_png/EibnicgwScTAYpUqJpWtAcSryhHHjPRiaeaibFg6dqNJn9400bv42PLflwKthINgUwnW1K7awDUgBFwZvBzTA7dabA/640?wx_fmt=png"></figure><h3 data-tool="mdnice编辑器"><span></span><span><span></span>免疫相关lncRNAs的泛癌特征识别潜在致癌生物标志物</span><span></span></h3><h4 data-tool="mdnice编辑器"><span></span><span><span></span>背景</span><span></span></h4><blockquote data-tool="mdnice编辑器"><span>❝</span><p>长非编码RNA（lncRNAs）是基因表达的关键调节器，在免疫调节中发挥着重要作用。这里我们介绍一种集成算法ImmLnc，用于识别免疫相关通路的lncRNA调节器。我们全面绘制了33种癌症类型免疫组中lncRNA调节的图景，并表明具有相似组织起源的癌症可能共享lncRNA免疫调节器。此外，免疫相关lncRNAs可能在癌症中表现出表达紊乱，并与免疫细胞浸润显著相关。ImmLnc可以帮助确定癌症相关lncRNA的优先顺序，并进一步确定非小细胞肺癌的三种分子亚型（增殖型、中间型和免疫型）。这些亚型的特征是突变负荷、免疫细胞浸润、免疫调节基因表达、化疗反应和预后的差异。总之，ImmLnc管道和由此产生的数据是了解lncRNA功能和推进免疫治疗靶点识别的宝贵资源。</p><span>❞</span></blockquote><h3 data-tool="mdnice编辑器"><span></span><span><span></span>研究结果</span><span></span></h3><h4 data-tool="mdnice编辑器"><span></span><span><span></span>不同癌症类型免疫相关lncRNA的鉴定</span><span></span></h4><blockquote data-tool="mdnice编辑器"><span>❝</span><p>为了确定与免疫相关通路相关的候选lncRNA调节器，我们提出了一个称为ImmLnc的三步计算框架（图1a）。ImmLnc分三步识别lncRNA调节剂（图1a）。其次，我们计算每个患者的肿瘤纯度，并根据每个候选lncRNA的RS评分对基因进行排序。第三，我们根据改进的基因集富集分析（GSEA）15,16计算每个lncRNA在免疫途径（lncRES）中的活性。将GSEA的P值转换为lncRES分数，并选择lncRES&gt;0.995和错误发现率（FDR）&lt;0.05的lncRNA途径对。</p><span>❞</span></blockquote><h3 data-tool="mdnice编辑器"><span></span><span><span></span>lncRNA调节因子在癌症中的表达扰动</span><span></span></h3><p data-tool="mdnice编辑器">为了深入了解免疫相关lncRNAs的功能，我们进一步研究了在多种癌症类型中发现的500个排名靠前的lncRNA-途径对（图2a和补充数据4），并确定了一个lncRNA途径调控网络。</p><figure data-tool="mdnice编辑器"><img data-ratio="0.71875" data-src="https://mmbiz.qpic.cn/mmbiz_png/EibnicgwScTAYpUqJpWtAcSryhHHjPRiaeakiaicFXfFJiaV8jy6ZZ6vKpibRy5beicjNuJqOU7oRaBdbibLRmtdKt1nWeQ/640?wx_fmt=png" data-type="png" data-w="864" src="https://mmbiz.qpic.cn/mmbiz_png/EibnicgwScTAYpUqJpWtAcSryhHHjPRiaeakiaicFXfFJiaV8jy6ZZ6vKpibRy5beicjNuJqOU7oRaBdbibLRmtdKt1nWeQ/640?wx_fmt=png"></figure><h3 data-tool="mdnice编辑器"><span></span><span><span></span>LncRNA与免疫细胞浸润有关</span><span></span></h3><blockquote data-tool="mdnice编辑器"><span>❝</span><p>免疫反应已被证明涉及免疫细胞的组织浸润25。因此，我们推断，如果ImmLnc识别的lncRNAs在免疫调节中发挥重要作用，那么它们更有可能在免疫细胞中高度表达，并与肿瘤中的免疫细胞浸润相关。这些结果表明，免疫相关lncRNAs在免疫细胞群体中表现出较高的表达。接下来，我们根据肿瘤免疫评估资源（TIMER）29的基因表达，估计了每个病人的免疫细胞浸润水平。这些结果表明，lncRNAs可能在以下方面发挥关键作用 免疫学调节中发挥关键作用。</p><span>❞</span></blockquote><figure data-tool="mdnice编辑器"><img data-ratio="0.7606936416184971" data-src="https://mmbiz.qpic.cn/mmbiz_png/EibnicgwScTAYpUqJpWtAcSryhHHjPRiaeaAAGZErzB8fbpiclDMDiaLJOe1p4XZNOdyXoZpSjaVDg1Gnwaj9BMIUEg/640?wx_fmt=png" data-type="png" data-w="865" src="https://mmbiz.qpic.cn/mmbiz_png/EibnicgwScTAYpUqJpWtAcSryhHHjPRiaeaAAGZErzB8fbpiclDMDiaLJOe1p4XZNOdyXoZpSjaVDg1Gnwaj9BMIUEg/640?wx_fmt=png"></figure><p data-tool="mdnice编辑器">此外，我们使用Fisher精确检验来研究ImmLnc识别的lncRNAs是否可能与免疫细胞浸润相关。我们发现，在大多数癌症类型中，免疫相关lncRNA的比例明显较高，与免疫细胞浸润相关（图3b±g）。此外，我们通过CIBERSORT36确定了与免疫细胞相关的lncRNAs。我们发现它们与TIMER明显重叠（补充数据6）。总之，所有这些结果表明，这些与免疫学相关的lncRNA调节因子在免疫细胞中表现出更高的表达。它们可能与免疫细胞浸润有关，进一步验证了 ImmLnc算法的结果。</p><h3 data-tool="mdnice编辑器"><span></span><span><span></span>ImmLnc优先考虑与癌症相关的lncRNA</span><span></span></h3><blockquote data-tool="mdnice编辑器"><span>❝</span><p>在证明ImmLnc可以有效识别免疫相关lncRNA后，我们接下来探索了ImmLnc在癌症相关lncRNAs优先排序中的应用。我们发现，与基于差异表达的方法相比，这种免疫调节信息的整合在受体特性曲线下的面积更大（补充图15b–c）。当我们考虑所有与免疫有关的lncRNAs时，我们得到了类似的结果（补充图16）。附图16）。这些结果表明，ImmLnc可以优先处理 癌症/疾病相关的lncRNAs.</p><span>❞</span></blockquote><figure data-tool="mdnice编辑器"><img data-ratio="0.9050925925925926" data-src="https://mmbiz.qpic.cn/mmbiz_png/EibnicgwScTAYpUqJpWtAcSryhHHjPRiaeakwzDXSq4bIQ66iaRuTDJJjyghiaxqYg3hvPeEcp07bM1gJrKg2uvyzbQ/640?wx_fmt=png" data-type="png" data-w="864" src="https://mmbiz.qpic.cn/mmbiz_png/EibnicgwScTAYpUqJpWtAcSryhHHjPRiaeakwzDXSq4bIQ66iaRuTDJJjyghiaxqYg3hvPeEcp07bM1gJrKg2uvyzbQ/640?wx_fmt=png"></figure><p data-tool="mdnice编辑器">基于lincRNA的相对等级，我们确定了几种与癌症相关的lincRNA，如LINC00944和SMIM2538,39（图4c）。LINC00944已被证明参与结直肠癌的肝转移过程39。我们发现该lincRNA在六种癌症类型中表现出显著的表达紊乱，包括乳腺癌、肾癌、肺癌和结直肠癌（图4d）。</p><h3 data-tool="mdnice编辑器"><span></span><span><span></span>免疫lncRNAs对癌症的分子亚型进行分类</span><span></span></h3><blockquote data-tool="mdnice编辑器"><span>❝</span><p>除了识别癌症中的关键分子外,癌症亚型鉴定是改善个性化治疗的关键。因此，我们接下来调查了ImmLnc识别的lncRNAs在多大程度上可以应用于分子癌症亚型分析。虽然C1亚型的男性患者较多（图5b。P = 0.002，双侧Fisher's精确检验），但在癌症分期和吸烟状况方面没有观察到差异。三种亚型之间没有观察到癌症分期和吸烟状况的差异。（补充图19c-d）。</p><span>❞</span></blockquote><h3 data-tool="mdnice编辑器"><span></span><span><span></span>免疫分析提示存在免疫亚型</span><span></span></h3><blockquote data-tool="mdnice编辑器"><span>❝</span><p>肿瘤突变负荷（TMB）正在成为免疫治疗的潜在生物标记44,45。在检查肺癌患者中的TMB分布时，我们发现C2患者的TMB高于其他亚型患者（图6a和补充图20a）。此外，同源重组缺陷（HRD）仍然是一种重要的生物标记物，也是增强肿瘤免疫原性的潜在有效辅助物46。我们比较了不同亚型的HRD评分。我们发现C1和C2患者的HDR得分显著高于C3患者（图6b，P&lt;0.001，单侧Wilcoxon秩和检验）。接下来，我们研究了肺癌患者的免疫、免疫细胞溶解活性（CYT）和主要组织相容性复合体（MHC）评分的分布。所有这些分数都被证明是预测免疫反应的有用生物标记47，48。我们发现C2患者的免疫、CYT和MHC分数明显高于其他患者（图6e，P&lt;0.001；Kolmogorov–Smirnov检验）。此外，我们还检测了Tcell信号通路的基因表达谱。</p><span>❞</span></blockquote><h3 data-tool="mdnice编辑器"><span></span><span><span></span>ImmLnc：癌症免疫lncRNA的网络资源</span><span></span></h3><blockquote data-tool="mdnice编辑器"><span>❝</span><p>为了帮助研究人员将本研究中描述的原理应用于任何感兴趣的疾病，我们开发了一个全面的交互式ImmLnc网络资源（http:///bio-bigdata.hrbmu.edu.cn/ImmLnc）。通过该平台，用户可以查询特定癌症背景下感兴趣的lncRNA或免疫相关途径（图7a）。</p><span>❞</span></blockquote><h3 data-tool="mdnice编辑器"><span></span><span><span></span>研究总结</span><span></span></h3><blockquote data-tool="mdnice编辑器"><span>❝</span><p>越来越多的证据表明，lncRNAs是重要的免疫调节器。然而，到目前为止，只有少数例子被确认。在这项研究中，我们报告了使用ImmLnc算法来系统地识别可能调节免疫相关途径的lncRNA调节器。我们已经证明了lncRNAs是33种癌症类型中免疫调节的积极参与者。值得注意的是，与免疫有关的lncRNAs可能在免疫细胞中表现出更高的表达，显示出表达的扰动，并与免疫细胞的浸润明显相关。此外，通过两个应用，我们证明了ImmLnc有助于优先考虑癌症相关的lncRNAs，并确定了具有不同免疫学特征的癌症亚型。基于网络的ImmLnc平台 形式提供了一个宝贵的资源来研究lncRNAs在免疫调节中的功能。lncRNAs在免疫调节中的功能。</p><span>❞</span></blockquote><figure data-tool="mdnice编辑器"><img data-ratio="1.1514450867052024" data-src="https://mmbiz.qpic.cn/mmbiz_png/EibnicgwScTAYpUqJpWtAcSryhHHjPRiaeahjzKsP88OWdw4QkhkmsKejBgxOSz19F6ZIXicHkTnFyhANoxYTXyb7g/640?wx_fmt=png" data-type="png" data-w="865" src="https://mmbiz.qpic.cn/mmbiz_png/EibnicgwScTAYpUqJpWtAcSryhHHjPRiaeahjzKsP88OWdw4QkhkmsKejBgxOSz19F6ZIXicHkTnFyhANoxYTXyb7g/640?wx_fmt=png"></figure><figure data-tool="mdnice编辑器"><img data-ratio="0.9762752075919335" data-src="https://mmbiz.qpic.cn/mmbiz_png/EibnicgwScTAYpUqJpWtAcSryhHHjPRiaeacZv543jz8UpeB3uJEc5c38h7OFJ9q9r1Xl0wl9Cqz3Tbnb5BuFrqmQ/640?wx_fmt=png" data-type="png" data-w="843" src="https://mmbiz.qpic.cn/mmbiz_png/EibnicgwScTAYpUqJpWtAcSryhHHjPRiaeacZv543jz8UpeB3uJEc5c38h7OFJ9q9r1Xl0wl9Cqz3Tbnb5BuFrqmQ/640?wx_fmt=png"></figure><blockquote data-tool="mdnice编辑器"><span>❝</span><p>LncRNAs正在成为免疫系统中基因表达的关键调节器，并在癌症的发展和进展中发挥关键作用。随着免疫细胞中单细胞测序数据的不断增加，ImmLnc可以帮助识别免疫学中更多的lncRNA调节因子。我们分析了免疫相关的lncRNAs在各种免疫细胞的公开测序数据中的表达。我们发现，免疫相关的lncRNAs和与免疫细胞浸润相关的lncRNAs在B细胞和T细胞中可能表现出明显的高表达（补充图10）.</p><span>❞</span></blockquote><figure data-tool="mdnice编辑器"><img data-ratio="0.5352601156069364" data-src="https://mmbiz.qpic.cn/mmbiz_png/EibnicgwScTAYpUqJpWtAcSryhHHjPRiaeaKl5yaq3veztN494QarIaxWr1B0weaD70lphk6boJmBMrSEhbOSXFsQ/640?wx_fmt=png" data-type="png" data-w="865" src="https://mmbiz.qpic.cn/mmbiz_png/EibnicgwScTAYpUqJpWtAcSryhHHjPRiaeaKl5yaq3veztN494QarIaxWr1B0weaD70lphk6boJmBMrSEhbOSXFsQ/640?wx_fmt=png"></figure><blockquote data-tool="mdnice编辑器"><span>❝</span><p>这些结果表明，一部分lncRNAs可以在足够稳健的表达水平上检测到，作为生物标记物。第三，基于免疫途径的调节和与免疫细胞浸润的相关性，我们已经证明，ImmLnc可以表征不同的癌症亚型（增殖型、中间型和免疫型），它们对化疗有不同的反应。最后，我们重点关注Immport17中的17个免疫相关基因集，Immport27是最大的免疫数据开放存储库之一。ImmLnc管道也可以扩展到其他功能基因集（如必要基因），以识别lncRNA调节器。此外，ImmLnc的想法不仅限于剖析lncRNA的调节，还可用于识别对免疫相关通路至关重要的其他调节因子（如转录因子和microRNA）。</p><span>❞</span></blockquote><blockquote data-tool="mdnice编辑器"><span>❝</span><p>识别lncRNA的靶点是研究其功能的关键步骤。然而，已经确定了有限的目标。在本研究中，我们确定了与lncRNA表达相关的基因，并进一步研究了丰富的免疫途径。然而，确定特定的lncRNA如何影响基因表达仍然是一个挑战。lncRNA发挥其功能的许多潜在方式已经被揭示，包括作为信号lncRNA或支架lncRNAs50。随着以RNA为中心的方法的发展，例如通过RNA纯化分离染色质51和捕获杂交分析RNA目标52，我们将能够在本地环境中识别lncRNA的相互作用目标。识别这些靶点将进一步提高我们对lncRNA介导的免疫途径调控的认识，并促进我们对lnc RNA功能的理解。总之，lncRNAs代表了免疫系统复杂性的另一层。我们必须了解lncRNAs在免疫调节中的功能。继续研究此处确定的免疫相关lncRNAs将有助于开发更好的人类癌症和其他疾病免疫疗法。</p><span>❞</span></blockquote><h4 data-tool="mdnice编辑器"><span></span><span><span></span>对本文分析内容感兴趣的观众老爷欢迎咨询</span><span></span></h4><h3 data-tool="mdnice编辑器"><span></span><span><span></span>小编微信</span><span></span></h3><p><img data-galleryid="" data-ratio="1" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/EibnicgwScTAaNu6sU2UCYkxFq9ibq75wuaO0lqFoYz1icUo4jh3N2icAWECmibgPvqyReur0FCp7JNKO0icnRAsbO9ug/640?wx_fmt=jpeg" data-type="jpeg" data-w="430" src="https://mmbiz.qpic.cn/mmbiz_jpg/EibnicgwScTAaNu6sU2UCYkxFq9ibq75wuaO0lqFoYz1icUo4jh3N2icAWECmibgPvqyReur0FCp7JNKO0icnRAsbO9ug/640?wx_fmt=jpeg"></p><p><span></span></p><h3 data-tool="mdnice编辑器"><span></span><span>关注下方公众号下回更新不迷路</span><span></span></h3><section><mp-common-profile data-pluginname="mpprofile" data-id="Mzg3MzQzNTYzMw==" data-headimg="http://mmbiz.qpic.cn/mmbiz_png/EibnicgwScTAZF0rpeZII9Ltl26VbVagriczTria1fib3XgjwwHEHFjPzkmGpqWDVVHBSzhENictUM2iavAKiaM5lc9USw/0?wx_fmt=png" data-nickname="R语言数据分析指南" data-alias="YanJANtwo" data-signature="R语言重症爱好者，喜欢绘制各种精美的图表，喜欢的小伙伴可以关注我，跟我一起学习" data-from="0" data-is_biz_ban="0"></mp-common-profile></section></section><p><mp-style-type data-value="3"></mp-style-type></p></div>

**Comment by R97416032** [comment]
有没有源码可以分享一下吖
