### ISSUE TITLE
一行代码完成单细胞数据人鼠基因同源转换

### ISSUE THREAD

**Issue by ixxmu** [ixxmu/mp_duty#3032]
https://mp.weixin.qq.com/s/UZVqsmWICDGCLlwM8jRy9g

**Comment by ixxmu** [comment]
一行代码完成单细胞数据人鼠基因同源转换 by 生信随笔
------
<div><section data-tool="mdnice编辑器" data-website="https://www.mdnice.com"><p data-tool="mdnice编辑器"><strong>首先，为什么要进行人和小鼠等物种的基因ID转换？</strong></p><p data-tool="mdnice编辑器">例如小鼠和人的单细胞数据整合分析，一些工具目前只适用人的单细胞数据，例如cellchat等。为了解决这些问题，进行人和小鼠等物种的基因ID转换是一个比较好的策略。</p><p data-tool="mdnice编辑器">基因ID的同源转换，思路可以参考我写的帖子：<a href="https://mp.weixin.qq.com/s?__biz=Mzg5MjcxNzg1NA==&amp;mid=2247483932&amp;idx=1&amp;sn=1e2fe2f459032ad440d28817c238e670&amp;scene=21#wechat_redirect" data-linktype="2">关于基因ID转换，一文就够了</a>。具体操作的话，需要在这个帖子的基础上进行修改。这个帖子提供了两种思路进行ID转换，一个是利用org.Hs.eg.db包，第二个思路是biomaRt包。由于10X用的是最新的注释文件，这里强烈推荐使用biomaRt包进行ID转换。具体代码如下：</p><h2 data-tool="mdnice编辑器"><span></span><span></span><span>一. ID转换所需的数据和函数</span><span></span><span></span></h2><p data-tool="mdnice编辑器">首先需要biomaRt_ensembl数据库：</p><blockquote data-tool="mdnice编辑器"><p>由于biomaRt_ensembl站点在国外，国内使用下载比较慢，因此建议下载好之后反复使用后台回复：GEO 即可获取</p></blockquote><pre data-tool="mdnice编辑器"><span></span><code><span># 加载biomaRt_ensembl数据</span><br>load(<span>"./biomaRt_ensembl_annotation.Rdata"</span>)<br></code></pre><p data-tool="mdnice编辑器">下面我写了一个转换的函数，该函数支持Seurat数据作为input数据：</p><pre data-tool="mdnice编辑器"><span></span><code>convertMouseGeneList.Seurat &lt;- <span>function</span>(seurat.data,<br>                                        Mus.data = <span>F</span>,<br>                                        Human.data = <span>F</span>,<span>...</span>){<br>  count.data = seurat.data@assays$RNA@counts<br>  meta.data = seurat.data@meta.data<br>  <br>  <span># mouse转Human</span><br>  convertMouseGeneList &lt;- <span>function</span>(x = x){<br>    <span>require</span>(<span>"biomaRt"</span>)<br>    <span># human &lt;- useMart("ensembl", dataset = "hsapiens_gene_ensembl", host = "https://dec2021.archive.ensembl.org/")</span><br>    <span># mouse &lt;- useMart("ensembl", dataset = "mmusculus_gene_ensembl", host = "https://dec2021.archive.ensembl.org/")</span><br>    <span># save(human,mouse,file = "./biomaRt_ensembl_annotation.Rdata")</span><br>    genesV2 = getLDS(attributes = c(<span>"mgi_symbol"</span>), filters = <span>"mgi_symbol"</span>, <br>                     values = x , mart = mouse, attributesL = c(<span>"hgnc_symbol"</span>), martL = human, uniqueRows=<span>T</span>)<br>    <span># humanx &lt;- unique(genesV2[, 2])</span><br>    <span># Print the first 6 genes found to the screen</span><br>    print(head(genesV2))<br>    <span>return</span>(genesV2)<br>  }<br>  <br>  <span># Human转mouse</span><br>  convertHumanGeneList &lt;- <span>function</span>(x){<br>    <span>require</span>(<span>"biomaRt"</span>)<br>    <span># human &lt;- useMart("ensembl", dataset = "hsapiens_gene_ensembl", host = "https://dec2021.archive.ensembl.org/")</span><br>    <span># mouse &lt;- useMart("ensembl", dataset = "mmusculus_gene_ensembl", host = "https://dec2021.archive.ensembl.org/")</span><br>    <span># save(human,mouse,file = "./biomaRt_ensembl_annotation.Rdata")</span><br>    genesV2 = getLDS(attributes = c(<span>"hgnc_symbol"</span>), filters = <span>"hgnc_symbol"</span>,<br>                     values = x , mart = human, attributesL = c(<span>"mgi_symbol"</span>), martL = mouse, uniqueRows=<span>T</span>)<br>    <span># humanx &lt;- genesV2</span><br>    <span># Print the first 6 genes found to the screen</span><br>    print(head(genesV2))<br>    <span>return</span>(genesV2)<br>  }<br>  <br>  <span>if</span>(Mus.data){<br>    hum_genes &lt;- convertMouseGeneList(x = row.names(count.data))<br>    head(hum_genes)<br>    hum_genes = hum_genes[!is.na(hum_genes$HGNC.symbol)|hum_genes$HGNC.symbol==<span>""</span>,]<br>    <br>    <span>#### merge</span><br>    count.data = as.data.frame(count.data) %&gt;% rownames_to_column(var = <span>"MGI.symbol"</span>)<br>    count.data = left_join(count.data,hum_genes)<br>    <br>    count.data = count.data %&gt;% <br>      dplyr::select(HGNC.symbol,MGI.symbol,everything())<br>    count.data = count.data[!is.na(count.data$HGNC.symbol),]<br>    <br>    rank.data = rowSums(count.data[,-c(<span>1</span>,<span>2</span>)])<br>    <br>    count.data = count.data[order(rank.data,decreasing = <span>T</span>),]<br>    count.data = count.data[!duplicated(count.data$HGNC.symbol),]<br>    row.names(count.data) =  count.data$HGNC.symbol<br>    count.data = count.data[,-c(<span>1</span>,<span>2</span>)]<br>    sec = CreateSeuratObject(counts = count.data,<br>                             meta.data = meta.data,<br>                             min.cells = <span>0</span>,<br>                             min.features = <span>0</span>)<br>  }<br>  <br>  <span>if</span>(Human.data){<br>    mus_genes &lt;- convertHumanGeneList(x = row.names(count.data))<br>    head(mus_genes)<br>    mus_genes = mus_genes[!is.na(mus_genes$MGI.symbol)|mus_genes$MGI.symbol==<span>""</span>,]<br>    <br>    <span>#### 3.merge</span><br>    count.data = as.data.frame(count.data) %&gt;% rownames_to_column(var = <span>"HGNC.symbol"</span>)<br>    count.data = left_join(count.data,mus_genes)<br>    <br>    count.data = count.data %&gt;% <br>      dplyr::select(HGNC.symbol,MGI.symbol,everything())<br>    <br>    count.data = count.data[!is.na(count.data$MGI.symbol),]<br>    <br>    rank.data = rowSums(count.data[,-c(<span>1</span>,<span>2</span>)])<br>    <br>    count.data = count.data[order(rank.data,decreasing = <span>T</span>),]<br>    count.data = count.data[!duplicated(count.data$MGI.symbol),]<br>    row.names(count.data) =  count.data$MGI.symbol<br>    count.data = count.data[,-c(<span>1</span>,<span>2</span>)]<br>    sec = CreateSeuratObject(counts = count.data,<br>                             meta.data = meta.data,<br>                             min.cells = <span>0</span>,<br>                             min.features = <span>0</span>)<br>  }<br>  <span>return</span>(sec)<br>}<br></code></pre><h2 data-tool="mdnice编辑器"><span></span><span></span><span>二.ID转换实战</span><span></span><span></span></h2><pre data-tool="mdnice编辑器"><span></span><code><span>library</span>(Seurat)<br><span>library</span>(dplyr)<br><span>library</span>(biomaRt)<br><span>library</span>(tibble)<br></code></pre><pre data-tool="mdnice编辑器"><span></span><code><span>#### 1.加载示例数据</span><br><span>library</span>(SeuratData)<br>ifnb.data = LoadData(<span>"ifnb"</span>) <span>#是人的数据</span><br>row.names(ifnb.data)<br></code></pre><p data-tool="mdnice编辑器">测试转换，示例数据是人的，把它转为小鼠：</p><pre data-tool="mdnice编辑器"><span></span><code><span>#### 2.测试</span><br><span>### 2.1 人转鼠</span><br>mus.data = convertMouseGeneList.Seurat(seurat.data = ifnb.data,Human.data = <span>T</span>) <span>#ifnb.data是人的数据</span><br>head(row.names(mus.data))<br><span># [1] "Fth1"     "Ftl1-ps1" "Ftl1"     "B2m"      "Isg15"    "Cxcl10" </span><br><br>mus.data<br><span># An object of class Seurat </span><br><span># 11541 features across 13999 samples within 1 assay </span><br><span># Active assay: RNA (11541 features, 0 variable features)</span><br><span>#人的GAPDH vs. 鼠的</span><br>cor.test(mus.data@assays$RNA@counts[<span>"Gapdh"</span>,],<br>         ifnb.data@assays$RNA@counts[<span>"GAPDH"</span>,]) <span>#1</span><br></code></pre><pre data-tool="mdnice编辑器"><span></span><code><span>### 2.2 鼠转人</span><br>hum.data = convertMouseGeneList.Seurat(seurat.data = mus.data,<br>                                       Human.data = <span>F</span>,Mus.data = <span>T</span>) <span>#ifnb.data是人的数据</span><br>head(row.names(hum.data))<br><span># "FTH1"   "FTL"    "B2M"    "ISG15"  "CXCL10" "TIMP1" </span><br><br>hum.data<br><span># An object of class Seurat </span><br><span># 11053 features across 13999 samples within 1 assay </span><br><span># Active assay: RNA (11053 features, 0 variable features)</span><br><span>#人的GAPDH vs. 鼠的</span><br>cor.test(mus.data@assays$RNA@counts[<span>"Gapdh"</span>,],<br>         hum.data@assays$RNA@counts[<span>"GAPDH"</span>,]) <span>#1</span><br></code></pre><span>- END -</span></section><p><br></p><p><mp-style-type data-value="3"></mp-style-type></p></div>

**Comment by Ane-artist** [comment]
GEO
