### ISSUE TITLE
使用Docker进行BD单细胞转录组数据上游分析--初步尝试

### ISSUE THREAD

**Issue by ixxmu** [ixxmu/mp_duty#3176]
https://mp.weixin.qq.com/s/uyMcThYI7uq9TV1uBLktAw

**Comment by ixxmu** [comment]
使用Docker进行BD单细胞转录组数据上游分析--初步尝试 by 东林的扯淡小屋
------
<div><p>首先安装docker：</p><p>Install Docker Engine on Ubuntu | Docker Documentation</p><p>https://docs.docker.com/engine/install/ubuntu/</p><p><img data-galleryid="" data-ratio="0.5752895752895753" data-s="300,640" data-type="png" data-w="1036" data-src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBqvEdiapqeqVa1CHEtkAg4EBAz2aCDfLsZibB1ibEqXbSsUicZBpXLicR28nfpNsIPI1AJvH9NBcgk5pbg/640?wx_fmt=png" src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBqvEdiapqeqVa1CHEtkAg4EBAz2aCDfLsZibB1ibEqXbSsUicZBpXLicR28nfpNsIPI1AJvH9NBcgk5pbg/640?wx_fmt=png"></p><p><br></p><section><ul><li><li><li><li><li><li><li><li><li><li><li><li><li></ul><pre data-lang="swift"><code><span>#创建名为<span>BD</span>的软件安装环境</span></code><code><span>conda create -n <span>BD</span> python=<span>2</span></span></code><code><span>#查看当前conda环境</span></code><code><span>conda info --envs</span></code><code><span>#激活conda的rna环境</span></code><code><span>conda activate <span>BD</span></span></code><code><span>pip install cwlref-runner</span></code><code><span>sudo apt install nodejs</span></code><code><span># check </span></code><code><span>cwl-runner</span></code><code><span><br></span></code><code><span>wget -<span>c</span> https:<span>//bd-rhapsody-public.s3.amazonaws.com/Rhapsody-WTA/GRCm38-PhiX-gencodevM19/GRCm38-PhiX-gencodevM19-20181206.tar.gz</span></span></code><code><span>wget -<span>c</span> https:<span>//bd-rhapsody-public.s3.amazonaws.com/Rhapsody-WTA/GRCm38-PhiX-gencodevM19/gencodevM19-20181206.gtf</span></span></code></pre></section><p><img data-galleryid="" data-ratio="0.5958686440677966" data-s="300,640" data-type="png" data-w="1888" data-src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBqvEdiapqeqVa1CHEtkAg4EBZliaULO4TXnLBs5ZDoZiaYEZZ3XWFjL7PPjOWukpb1m3t2ssKmrgaQ7Q/640?wx_fmt=png" src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBqvEdiapqeqVa1CHEtkAg4EBZliaULO4TXnLBs5ZDoZiaYEZZ3XWFjL7PPjOWukpb1m3t2ssKmrgaQ7Q/640?wx_fmt=png"></p><p><img data-galleryid="" data-ratio="0.5958686440677966" data-s="300,640" data-type="png" data-w="1888" data-src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBqvEdiapqeqVa1CHEtkAg4EBrlr6PNVMqkgE2zF7SD5vic4Rnh9nrIXjUGKGicZHlLT548ciaPVGU0gPg/640?wx_fmt=png" src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBqvEdiapqeqVa1CHEtkAg4EBrlr6PNVMqkgE2zF7SD5vic4Rnh9nrIXjUGKGicZHlLT548ciaPVGU0gPg/640?wx_fmt=png"></p><p>下载：https://bitbucket.org/CRSwDev/cwl/src/master/<br></p><p><img data-galleryid="" data-ratio="0.4052863436123348" data-s="300,640" data-type="png" data-w="1135" data-src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBqvEdiapqeqVa1CHEtkAg4EBzJCYzicrRd5R4CSB5h3TcQmjZC016kvXX0w7Y0vF51opqAaVlrrhpCQ/640?wx_fmt=png" src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBqvEdiapqeqVa1CHEtkAg4EBzJCYzicrRd5R4CSB5h3TcQmjZC016kvXX0w7Y0vF51opqAaVlrrhpCQ/640?wx_fmt=png"></p><p><img data-galleryid="" data-ratio="0.931958762886598" data-s="300,640" data-type="png" data-w="970" data-src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBqvEdiapqeqVa1CHEtkAg4EBbgeuBUpdVvUDfbkRRTmgdII5CLQHuzhVIUGiawgibbwajNAKsXdQoBVQ/640?wx_fmt=png" src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBqvEdiapqeqVa1CHEtkAg4EBbgeuBUpdVvUDfbkRRTmgdII5CLQHuzhVIUGiawgibbwajNAKsXdQoBVQ/640?wx_fmt=png"></p><p>官方软件安装：<br></p><section><ul><li><li></ul><pre data-lang="properties"><code><span><span>docker pull daocloud.io/bdgenomics/rhapsody</span>:<span>1.9.1</span></span></code><code><span><span>docker</span> <span>images</span></span></code></pre></section><p><img data-galleryid="" data-ratio="0.7235294117647059" data-s="300,640" data-type="png" data-w="1190" data-src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBpu3fJticBrghoDMZDp2iaAZMdKbtc59eMzLgqcweTbT4UpTVj7icCXH02oYs1AltPb3WRrHNvcBPGJA/640?wx_fmt=png" src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBpu3fJticBrghoDMZDp2iaAZMdKbtc59eMzLgqcweTbT4UpTVj7icCXH02oYs1AltPb3WRrHNvcBPGJA/640?wx_fmt=png"></p><p><br></p><section><ul><li><li></ul><pre data-lang="css"><code><span># 备份一下配置文件</span></code><code><span><span>cp</span> <span>template_wta_1</span><span>.9</span><span>.1</span><span>.yml</span> <span>my_wta_1</span><span>.9</span><span>.1-2022-08-29_11-57</span><span>.yml</span></span></code></pre></section><p>然后修改：<br></p><section><ul><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li></ul><pre data-lang="shell"><code><span><span>#</span>!/usr/bin/env cwl-runner</span></code><code><span><br></span></code><code><span>cwl:tool: rhapsody</span></code><code><span><br></span></code><code><span><span>#</span> This is a template YML file used to specify the inputs <span>for</span> a BD Genomics WTA Rhapsody Analysis pipeline run. See the</span></code><code><span><span>#</span> BD Genomics Analysis Setup User Guide (Doc ID: 47383) <span>for</span> more details. Enter the following information:</span></code><code><span><br></span></code><code><span><br></span></code><code><span><span>#</span><span># Reads (required) - Path to your read files in the FASTQ.GZ format. You may specify as many R1/R2 read pairs as you want.</span></span></code><code><span>Reads:</span></code><code><span><br></span></code><code><span> - class: File</span></code><code><span>   location: "/data/yudonglin/reference/singcell/BD/hCS_Run1_S1_L001_R1_001.fastq.gz"</span></code><code><span> - class: File</span></code><code><span>   location: "/data/yudonglin/reference/singcell/BD/hCS_Run1_S1_L001_R2_001.fastq.gz"</span></code><code><span><br></span></code><code><span> - class: File</span></code><code><span>   location: "/data/yudonglin/reference/singcell/BD/hCS_Run1_S2_L002_R1_001.fastq.gz"</span></code><code><span> - class: File</span></code><code><span>   location: "/data/yudonglin/reference/singcell/BD/hCS_Run1_S2_L002_R2_001.fastq.gz"</span></code><code><span><br></span></code><code><span><span>#</span><span># Reference_Genome (required) - Path to STAR index for tar.gz format. See Doc ID: 47383 for instructions to obtain pre-built STAR index file.</span></span></code><code><span>Reference_Genome:</span></code><code><span>   class: File</span></code><code><span>   location: "/data/yudonglin/reference/singcell/BD/ref/GRCm38-PhiX-gencodevM19-20181206.tar.gz"</span></code><code><span><br></span></code><code><span><span>#</span><span># Transcriptome_Annotation (required) - Path to GTF annotation file</span></span></code><code><span>Transcriptome_Annotation:</span></code><code><span>   class: File</span></code><code><span>   location: "/data/yudonglin/reference/singcell/BD/ref/gencodevM19-20181206.gtf"</span></code><code><span><br></span></code><code><span><span>#</span><span># AbSeq_Reference (optional) - Path to the AbSeq reference file in FASTA format.  Only needed if BD AbSeq Ab-Oligos are used.</span></span></code><code><span><span>#</span>AbSeq_Reference:</span></code><code><span><span>#</span> - class: File</span></code><code><span><span>#</span>   location: <span>"test/AbSeq_reference.fasta"</span></span></code><code><span><br></span></code><code><span><span>#</span><span># Supplemental_Reference (optional) - Path to the supplemental reference file in FASTA format.  Only needed if there are additional transgene sequences used in the experiment.</span></span></code><code><span><span>#</span>Supplemental_Reference:</span></code><code><span><span>#</span> - class: File</span></code><code><span><span>#</span>   location: <span>"test/supplemental_reference.fasta"</span></span></code><code><span><br></span></code><code><span><span>#</span><span>###################################</span></span></code><code><span><span>#</span><span># Putative Cell Calling Settings ##</span></span></code><code><span><span>#</span><span>###################################</span></span></code><code><span><br></span></code><code><span><span>#</span><span># Exact cell count - Set a specific number (&gt;=1) of cells as putative, based on those with the highest error-corrected read count</span></span></code><code><span><span>#</span>Exact_Cell_Count: 10000</span></code><code><span><br></span></code><code><span><span>#</span><span># Disable Refined Putative Cell Calling - Determine putative cells using only the basic algorithm (minimum second derivative along the cumulative reads curve).  The refined algorithm attempts to remove false positives and recover false negatives, but may not be ideal for certain complex mixtures of cell types.  Does not apply if Exact Cell Count is set.</span></span></code><code><span><span>#</span><span># values can be true or false.</span></span></code><code><span><span>#</span>Basic_Algo_Only: <span>true</span></span></code><code><span><br></span></code><code><span><span>#</span><span>#######################</span></span></code><code><span><span>#</span><span># Subsample Settings ##</span></span></code><code><span><span>#</span><span>#######################</span></span></code><code><span><br></span></code><code><span><span>#</span><span># Subsample (optional) - A number &gt;1 or fraction (0 &lt; n &lt; 1) to indicate the number or percentage of reads to subsample.</span></span></code><code><span><span>#</span>Subsample: 0.01</span></code><code><span><br></span></code><code><span><span>#</span><span># Subsample seed (optional) - A seed for replicating a previous subsampled run.</span></span></code><code><span><span>#</span>Subsample_seed: 3445</span></code><code><span><br></span></code><code><span><span>#</span><span>######################</span></span></code><code><span><span>#</span><span># Multiplex options ##</span></span></code><code><span><span>#</span><span>######################</span></span></code><code><span><br></span></code><code><span><span>#</span><span># Sample Tags Version (optional) - Specify if multiplexed run: human, hs, mouse or mm</span></span></code><code><span><span>#</span>Sample_Tags_Version: mouse</span></code><code><span><br></span></code><code><span><span>#</span><span># Subsample Sample Tags (optional) -  A number &gt;1 or fraction (0 &lt; n &lt; 1) to indicate the number or percentage of reads to subsample.</span></span></code><code><span><span>#</span>Subsample_Tags: 0.05</span></code><code><span><br></span></code><code><span><span>#</span><span># Tag_Names (optional) - Specify the tag number followed by '-' and the desired sample name to appear in Sample_Tag_Metrics.csv</span></span></code><code><span><span>#</span> Do not use the special characters: &amp;, (), [], {},  &lt;&gt;, ?, |</span></code><code><span><span>#</span>Tag_Names: [hCS_Run1]</span></code></pre></section><p>开始运行：<br></p><p><img data-galleryid="" data-ratio="1.1815286624203822" data-s="300,640" data-type="png" data-w="942" data-src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBqvEdiapqeqVa1CHEtkAg4EBdA9Oib9ArlZXNnFwmWfx24un5TrlNaEclWQFSzTQ2FbOZRz5esBQLuw/640?wx_fmt=png" src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBqvEdiapqeqVa1CHEtkAg4EBdA9Oib9ArlZXNnFwmWfx24un5TrlNaEclWQFSzTQ2FbOZRz5esBQLuw/640?wx_fmt=png"></p><section><ul><li><li></ul><pre data-lang="kotlin"><code><span>cwl-runner --parallel --tmpdir-prefix tmp_ --outdir /<span>data</span>/yudonglin/reference/singcell/BD/scRNA-<span>out</span> /<span>data</span>/yudonglin/reference/singcell/BD/cwl/v1.9.1/rhapsody_wta_1.9.1.cwl /<span>data</span>/yudonglin/reference/singcell/BD/cwl/v1.9.1/my_wta_1.9.1-<span>2022</span>-<span>08</span>-<span>29_11</span>-<span>57</span>.yml</span></code><code><span><br></span></code></pre></section><p><img data-galleryid="" data-ratio="0.5958686440677966" data-s="300,640" data-type="png" data-w="1888" data-src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBpu3fJticBrghoDMZDp2iaAZMBMusbkpnkLHiaqhFnPt9UiaIDRsWXT1Gzuk8ggEDeX9ZlkoKLuVhZia2A/640?wx_fmt=png" src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBpu3fJticBrghoDMZDp2iaAZMBMusbkpnkLHiaqhFnPt9UiaIDRsWXT1Gzuk8ggEDeX9ZlkoKLuVhZia2A/640?wx_fmt=png"></p><p><br></p><p><br></p><p>参考资料：</p><p>BD Single-Cell Multiomics Analysis Setup User Guide (bdbiosciences.com)</p><p>https://www.bdbiosciences.com/content/dam/bdb/marketing-documents/BD_Single_Cell_Genomics_Analysis_Setup_User_Guide_v2.pdf</p><p>CRSwDev / cwl — Bitbucket</p><p>https://bitbucket.org/CRSwDev/cwl/src/master/</p><p>https://omicx.cc/posts/2021-06-24-setup-bd-single-cell-genomics-rhapsody-analysis/</p><p> BD Rhapsody单细胞分析系统_bd 上游分析流程_TTS56的博客-CSDN博客</p><p>https://blog.csdn.net/qq_40966210/article/details/126585259</p><p><img data-galleryid="" data-ratio="0.45448798988621997" data-s="300,640" data-type="png" data-w="1582" data-src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBqvEdiapqeqVa1CHEtkAg4EBw0Op9z2BatDScYsLxtXUxCic4EerCOXrL1mYQsLaU4IuLWAXibflUu9A/640?wx_fmt=png" src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBqvEdiapqeqVa1CHEtkAg4EBw0Op9z2BatDScYsLxtXUxCic4EerCOXrL1mYQsLaU4IuLWAXibflUu9A/640?wx_fmt=png"></p><p>https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE93811</p><p><img data-galleryid="" data-ratio="1.143418467583497" data-s="300,640" data-type="png" data-w="1018" data-src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBqvEdiapqeqVa1CHEtkAg4EBwUibQEaxzZhNPBDbCwXRwNsxYZJnWg8MHu0U8SjTjTFJpw3YGSJglmQ/640?wx_fmt=png" src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBqvEdiapqeqVa1CHEtkAg4EBwUibQEaxzZhNPBDbCwXRwNsxYZJnWg8MHu0U8SjTjTFJpw3YGSJglmQ/640?wx_fmt=png"></p><p><img data-galleryid="" data-ratio="0.748135874067937" data-s="300,640" data-type="png" data-w="1207" data-src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBqvEdiapqeqVa1CHEtkAg4EBWUXIEcmXssv6pBAbibGHvE5CGtjM9TKT3yOX4epBpJyzzAsibfP0kRmg/640?wx_fmt=png" src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBqvEdiapqeqVa1CHEtkAg4EBWUXIEcmXssv6pBAbibGHvE5CGtjM9TKT3yOX4epBpJyzzAsibfP0kRmg/640?wx_fmt=png"></p><p><img data-galleryid="" data-ratio="0.8342541436464088" data-s="300,640" data-type="png" data-w="1448" data-src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBqvEdiapqeqVa1CHEtkAg4EBVlPwsjxrbfy6fFuiaOA7Wib0NjHwGvlITbDQkqo09K9vr2x3oVGgcCuw/640?wx_fmt=png" src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBqvEdiapqeqVa1CHEtkAg4EBVlPwsjxrbfy6fFuiaOA7Wib0NjHwGvlITbDQkqo09K9vr2x3oVGgcCuw/640?wx_fmt=png"></p><p><img data-galleryid="" data-ratio="0.2514506769825919" data-s="300,640" data-type="png" data-w="1034" data-src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBpu3fJticBrghoDMZDp2iaAZMj0ph4bqXMxHic2C83BZp0g6xnWH2lHfE87eAUHLoYwrEVRbPoWm0ibkA/640?wx_fmt=png" src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBpu3fJticBrghoDMZDp2iaAZMj0ph4bqXMxHic2C83BZp0g6xnWH2lHfE87eAUHLoYwrEVRbPoWm0ibkA/640?wx_fmt=png"></p><p><img data-galleryid="" data-ratio="0.4788844621513944" data-s="300,640" data-type="png" data-w="1255" data-src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBpu3fJticBrghoDMZDp2iaAZMcibicM0bd9vV7CPibq6WJN0yz27saeoC3WVoIOoq9k0ibvM886VuYrib8WQ/640?wx_fmt=png" src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBpu3fJticBrghoDMZDp2iaAZMcibicM0bd9vV7CPibq6WJN0yz27saeoC3WVoIOoq9k0ibvM886VuYrib8WQ/640?wx_fmt=png"></p><p>顺利运行！<br></p><p><img data-galleryid="" data-ratio="0.6048517520215634" data-s="300,640" data-type="png" data-w="1855" data-src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBpu3fJticBrghoDMZDp2iaAZMAVuAop5ZgB4iaibflvzVjyevYN5eGkjdkLE1IAr7ibjgFjW3t4ibLCDQ3g/640?wx_fmt=png" src="https://mmbiz.qpic.cn/mmbiz_png/kZ1wdgAscBpu3fJticBrghoDMZDp2iaAZMAVuAop5ZgB4iaibflvzVjyevYN5eGkjdkLE1IAr7ibjgFjW3t4ibLCDQ3g/640?wx_fmt=png"></p><p><mp-style-type data-value="3"></mp-style-type></p></div>

**Comment by xutongran** [comment]
The above advice is excellent!  Any more information on how singularity uses BD pipline?
