### ISSUE TITLE
基础教程 | 如何在GEO更新自己已上传的数据集（扩充样本等）

### ISSUE THREAD

**Issue by ixxmu** [ixxmu/mp_duty#3383]
https://mp.weixin.qq.com/s/CnzvN5p9Z6g512I_n9-yWw

**Comment by ixxmu** [comment]
基础教程 | 如何在GEO更新自己已上传的数据集（扩充样本等） by 生信作曲家
------
<div><section><h3><span>前言</span><br></h3><blockquote><p><span></span><span>生信作曲家一直致力于构建国内</span><span><strong>和谐、开放、可持续</strong></span><span><strong>的生物信息交流平台</strong>。生信作曲家的目标是<strong>为每个科研人扫清科研路上的一切障碍，让生物信息学人人可做</strong>。目前，生信作曲家已推出</span><span><strong>"</strong><strong>跟着一区文章学通机器学习”、</strong></span><span><strong>"</strong><strong>跟着一区文章学通单细胞</strong><strong>"、“孟德尔随机化实战”</strong><span><strong>、</strong></span><strong>Bootstrap<span><strong>、</strong></span>CIBERSORTx、NTP、TICPE，metaVIPER算法</strong></span><span>等多种强力教程，同时也兼具</span><strong><span>GEO数据库</span></strong><span>，</span><span><strong>ICGC数据库</strong></span><span>数据整理等核心入门技术教学，开办</span><span><strong>肿瘤发文计划RS、max，非肿瘤发文计划note、ultra、pro、7天发文A计划</strong><strong>，五一创新发文计划pro</strong></span><span><strong>、生信中秋分享会、小年夜分享会、暑期集训营和冬季集训营</strong>等多次。辅导同学实现纯生信SCI发表硕果累累，帮助同学实现医学事业路上的理想与追求。</span></p></blockquote><p>GEO数据上传现有教程已经很多，但是实际上<strong>GEO更新、扩充自己已上传的数据集是常见的操作</strong>（如检测了新的一批样本等），但是目前教程却竟然较缺乏。很多同学有疑问是否有特殊窗口进入更新等。本篇我们带大家实践。</p><figure><figcaption><img data-ratio="0.9675925925925926" data-type="png" data-w="1080" data-src="https://mmbiz.qpic.cn/mmbiz_png/mo60jlFOtaDia67LFicB2SjTiaicz257TbstwgzicD9Tsrbdpicnk6DZ5D5IGyajDE41nH3Gn0KVADxeOB07rZDXeKrw/640?wx_fmt=png" src="https://mmbiz.qpic.cn/mmbiz_png/mo60jlFOtaDia67LFicB2SjTiaicz257TbstwgzicD9Tsrbdpicnk6DZ5D5IGyajDE41nH3Gn0KVADxeOB07rZDXeKrw/640?wx_fmt=png"></figcaption></figure><h3><span>实操教学</span></h3><h4><span>上传数据（和首次上传流程相同）</span></h4><ul><li><p><span>以下是我们进入GEO上传的地点。</span></p></li></ul><figure><figcaption><img data-ratio="0.6833333333333333" data-type="png" data-w="1080" data-src="https://mmbiz.qpic.cn/mmbiz_png/mo60jlFOtaDia67LFicB2SjTiaicz257TbstpGw6HWvoGfEjo57nOQyicQ91JFKNQSuticfn10U3z0pHWBibI7QKyKpfg/640?wx_fmt=png" src="https://mmbiz.qpic.cn/mmbiz_png/mo60jlFOtaDia67LFicB2SjTiaicz257TbstpGw6HWvoGfEjo57nOQyicQ91JFKNQSuticfn10U3z0pHWBibI7QKyKpfg/640?wx_fmt=png"><br><br></figcaption></figure><ul><li><p><strong>需要注意，更新样本的上传数据的流程和首次上传是一模一样的</strong> 我们在transfer file中获取上传的个人站点和密码等可以用一些软件或者服务器ncftp上传，这些教程已经屡见不鲜了，大家尽可以大胆参阅（<span>https://mp.weixin.qq.com/s/3Q7jahyc0Y6crW6R0Lh6Gw</span>）。不过上传时自己创建的文件夹可以显眼命名，例如”<strong>updata_to_GSExxxxx"</strong></p></li></ul><p><br></p><p><img data-ratio="0.7092592592592593" data-type="png" data-w="1080" data-src="https://mmbiz.qpic.cn/mmbiz_png/mo60jlFOtaDia67LFicB2SjTiaicz257Tbsto2ic9S4sWNfTOrrWjbwQENhkIHb8rb9ZMUsSMKUuMN8TWd0K5RtYkTg/640?wx_fmt=png" src="https://mmbiz.qpic.cn/mmbiz_png/mo60jlFOtaDia67LFicB2SjTiaicz257Tbsto2ic9S4sWNfTOrrWjbwQENhkIHb8rb9ZMUsSMKUuMN8TWd0K5RtYkTg/640?wx_fmt=png"></p><p><br></p><ul><li><p><span>结束后我们一般在notify GEO中通知GEO</span></p></li></ul><figure><figcaption><br></figcaption></figure><h4><span>通知官方</span></h4><ul><li><p>之后在notify中<strong>标注清楚更新</strong>，comments有<strong>礼貌地陈述更新需求</strong>。需要注意GEO是真人人工核对的在，保证各项清晰可读</p></li></ul><figure><figcaption><img data-ratio="0.5861111111111111" data-type="png" data-w="1080" data-src="https://mmbiz.qpic.cn/mmbiz_png/mo60jlFOtaDia67LFicB2SjTiaicz257TbstBCQ86D8APPoJmb5pEpb64V2Pj2vssm1U3Qbq0Vd5wU2hpMkkPqdX1A/640?wx_fmt=png" src="https://mmbiz.qpic.cn/mmbiz_png/mo60jlFOtaDia67LFicB2SjTiaicz257TbstBCQ86D8APPoJmb5pEpb64V2Pj2vssm1U3Qbq0Vd5wU2hpMkkPqdX1A/640?wx_fmt=png"></figcaption></figure><h4><span>几天后，成功更新</span></h4><figure><p><img data-ratio="0.18611111111111112" data-type="png" data-w="1080" data-src="https://mmbiz.qpic.cn/mmbiz_png/mo60jlFOtaDia67LFicB2SjTiaicz257Tbstw6kwAeTdVyqAfKrUiaxFKicdWqJ0vpzaeiaUcCl0CYZ3DeToVrfU3p2lQ/640?wx_fmt=png" src="https://mmbiz.qpic.cn/mmbiz_png/mo60jlFOtaDia67LFicB2SjTiaicz257Tbstw6kwAeTdVyqAfKrUiaxFKicdWqJ0vpzaeiaUcCl0CYZ3DeToVrfU3p2lQ/640?wx_fmt=png"></p><p><br></p><p><br></p><section><mp-common-profile data-pluginname="mpprofile" data-weuitheme="light" data-id="MzI5ODI0NzM2OQ==" data-headimg="http://mmbiz.qpic.cn/mmbiz_png/mo60jlFOtaDQIG3BiaPDOAtTJDzqbyPp4crVHnib8fS6Gp6DMjvJJkK9bhPWe6wpNujV93n60FymcjAOfum0t9PA/0?wx_fmt=png" data-nickname="生信作曲家" data-alias="Bioinfo_composer" data-signature="交流生物信息学习经验，分享科研SCI撰写思路和规范，传递最新生物医药资讯。" data-from="0" data-weui-theme="light"></mp-common-profile></section><figcaption><strong><br>加交流群 备注 加群<br><br></strong></figcaption><p><img data-ratio="1.3642105263157895" data-s="300,640" data-type="png" data-w="950" data-src="https://mmbiz.qpic.cn/mmbiz_png/mo60jlFOtaBFwOVFG5iblDrhHKV1D29Sjyn2r1GOSUHEd1SCkFv33cbuGjPflVYzyqkibKPAF85rATyHN4Cia3MEA/640?wx_fmt=png" src="https://mmbiz.qpic.cn/mmbiz_png/mo60jlFOtaBFwOVFG5iblDrhHKV1D29Sjyn2r1GOSUHEd1SCkFv33cbuGjPflVYzyqkibKPAF85rATyHN4Cia3MEA/640?wx_fmt=png"></p><figcaption><strong><br></strong></figcaption></figure></section><p><mp-style-type data-value="3"></mp-style-type></p></div>

**Comment by Nadine-sudo** [comment]
优秀
