### ISSUE TITLE
10X单细胞上游 | 一个样本对应多个SRR ID怎么办？

### ISSUE THREAD

**Issue by ixxmu** [ixxmu/mp_duty#3561]
https://mp.weixin.qq.com/s/Fr_No_AN1O6qsFo8QcmR0Q

**Comment by ixxmu** [comment]
10X单细胞上游 | 一个样本对应多个SRR ID怎么办？ by 生信随笔
------
<div><section data-tool="mdnice编辑器" data-website="https://www.mdnice.com"><p data-tool="mdnice编辑器">我最早学习单细胞上游分析是在2021年底，那会先学习了cellranger环境部署，然后基于三个fastq文件（I1、R1和R2）跑cellranger得到下游数据。后来也遇到过GEO的一些数据集提供的是bam文件而非fastq文件，这个时候需要<strong>bam转fastq，再走cellranger的流程</strong>，详见：</p><ul data-tool="mdnice编辑器"><li><section><a href="https://mp.weixin.qq.com/s?__biz=Mzg5MjcxNzg1NA==&amp;mid=2247483752&amp;idx=1&amp;sn=5d7bb3369c68f5170995861962a6cbd3&amp;scene=21#wechat_redirect" data-linktype="2">一文打通单细胞上游：从软件部署到上游分析</a></section></li></ul><p data-tool="mdnice编辑器">这个过程中也<strong>积累了一些小经验</strong>，比如</p><ul data-tool="mdnice编辑器"><li><section><p>从GEO上下载数据主要有三种方法，prefetch、ascp和kingfisher。而10X数据比较推荐prefetch和ascp，特别是ascp下载速度很快，缺点是有些时候会抽风没办法用。而kingfisher的话，默认参数下载得到的fastq是<strong>不会</strong>split得到I1，R1和R2的，也可能需要额外添加一些参数。当然，这三种方法大家可以尝试一下，对于优缺点会更有体会。</p></section></li><li><section><p>第二个体会是下载得到的SRR文件转fastq文件，使用传统的fastq-dump，速度是非常慢的。推荐使用<strong>fasterq-dump拆解</strong> + <strong>pigz多线程压缩</strong>的方法，速度非常丝滑，大大节省时间。另外fasterq-dump记得加<code>--include-technical</code>参数，才能得到I1，R1和R2三个文件，这里可以参考我在生信技能树上的投稿：</p></section></li><ul><li><section><a href="https://mp.weixin.qq.com/s?__biz=MzAxMDkxODM1Ng==&amp;mid=2247508521&amp;idx=2&amp;sn=2cf3158e74d37b3a741908d8bfc8f02f&amp;scene=21#wechat_redirect" data-linktype="2">10X单细胞转录组测序数据的 SRA转fastq踩坑那些事</a></section></li></ul><li><section><p>第三个小经验是在bam转fastq过程中累积的，我观察到10X bam转fastq输出的fastq文件并不是简单的3个样本I1，R1和R2，而是一个样的几十个Line，<strong>格式为ID名称+SX+L001+I1/R1/R2+001.fastq.gz</strong>，例如：</p><pre><span></span><code>SampleID_S1_L001_I1_001.fastq.gz<br>SampleID_S1_L001_R1_001.fastq.gz<br>SampleID_S1_L001_R2_001.fastq.gz<br>SampleID_S2_L001_I1_001.fastq.gz<br>SampleID_S2_L001_R1_001.fastq.gz<br>SampleID_S2_L001_R2_001.fastq.gz<br>SampleID_S3_L001_I1_001.fastq.gz<br>SampleID_S3_L001_R1_001.fastq.gz<br>SampleID_S3_L001_R2_001.fastq.gz<br>SampleID_S4_L001_I1_001.fastq.gz<br>SampleID_S4_L001_R1_001.fastq.gz<br>SampleID_S4_L001_R2_001.fastq.gz<br></code></pre><p><strong>注意到这个规律之后，也就能回答本文的大标题了：“10X单细胞上游 | 一个样本对应多个SRR ID怎么办？”</strong></p><p>在GEO等公共数据上传的过程中，可能是作者觉得10X的fastq文件太大了，不方便上传（<strong>我猜的</strong>），所以很多作者会把一个10X样本的三个文件，拆解为多个Line，然后分批上传，例如GSE181294这个数据集（https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE181294），</p><p><strong>下面四个SRR都属于同一个样本SAMN20519984/GSM5494342哦：</strong></p></section></li></ul><figure data-tool="mdnice编辑器"><img data-ratio="0.18888888888888888" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqVDTfJrw2XicOadMibMbgkYMHyFQm7pmbfmDTfGLtDjrdAQxTUflcB3afoClR1iaRpXhSuicThHTwExUw/640?wx_fmt=other" data-type="other" data-w="1080" src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqVDTfJrw2XicOadMibMbgkYMHyFQm7pmbfmDTfGLtDjrdAQxTUflcB3afoClR1iaRpXhSuicThHTwExUw/640?wx_fmt=other"><figcaption>image-20230626110346739</figcaption></figure><h3 data-tool="mdnice编辑器">一. 我的解决方案</h3><p data-tool="mdnice编辑器">有了上面的认知之后，解决方案呼之欲出。</p><p data-tool="mdnice编辑器">首先是10X cellranger和这个数据集的下载，参考<a href="https://mp.weixin.qq.com/s?__biz=Mzg5MjcxNzg1NA==&amp;mid=2247483752&amp;idx=1&amp;sn=5d7bb3369c68f5170995861962a6cbd3&amp;scene=21#wechat_redirect" data-linktype="2">一文打通单细胞上游：从软件部署到上游分析</a>即可。</p><p data-tool="mdnice编辑器">第二步是SRR转fastq文件，如上所述用<strong>fasterq-dump拆解</strong> + <strong>pigz多线程压缩</strong>的方法：</p><pre data-tool="mdnice编辑器"><span></span><code>cat &gt;fastq.sh<br>ls SRR* | <span>while</span> <span>read</span> id;<span>do</span> <br>fasterq-dump -O ./ --split-files -e 20 ./<span>$id</span>  --include-technical;<br><span>#rm $id;</span><br>pigz -p 20 ./<span>${id}</span>_1.fastq;<br>pigz -p 20 ./<span>${id}</span>_2.fastq;<br>pigz -p 20 ./<span>${id}</span>_3.fastq;<br><span>done</span><br><br><span>## 运行脚本</span><br>nohup bash fastq.sh &amp;<br></code></pre><p data-tool="mdnice编辑器">第三步是重命名，先对同一个样本的不同Line进行重命名，这个数据集是4个SRR对应1个样本（<strong>需要自行观察meta.data信息</strong>）：</p><pre data-tool="mdnice编辑器"><span></span><code>mv SRR1_1.fastq.gz SampleID1_S1_L001_I1_001.fastq.gz<br>mv SRR1_2.fastq.gz SampleID1_S1_L001_R1_001.fastq.gz<br>mv SRR1_3.fastq.gz SampleID1_S1_L001_R2_001.fastq.gz<br><br>mv SRR2_1.fastq.gz SampleID1_S2_L001_I1_001.fastq.gz<br>mv SRR2_2.fastq.gz SampleID1_S2_L001_R1_001.fastq.gz<br>mv SRR2_3.fastq.gz SampleID1_S2_L001_R2_001.fastq.gz<br><br>mv SRR3_1.fastq.gz SampleID1_S3_L001_I1_001.fastq.gz<br>mv SRR3_2.fastq.gz SampleID1_S3_L001_R1_001.fastq.gz<br>mv SRR3_3.fastq.gz SampleID1_S3_L001_R2_001.fastq.gz<br><br>mv SRR4_1.fastq.gz SampleID1_S4_L001_I1_001.fastq.gz<br>mv SRR4_2.fastq.gz SampleID1_S4_L001_R1_001.fastq.gz<br>mv SRR4_3.fastq.gz SampleID1_S4_L001_R2_001.fastq.gz<br></code></pre><p data-tool="mdnice编辑器">当然这种手动的方法针对很少的样本确实花点时间就能实现，但是一旦样本和Line的数量增加，这种手动的时间成本巨大而且容易出错，所以需要借助Linux脚本的方法。</p><p data-tool="mdnice编辑器">假设Line SRR230806<strong>42</strong>-SRR230806<strong>45</strong>属于sample1，Line SRR230806<strong>46</strong>-SRR230806<strong>49属于sample2</strong>，以此类推有几十个sample，几百个SRR ID，我们首先从meta.data里获取到这种对应关系，然后写入<code>files.txt</code>文件：</p><pre data-tool="mdnice编辑器"><span></span><code>cat &gt;files.txt<br>SRR23080642 sample1<br>SRR23080643 sample1<br>SRR23080644 sample1<br>SRR23080645 sample1<br>SRR23080646 sample2<br>SRR23080647 sample2<br>SRR23080648 sample2<br>SRR23080649 sample2<br></code></pre><p data-tool="mdnice编辑器">当前文件夹：</p><figure data-tool="mdnice编辑器"><img data-ratio="0.06666666666666667" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqVDTfJrw2XicOadMibMbgkYMHt9yPEBNdfJN6RCKibmjiaro6j71SVOEOXuHNlLfbibn7SicZFhkGwB8gRg/640?wx_fmt=other" data-type="other" data-w="1080" src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqVDTfJrw2XicOadMibMbgkYMHt9yPEBNdfJN6RCKibmjiaro6j71SVOEOXuHNlLfbibn7SicZFhkGwB8gRg/640?wx_fmt=other"><figcaption>image-20230626111729388</figcaption></figure><p data-tool="mdnice编辑器">然后写一个批量重命名脚本即可。<strong>这里我本来把这个需求丢给了chatGPT，但是在经过了十几轮问答后，我发现chatGPT并不能解决我这个需求，他给我的脚本甚至一次比一次离谱。所以从这个角度来说，人工智能仍不能完全代替我们。</strong></p><p data-tool="mdnice编辑器">我的脚本如下：</p><ul data-tool="mdnice编辑器"><li><section>首先想到一个粗浅的脚本，有一点瑕疵（也是chatGPT能想到的）：</section></li></ul><pre data-tool="mdnice编辑器"><span></span><code>cat &gt;rename.sh<br>counter=1<br>cat files.txt |<span>while</span> <span>read</span> id;<br><span>do</span>    <br> arr=(<span>${id}</span>)<br> SRR_ID=<span>${arr[0]}</span><br> SAM_ID=<span>${arr[1]}</span><br> <br><span>#echo $SRR_ID</span><br>mv <span>${SRR_ID}</span>_1.fastq.gz <span>${SAM_ID}</span>_S<span>${counter}</span>_L001_I1_001.fastq.gz<br>mv <span>${SRR_ID}</span>_2.fastq.gz <span>${SAM_ID}</span>_S<span>${counter}</span>_L001_R1_001.fastq.gz<br>mv <span>${SRR_ID}</span>_3.fastq.gz <span>${SAM_ID}</span>_S<span>${counter}</span>_L001_R2_001.fastq.gz<br>  <span># 递增计数器</span><br>  counter=$((counter + 1))<br><span>done</span> <br></code></pre><figure data-tool="mdnice编辑器"><img data-ratio="1.6459016393442623" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqVDTfJrw2XicOadMibMbgkYMHh6icP1Nw5b6mAS2mOnjtf2wMxv46zXp2U59Woib2So76KOZM58KnUX9Q/640?wx_fmt=other" data-type="other" data-w="305" src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqVDTfJrw2XicOadMibMbgkYMHh6icP1Nw5b6mAS2mOnjtf2wMxv46zXp2U59Woib2So76KOZM58KnUX9Q/640?wx_fmt=other"><figcaption>image-20230626135134110</figcaption></figure><ul data-tool="mdnice编辑器"><li><section><p>这里可以看到，sample2的SN并不是从S1-S4独立的，虽然这样的fastq也足以运行，但是本着精益求精的态度，我再次进行了修改。</p><p>这里的难点在于不同sample的S需要进行重置，这点chatGPT似乎一直没办法理解，<strong>我灵光一闪，突然想到一段代码</strong>：</p></section></li></ul><pre data-tool="mdnice编辑器"><span></span><code>cat &gt;rename.sh<br>cat files.txt |cut -d <span>" "</span> -f 2 |uniq | <span>while</span> <span>read</span> SAM_ID;<br>    <span>do</span>    <br>    grep <span>$SAM_ID</span> files.txt &gt;tpm.txt<br>    <br>    counter=1<br>    cat tpm.txt |<span>while</span> <span>read</span> id;<br>        <span>do</span>    <br>            arr=(<span>${id}</span>)<br>            SRR_ID=<span>${arr[0]}</span><br>            SAM_ID=<span>${arr[1]}</span><br><br>        <span>#echo $SRR_ID</span><br>        mv <span>${SRR_ID}</span>_1.fastq.gz <span>${SAM_ID}</span>_S<span>${counter}</span>_L001_I1_001.fastq.gz<br>        mv <span>${SRR_ID}</span>_2.fastq.gz <span>${SAM_ID}</span>_S<span>${counter}</span>_L001_R1_001.fastq.gz<br>        mv <span>${SRR_ID}</span>_3.fastq.gz <span>${SAM_ID}</span>_S<span>${counter}</span>_L001_R2_001.fastq.gz<br>        <br>         <span>echo</span> <span>"Renamed <span>${SRR_ID}</span>_1.fastq.gz to <span>${SAM_ID}</span>_S<span>${counter}</span>_L001_I1_001.fastq.gz"</span><br>         <span>echo</span> <span>"Renamed <span>${SRR_ID}</span>_2.fastq.gz to <span>${SAM_ID}</span>_S<span>${counter}</span>_L001_R1_001.fastq.gz"</span><br>         <span>echo</span> <span>"Renamed <span>${SRR_ID}</span>_3.fastq.gz to <span>${SAM_ID}</span>_S<span>${counter}</span>_L001_R2_001.fastq.gz"</span><br>           <br>          <span># 递增计数器</span><br>          counter=$((counter + 1))<br>    <span>done</span> <br>rm tpm.txt    <br><span>done</span> <br></code></pre><figure data-tool="mdnice编辑器"><img data-ratio="1.6506849315068493" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqVDTfJrw2XicOadMibMbgkYMHnuM27KRBgh5UudTGDVhDpbsltrWC4zEBiaTmwnfUMhj1sKSOPN9y1cw/640?wx_fmt=other" data-type="other" data-w="292" src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqVDTfJrw2XicOadMibMbgkYMHnuM27KRBgh5UudTGDVhDpbsltrWC4zEBiaTmwnfUMhj1sKSOPN9y1cw/640?wx_fmt=other"><figcaption>image-20230626135047377</figcaption></figure><p data-tool="mdnice编辑器">非常简朴的代码，好在也完成了这个小需求。</p><h3 data-tool="mdnice编辑器">二. python包easyBio的解决方案</h3><p data-tool="mdnice编辑器">除了我的方案，我前段时间看到一个有意思的python包<code>easyBio</code>，详见</p><ul data-tool="mdnice编辑器"><li><section><p><a href="https://mp.weixin.qq.com/s?__biz=Mzg4Mzk3MDM2Ng==&amp;mid=2247483727&amp;idx=1&amp;sn=d3ff13ae4eed5d49cde95205edafe2bd&amp;scene=21#wechat_redirect" data-linktype="2">单细胞上游：四、震惊！不需要构建SRR样本列表，仅需要GEO号就能下载上游数据，当前最完美的GEO上游数据下载方案</a></p></section></li><li><section><p><a href="https://mp.weixin.qq.com/s?__biz=Mzg4Mzk3MDM2Ng==&amp;mid=2247483794&amp;idx=1&amp;sn=eb5560def17680a7bfa0b931bd82c20e&amp;scene=21#wechat_redirect" data-linktype="2">单细胞上游：六、cellranger整体流程（多泳道fastq文件一键改名方法）</a></p></section></li><li><section><p><a href="https://mp.weixin.qq.com/s?__biz=Mzg4Mzk3MDM2Ng==&amp;mid=2247483802&amp;idx=1&amp;sn=6fde37c95bf65cc6833a617803186e0d&amp;scene=21#wechat_redirect" data-linktype="2">单细胞上游：七、GEO单细胞数据一键上游</a></p></section></li><li><section><p><a href="https://mp.weixin.qq.com/s?__biz=Mzg4Mzk3MDM2Ng==&amp;mid=2247483836&amp;idx=1&amp;sn=db5995e56dca3943c1d5b1671428f0e7&amp;scene=21#wechat_redirect" data-linktype="2">单细胞上游：八、新增GSA开放数据的一键上游</a></p></section></li></ul><p data-tool="mdnice编辑器">围绕单细胞上游分析，作者写了有八个专题哦。作者还是一个python大佬，把所有的流程打包成了一个python包<code>easyBio</code>。<code>easybio</code>功能非常多，<strong>感兴趣的可以翻一翻作者写的推文</strong>。</p><p data-tool="mdnice编辑器">在这个包里，作者多个Line的解决方案源代码详见：<a href="https://mp.weixin.qq.com/s?__biz=Mzg4Mzk3MDM2Ng==&amp;mid=2247483794&amp;idx=1&amp;sn=eb5560def17680a7bfa0b931bd82c20e&amp;scene=21#wechat_redirect" data-linktype="2">单细胞上游：六、cellranger整体流程（多泳道fastq文件一键改名方法）</a></p><p data-tool="mdnice编辑器"><code>easyBio</code>安装也很方便：</p><pre data-tool="mdnice编辑器"><span></span><code>pip install easybio<br></code></pre><p data-tool="mdnice编辑器">然后针对拆解好的fastq文件进行重命名：</p><pre data-tool="mdnice编辑器"><span></span><code>easychangeSRAName -l  ./files.txt -f ./<br></code></pre><figure data-tool="mdnice编辑器"><img data-ratio="0.8510301109350238" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqVDTfJrw2XicOadMibMbgkYMHiatRKlNwChhztXMCfoFzeicNEZ0rfQZjfRu3ibUic0nnBWoMJicxabXRicGw/640?wx_fmt=other" data-type="other" data-w="631" src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqVDTfJrw2XicOadMibMbgkYMHiatRKlNwChhztXMCfoFzeicNEZ0rfQZjfRu3ibUic0nnBWoMJicxabXRicGw/640?wx_fmt=other"><figcaption>image-20230626140631939</figcaption></figure><pre data-tool="mdnice编辑器"><span></span><code>ls -lh<br></code></pre><figure data-tool="mdnice编辑器"><img data-ratio="1.439306358381503" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqVDTfJrw2XicOadMibMbgkYMHZlKZkb3ZLUnpheDwMC0wwkehSKBS940facdNdUNHEibbhic8fM2kS5kA/640?wx_fmt=other" data-type="other" data-w="346" src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqVDTfJrw2XicOadMibMbgkYMHZlKZkb3ZLUnpheDwMC0wwkehSKBS940facdNdUNHEibbhic8fM2kS5kA/640?wx_fmt=other"><figcaption>image-20230626140656716</figcaption></figure><p data-tool="mdnice编辑器"><code>easychangeSRAName</code>函数是基于python写的，源代码写的非常长的一段（如下）。。但是工具，好用就行。</p><p data-tool="mdnice编辑器">唯一吐槽一点重命名后的代码多了“SRR"，只要对作者的源代码进行非常简单的修改即可修复这个小问题：</p><pre data-tool="mdnice编辑器"><span></span><code><span>import</span> argparse<br><span>from</span> collections <span>import</span> defaultdict<br><span>import</span> os<br><span>import</span> re<br><br><br><span><span>def</span> <span>renames1</span><span>(folder_path)</span>:</span><br>    srr_counts = {}<br><br>    <span>for</span> file <span>in</span> os.listdir(folder_path):<br>        match = re.match(<span>r'(SRR\d+)_(\d)'</span>, file)<br>        <span>if</span> match:<br>            srr_id, num = match.groups()<br>            srr_counts[srr_id] = max(srr_counts.get(srr_id, <span>0</span>), int(num))<br><br>    <span>for</span> file <span>in</span> os.listdir(folder_path):<br>        match = re.match(<span>r'(SRR\d+)_(\d)'</span>, file)<br>        <span>if</span> match:<br>            srr_id, num = match.groups()<br>            <span>if</span> srr_counts[srr_id] == <span>2</span>:<br>                new_name = <span>f'<span>{srr_id}</span>_S1_L001_R<span>{num}</span>_001.fastq.gz'</span><br>            <span>elif</span> srr_counts[srr_id] == <span>3</span>:<br>                <span>if</span> num == <span>"1"</span>:<br>                    new_name = <span>f'<span>{srr_id}</span>_S1_L001_I1_001.fastq.gz'</span><br>                <span>else</span>:<br>                    new_name = <span>f'<span>{srr_id}</span>_S1_L001_R<span>{int(num)<span>-1</span>}</span>_001.fastq.gz'</span><br>            os.rename(os.path.join(folder_path, file),<br>                      os.path.join(folder_path, new_name))<br>            print(<span>f'Renamed <span>{file}</span> to <span>{new_name}</span>'</span>)<br><br><br><span><span>def</span> <span>read_mapping_file</span><span>(list_file)</span>:</span><br>    <span>with</span> open(list_file, <span>'r'</span>) <span>as</span> f:<br>        lines = f.readlines()<br>        mapping = {line.split()[<span>0</span>]: line.split()[<span>1</span>] <span>for</span> line <span>in</span> lines}<br>    <span>return</span> mapping<br><br><br><span><span>def</span> <span>count_srr_occurrences</span><span>(folder_path)</span>:</span><br>    files = os.listdir(folder_path)<br>    srr_counts = defaultdict(int)<br>    <span>for</span> file <span>in</span> files:<br>        srr_match = re.match(<span>r'(SRR\d+)_(\d)'</span>, file)<br>        <span>if</span> srr_match:<br>            srr = srr_match.group(<span>1</span>)<br>            srr_counts[srr] += <span>1</span><br>    <span>return</span> files, srr_counts<br><br><br><span><span>def</span> <span>rename_files</span><span>(files, folder_path, mapping, srr_counts)</span>:</span><br>    name_add_mapping = {}<br>    name_add_srr_mapping = {}<br>    <span>for</span> file <span>in</span> files:<br>        srr_match = re.match(<span>r'(SRR\d+)_(\d)'</span>, file)<br>        <span>if</span> srr_match:<br>            srr, number = srr_match.groups()<br>            name = mapping[srr]<br>            read_type = <span>''</span><br>            <span>if</span> srr_counts[srr] == <span>2</span>:<br>                read_type = <span>'R1'</span> <span>if</span> number == <span>'1'</span> <span>else</span> <span>'R2'</span><br>            <span>elif</span> srr_counts[srr] == <span>3</span>:<br>                read_type = <span>'I1'</span> <span>if</span> number == <span>'1'</span> <span>else</span> (<br>                    <span>'R1'</span> <span>if</span> number == <span>'2'</span> <span>else</span> <span>'R2'</span>)<br><br>            <span>if</span> srr <span>in</span> name_add_srr_mapping:<br>                lane_number = name_add_srr_mapping[srr]<br>            <span>else</span>:<br>                name_add_mapping[name] = name_add_mapping.get(name, <span>0</span>) + <span>1</span><br>                name_add_srr_mapping[srr] = name_add_mapping[name]<br>                lane_number = name_add_srr_mapping[srr]<br><br>            new_name = <span>f"<span>{name}</span>_S1_L00<span>{lane_number}</span>_<span>{read_type}</span>_001.fastq.gz"</span><br>            os.rename(os.path.join(folder_path, file),<br>                      os.path.join(folder_path, new_name))<br>            print(<span>f'Renamed <span>{file}</span> to <span>{new_name}</span>'</span>)<br><br><br><span><span>def</span> <span>renames2</span><span>(list_file, folder_path)</span>:</span><br>    mapping = read_mapping_file(list_file)<br>    files, srr_counts = count_srr_occurrences(folder_path)<br>    rename_files(files, folder_path, mapping, srr_counts)<br><br><br><span><span>def</span> <span>main</span><span>()</span>:</span><br>    parser = argparse.ArgumentParser(<br>        description=<span>"Process list_file and folder_path"</span>)<br>    parser.add_argument(<span>"-l"</span>, <span>"--list_file"</span>, help=<span>"matching list"</span>)<br>    parser.add_argument(<span>"-f"</span>, <span>"--folder_path"</span>, default=os.getcwd(),<br>                        help=<span>"Directory (default: current directory)"</span>)<br><br>    args = parser.parse_args()<br>        <br>    list_file = args.list_file<br>    folder_path = args.folder_path<br>    <br>    print(<span>"\033[1;32m list_file:\033[0m \033[32m{}\033[0m"</span>.format(list_file))<br>    print(<span>"\033[1;32m folder_path:\033[0m \033[32m{}\033[0m"</span>.format(folder_path))<br>    <br>    <span>if</span> list_file:<br>        renames2(list_file, folder_path)<br>    <span>else</span>:<br>        renames1(folder_path)<br>    print(<span>"\033[1;32m Rename completed\033[0m"</span>)<br><br><br><span>if</span> __name__ == <span>'__main__'</span>:<br>    main()<br></code></pre><span>- END -</span></section><p><br></p><p><mp-style-type data-value="3"></mp-style-type></p></div>

**Comment by qinshangyao** [comment]
Very helpful! Many thanks!

**Comment by 1061047021lql-AI** [comment]
您好，非常感谢您的讲解，如果要用cellranger运行一个样本，在您列举的这个例子里把一个样本的12个文件放在一个文件夹下就可以了把？

**Comment by 1061047021lql-AI** [comment]
您好，非常感谢您的讲解，如果要用cellranger运行一个样本，在您列举的这个例子里把一个样本的12个fastq文件放在一个文件夹下就可以了把？另外您的命名对同一个样本来说变化的是S，分别是S1,S2,S3,S4; 如果对同一个样本S不变，比如都是S1，变化的是L可不可以呢？即L001,L002,L003,L004,非常感谢您的回复

**Comment by 1061047021lql-AI** [comment]
您好，非常感谢您的讲解，如果要用cellranger运行一个样本，在您列举的这个例子里把一个样本的12个fastq文件放在一个文件夹下就可以了把？另外您的命名对同一个样本来说变化的是S，分别是S1,S2,S3,S4; 如果对同一个样本S不变，比如都是S1，变化的是L可不可以呢？即L001,L002,L003,L004,具体如下,非常感谢您的回复

**Comment by 1061047021lql-AI** [comment]
您好，非常感谢您的讲解，如果要用cellranger运行一个样本，在您列举的这个例子里把一个样本的12个fastq文件放在一个文件夹下就可以了把？另外您的命名对同一个样本来说变化的是S，分别是S1,S2,S3,S4; 如果对同一个样本S不变，比如都是S1，变化的是L可不可以呢？即L001,L002,L003,L004,具体如下：

sample1_S1_L001_I1_001.fastq.gz
sample1_S1_L001_R1_001.fastq.gz
sample1_S1_L001_R2_001.fastq.gz
sample1_S1_L002_I1_001.fastq.gz
sample1_S1_L002_R1_001.fastq.gz
sample1_S1_L002_R2_001.fastq.gz
sample1_S1_L003_I1_001.fastq.gz
sample1_S1_L003_R1_001.fastq.gz
sample1_S1_L003_R2_001.fastq.gz
sample1_S1_L004_I1_001.fastq.gz
sample1_S1_L004_R1_001.fastq.gz
sample1_S1_L004_R2_001.fastq.gz

**Comment by 1061047021lql-AI** [comment]
您好，非常感谢您的讲解，如果要用cellranger运行一个样本，在您列举的这个例子里把一个样本的12个fastq文件放在一个文件夹下就可以了把？另外您的命名对同一个样本来说变化的是S，分别是S1,S2,S3,S4; 如果对同一个样本S不变，比如都是S1，变化的是L可不可以呢？即L001,L002,L003,L004,具体如下：

sample1_S1_L001_I1_001.fastq.gz
sample1_S1_L001_R1_001.fastq.gz
sample1_S1_L001_R2_001.fastq.gz
sample1_S1_L002_I1_001.fastq.gz
sample1_S1_L002_R1_001.fastq.gz
sample1_S1_L002_R2_001.fastq.gz
sample1_S1_L003_I1_001.fastq.gz
sample1_S1_L003_R1_001.fastq.gz
sample1_S1_L003_R2_001.fastq.gz
sample1_S1_L004_I1_001.fastq.gz
sample1_S1_L004_R1_001.fastq.gz
sample1_S1_L004_R2_001.fastq.gz                                                                                                                                                                   请问这样是否可以呢？两个问题谢谢您的回复！
