### ISSUE TITLE
GEO数据库读取官方RNA-seq count矩阵及预处理

### ISSUE THREAD

**Issue by ixxmu** [ixxmu/mp_duty#3702]
https://mp.weixin.qq.com/s/CIKsm-1L7vk1hGpa1lDBZw

**Comment by ixxmu** [comment]
GEO数据库读取官方RNA-seq count矩阵及预处理 by 生命数据科学
------
<div><section><mp-common-profile data-pluginname="mpprofile" data-id="Mzk0MDI4MjM4NQ==" data-headimg="http://mmbiz.qpic.cn/mmbiz_png/Nf8QqUlJukMmaCXNABdtSPicSfZU9GMyI6PHia3Gqfy5DNMias3VicXY8Gh70vu1gibxsObqoGRRHYtJLKX6WbyeeNw/0?wx_fmt=png" data-nickname="生命数据科学" data-alias="Data_Research" data-signature="科研是天马行空的想象和脚踏实地的认真！" data-from="0" data-is_biz_ban="0"></mp-common-profile></section><section data-tool="markdown编辑器" data-website="https://markdown.com.cn/editor"><h2 data-tool="markdown.com.cn编辑器"><span></span><span>使用说明</span><span></span></h2><ol data-tool="markdown.com.cn编辑器"><li><section><p><strong>库引入</strong></p></section></li></ol><ul><li><section>导入所需的R包：<code>dplyr</code>、<code>AnnotationDbi</code>、<code>org.Hs.eg.db</code> 和 <code>data.table</code>。</section></li></ul><li><section><p><strong>自定义GSE号输入</strong></p></section></li><ul><li><section>当运行脚本时，它会提示您输入一个GSE号。</section></li></ul><li><section><p><strong>数据下载</strong></p></section></li><ul><li><section>根据您提供的GSE号，脚本会构造一个URL以从NCBI GEO下载相应的原始计数数据。</section></li><li><section>下载的文件名是基于输入的GSE号。</section></li></ul><li><section><p><strong>数据读取与处理</strong></p></section></li><ul><li><section>使用<code>data.table::fread</code>函数读取下载的gzip压缩文件。</section></li><li><section>将数据转换为矩阵，并将其行名设置为Entrez ID。</section></li></ul><li><section><p><strong>标识转换</strong></p></section></li><ul><li><section>利用<code>mapIds</code>函数将Entrez ID转换为Gene Symbols。</section></li><li><section>删除存在NA的行。</section></li></ul><li><section><p><strong>生成结果</strong></p></section></li><ul><li><section>脚本最后会生成一个名为<code>gene_counts</code>的数据框，其中包含基因名称（Gene Symbols）及其对应的计数数据。</section></li></ul><h2 data-tool="markdown.com.cn编辑器"><span></span><span>代码</span></h2><section><ul><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li></ul><pre data-lang=""><code><span>library("dplyr")</span></code><code><span>library("AnnotationDbi")</span></code><code><span>library("org.Hs.eg.db")</span></code><code><span>library("data.table")</span></code><code><span><br></span></code><code><span># 1. 自定义输入GSE号</span></code><code><span>GSE_number &lt;- "GSE60052"</span></code><code><span><br></span></code><code><span># 2. 分析得到对应的gene_counts</span></code><code><span>urld &lt;- "https://www.ncbi.nlm.nih.gov/geo/download/?format=file&amp;type=rnaseq_counts"</span></code><code><span>path &lt;- paste(urld, paste("acc=", GSE_number, sep=""), paste("file=", GSE_number, "_raw_counts_GRCh38.p13_NCBI.tsv.gz", sep=""), sep="&amp;")</span></code><code><span>download.file(path, destfile = paste(GSE_number, "_raw_counts_GRCh38.p13_NCBI.tsv.gz", sep=""))</span></code><code><span><br></span></code><code><span>raw_counts &lt;- as.matrix(data.table::fread(paste(GSE_number, "_raw_counts_GRCh38.p13_NCBI.tsv.gz", sep=""), header=T, colClasses="integer"), rownames=1)</span></code><code><span>rownames(raw_counts) &lt;- mapIds(org.Hs.eg.db, keys = rownames(raw_counts), column = "SYMBOL", keytype = "ENTREZID", multiVals = "first")</span></code><code><span><br></span></code><code><span>raw_counts &lt;- raw_counts %&gt;%</span></code><code><span>  .[!is.na(rownames(.)), ] %&gt;%</span></code><code><span>  as.data.frame()</span></code><code><span><br></span></code><code><span>gene_counts &lt;- cbind(genes = rownames(raw_counts), raw_counts)</span></code><code><span><br></span></code><code><span>## 效果展示</span></code><code><span>&gt; gene_counts[1:5,1:5]</span></code><code><span>                  genes GSM1464282 GSM1464283 GSM1464284 GSM1464285</span></code><code><span>DDX11L1         DDX11L1          0          9          2          2</span></code><code><span>WASH7P           WASH7P        102        105        110         81</span></code><code><span>MIR6859.1     MIR6859.1          2          1          8          1</span></code><code><span>MIR1302.2HG MIR1302.2HG          0          4          0          5</span></code><code><span>MIR1302.2     MIR1302.2          0          0          1          3</span></code><code><span><br></span></code></pre></section></section><p><br></p><p><mp-style-type data-value="3"></mp-style-type></p></div>

**Comment by ixxmu** [comment]
难道要把我的流程改成用counts？ 虽然有的GEO确实没有上传counts

**Comment by Supremelu** [comment]
这个方法获得的counts与SRA数据获得counts有区别吗？大佬

**Comment by ixxmu** [comment]
> 这个方法获得的counts与SRA数据获得counts有区别吗？大佬

不会有很大区别，除非他没有提供counts，一般直接用他geo提供的即可

**Comment by Supremelu** [comment]
非常感谢！！

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年1月23日 22:02 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [ixxmu/mp_duty] GEO数据库读取官方RNA-seq count矩阵及预处理 (Issue #3702) |

这个方法获得的counts与SRA数据获得counts有区别吗？大佬

不会有很大区别，除非他没有提供counts，一般直接用他geo提供的即可
