### ISSUE TITLE
使用raster包在WorldClim数据库中获取全球气候和生物气候数据

### ISSUE THREAD

**Issue by ixxmu** [ixxmu/mp_duty#3817]
https://mp.weixin.qq.com/s/Z_wkBoK0hGjo426YkWFIZA

**Comment by ixxmu** [comment]
使用raster包在WorldClim数据库中获取全球气候和生物气候数据 by 小白鱼的生统笔记
------
<div><section data-support="96编辑器" data-style-id="24668" data-mpa-powered-by="yiban.io"><section data-support="96编辑器" data-style-id="24668"><section><section><section><section data-width="100%"><img data-ratio="0.2436548223350254" data-src="https://mmbiz.qpic.cn/mmbiz_gif/Ljib4So7yuWjjvcS70NecHLcxagEodW97PKvzwQ629F5QiayZpnkGL4fcsVzbxXQkSw1hP8sVhGWTa26J1Eul5eQ/640?wx_fmt=gif" data-type="gif" data-w="197" data-width="100%" src="https://mmbiz.qpic.cn/mmbiz_gif/Ljib4So7yuWjjvcS70NecHLcxagEodW97PKvzwQ629F5QiayZpnkGL4fcsVzbxXQkSw1hP8sVhGWTa26J1Eul5eQ/640?wx_fmt=gif"></section></section><section><strong><span>使用raster包在WorldClim数据库中获取全球气候和生物气候数据</span></strong></section><section><section><section><img data-ratio="1" data-src="https://mmbiz.qpic.cn/mmbiz_gif/Ljib4So7yuWjjvcS70NecHLcxagEodW97KjMiaXXfqKyB0p1TNAPeGTXG7ibeibar7arBd0OdhYttgW1OI9XR0C16A/640?wx_fmt=gif" data-type="gif" data-w="50" data-width="100%" src="https://mmbiz.qpic.cn/mmbiz_gif/Ljib4So7yuWjjvcS70NecHLcxagEodW97KjMiaXXfqKyB0p1TNAPeGTXG7ibeibar7arBd0OdhYttgW1OI9XR0C16A/640?wx_fmt=gif"><span></span></section></section></section></section></section></section></section><section><span>WorldClim<span>（</span><span>https://www.worldclim.org/</span></span><span>）是一个高空间分辨率的全球天气和气候数据的数据库。</span></section><section><span>WorldClim</span><span>中汇编了全球最低、平均和最高温度（</span><span>°C</span><span>）、降水（</span><span>mm</span><span>）、太阳辐射（</span><span>kJ m</span><sup>-2</sup><span> day</span><sup>-1</sup><span>）、风速（</span><span>m s</span><sup>-1</sup><span>）、水蒸气压（</span><span>kPa</span><span>）的历史数据，以及</span><span>19</span><span>种“生物气候”变量。除了可从中获取历史数据外，</span><span>WorldClim</span><span>还包含</span><span>CMIP6</span><span>对未来气候的预测。</span></section><p><span> </span><span> </span></p><section data-support="96编辑器" data-style-id="1964"><section><section><p><span>手动获取WorldClim的气候数据</span></p></section></section></section><p><span></span></p><p><span><span>进入</span>WorldClim<span>的数据下载页面（</span></span><span>https://www.worldclim.org/data/index.html</span><span><span>），在右侧可点击选择历史</span>/<span>未来数据查看，并从中下载感兴趣的数据集。</span></span></p><section><span><img data-ratio="0.4888888888888889" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/Canb3IJn7EAxrvTFYu7AN8THcDGJDIwRCO5eLd3SQ7SIelTICNFnrqj1zhbPh1FahfcyqoPc267Hiao2piajTPcw/640?wx_fmt=png" data-type="png" data-w="1080" title="" src="https://mmbiz.qpic.cn/sz_mmbiz_png/Canb3IJn7EAxrvTFYu7AN8THcDGJDIwRCO5eLd3SQ7SIelTICNFnrqj1zhbPh1FahfcyqoPc267Hiao2piajTPcw/640?wx_fmt=png"> </span></section><p><span>原始数据集比较大，默认是全球的气候数据，下载后还需进一步根据自己感兴趣的区域范围（经纬度）进行提取和匹配，不再多说。</span></p><p><img data-ratio="0.5148148148148148" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/Canb3IJn7EAxrvTFYu7AN8THcDGJDIwRjibyQhI8z41YeODqA0jA9MKBKic5SV0oMDOwrkZZe6Fe3TlxicDsg35KA/640?wx_fmt=png" data-type="png" data-w="1080" title="" src="https://mmbiz.qpic.cn/sz_mmbiz_png/Canb3IJn7EAxrvTFYu7AN8THcDGJDIwRjibyQhI8z41YeODqA0jA9MKBKic5SV0oMDOwrkZZe6Fe3TlxicDsg35KA/640?wx_fmt=png"><br></p><p><img data-ratio="0.5092592592592593" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/Canb3IJn7EAxrvTFYu7AN8THcDGJDIwRrvYaAiaTgHLibgKxSynaZcDFV56hu2B5VNgQP8KqNChXcfw9u2q0ibaqg/640?wx_fmt=png" data-type="png" data-w="1080" title="" src="https://mmbiz.qpic.cn/sz_mmbiz_png/Canb3IJn7EAxrvTFYu7AN8THcDGJDIwRrvYaAiaTgHLibgKxSynaZcDFV56hu2B5VNgQP8KqNChXcfw9u2q0ibaqg/640?wx_fmt=png"><br></p><section><img data-ratio="0.43703703703703706" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/Canb3IJn7EAxrvTFYu7AN8THcDGJDIwRo9XA2RensXo8v9QwvpOl6oAmicYicDOyuC2aNw1KcGOc4Gl2wAFC4CVw/640?wx_fmt=png" data-type="png" data-w="1080" title="" src="https://mmbiz.qpic.cn/sz_mmbiz_png/Canb3IJn7EAxrvTFYu7AN8THcDGJDIwRo9XA2RensXo8v9QwvpOl6oAmicYicDOyuC2aNw1KcGOc4Gl2wAFC4CVw/640?wx_fmt=png"><span> </span><span></span></section><p><mpcpc js_editor_cpcad="" src="/cgi-bin/readtemplate?t=tmpl/cpc_tmpl#1693379265093" data-category_id_list="1|5|7|8|16|17|29|31|36|37|42|43|46|47|48|50|51|55|59|62|60" data-id="1693379265093"></mpcpc><span></span></p><section data-support="96编辑器" data-style-id="1964"><section><section><p><span>使用R包raster获取WorldClim的气候数据</span></p></section></section></section><p><br></p><section><span>R<span>语言</span>raster<span>包提供了获取和匹配</span>WorldClim<span>气候数据的便捷方法，如下主要以该方法为例做个简单演示。</span></span></section><p><span> </span></p><section data-support="96编辑器" data-style-id="22451"><section><section><section><p><span>站点的经纬度表</span></p></section><section><br></section></section></section></section><p><span>准备一个记录站点经纬度坐标的文件，如下所示的“</span><span>site.txt</span><span>”，第一列经度第二列纬度。</span></p><p><img data-ratio="1.4018264840182648" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/Canb3IJn7EAxrvTFYu7AN8THcDGJDIwRYPPeiajFtib6iaTnGThb0UANcdDnG0efPzvJPBlJT1ts9XRlialrBaAXpQ/640?wx_fmt=png" data-type="png" data-w="219" title="" src="https://mmbiz.qpic.cn/sz_mmbiz_png/Canb3IJn7EAxrvTFYu7AN8THcDGJDIwRYPPeiajFtib6iaTnGThb0UANcdDnG0efPzvJPBlJT1ts9XRlialrBaAXpQ/640?wx_fmt=png"><br></p><p><span> </span><span> </span></p><section data-support="96编辑器" data-style-id="22451"><section><section><section><p><span>获取温度或降水的月平均数据</span></p></section><section><br></section></section></section></section><p><span>加载</span><span>raster</span><span>包，使用函数</span><span>getData()</span><span>即可在</span><span>WorldClim</span><span>中获取气候数据（默认获取全球的），然后再使用函数</span><span>extract()</span><span>根据提供的经纬度坐标从中提取匹配各站点的气候数据。</span></p><pre>library(raster)<br> <br>#读取各站点的经纬度数据<br>site &lt;- read.delim('site.txt', sep = '\t')<br> <br>#getData() 中指定 'worldclim' 以用于在 WorldClim 数据库中获取气候数据<br>#参数 var 可选 tmin（月平均最低温度）、tmax（月平均最高温度）、prec（月平均降水）、bio（生物气候）<br>#参数 res 用于指定分辨率，可选 0.5、2.5、5、10 (minutes of a degree)<br>#其他详情 ?getData<br> <br>#如下以匹配月平均降水数据为例，并根据提供的经纬度提取个站点的数据后输出<br>worldprec &lt;- getData('worldclim', var = 'prec', res = 2.5)<br>prec &lt;- extract(worldprec, site)<br>prec &lt;- cbind(site, prec)<br>write.table(prec, 'prec.txt', sep = '\t', row.names = FALSE, quote = FALSE)<br></pre><p><img data-ratio="0.48055555555555557" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/Canb3IJn7EAxrvTFYu7AN8THcDGJDIwRla5r9q8uO0pg2qmgurt8ntONBjVIiaIH2gslwdeiaHJxjJvnHHm7kwzw/640?wx_fmt=png" data-type="png" data-w="1080" title="" src="https://mmbiz.qpic.cn/sz_mmbiz_png/Canb3IJn7EAxrvTFYu7AN8THcDGJDIwRla5r9q8uO0pg2qmgurt8ntONBjVIiaIH2gslwdeiaHJxjJvnHHm7kwzw/640?wx_fmt=png"><br></p><p><span>对于温度数据的获取，操作及数据格式都是类似的，不再多说了。</span></p><p><span> </span></p><section data-support="96编辑器" data-style-id="22451"><section><section><section><p><span>获取“生物气候”变量</span></p></section><section><br></section></section></section></section><p><span>WorldClim</span><span>的生物气候变量是由每月温度和降水衍生出的更具生物学意义的变量，包括年度趋势（例如，年平均温度、年降水量）、季节性（例如，温度和降水量的年范围）以及极端或限制性环境因素（例如，最冷和最热月份的温度，以及旱季的降水），通常用于物种分布建模和相关生态建模技术。</span></p><pre>#如下以匹配 WorldClim 的 19 种生物气候数据为例，并根据提供的经纬度提取个站点的数据后输出<br>worldbio &lt;- getData('worldclim', var = 'bio', res = 2.5)<br>bio &lt;- extract(worldbio, site)<br>bio &lt;- cbind(site, bio)<br>write.table(bio, 'bio.txt', sep = '\t', row.names = FALSE, quote = FALSE)<br></pre><p><img data-ratio="0.5787037037037037" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/Canb3IJn7EAxrvTFYu7AN8THcDGJDIwRl6g5epj8kc3QNDyMLXiaqlPIphV8zicUWgYjDpw0uGc5yyn3rueAlBAw/640?wx_fmt=png" data-type="png" data-w="1080" title="" src="https://mmbiz.qpic.cn/sz_mmbiz_png/Canb3IJn7EAxrvTFYu7AN8THcDGJDIwRl6g5epj8kc3QNDyMLXiaqlPIphV8zicUWgYjDpw0uGc5yyn3rueAlBAw/640?wx_fmt=png"><br></p><p><span><span>关于</span>WorldClim<span>的</span>19<span>种生物气候变量可参阅：</span></span><span>https://www.worldclim.org/data/bioclim.html</span><span></span></p><p><span>bio1<span>，</span>Annual Mean Temperature<span>，年平均气温（</span>℃<span>）；</span></span></p><p><span>bio2<span>，</span>Mean Diurnal Range (Mean of monthly (max temp - min temp)) <span>，平均日温差（</span>℃<span>）；</span></span></p><p><span>bio3<span>，</span>Isothermality (bio2/ bio 7) (×100)<span>，等温性；</span></span></p><p><span>bio4<span>，</span>Temperature Seasonality (standard  deviation ×100)<span>，气温季节性变动系数；</span></span></p><p><span>bio5<span>，</span>Max Temperature of Warmest Month<span>，最热月份最高温度（</span>℃<span>）；</span></span></p><p><span>bio6<span>，</span>Min Temperature of Coldest Month<span>，最冷月份最低温度（</span>℃<span>）；</span></span></p><p><span>bio7<span>，</span>Temperature Annual Range (BIO5-BIO6)<span>，气温年较差（</span>℃<span>）；</span></span></p><p><span>bio8<span>，</span>Mean Temperature of Wettest Quarter<span>，最湿季度平均温度（</span>℃<span>）；</span></span></p><p><span>bio9<span>，</span>Mean Temperature of Driest Quarter<span>，最干季度平均温度（</span>℃<span>）；</span></span></p><p><span>bio10<span>，</span>Mean Temperature of Warmest Quarter<span>，最暖季度平均温度（</span>℃<span>）；</span></span></p><p><span>bio11<span>，</span>Mean Temperature of Coldest Quarter<span>，最冷季度平均温度（</span>℃<span>）；</span></span></p><p><span>bio12<span>，</span>Annual Precipitation<span>，年降水量（</span>mm<span>）；</span></span></p><p><span>bio13<span>，</span>Precipitation of Wettest Month<span>，最湿月份降水量（</span>mm<span>）；</span></span></p><p><span>bio14<span>，</span>Precipitation of Driest Month<span>，最干月份降水量（</span>mm<span>）；</span></span></p><p><span>bio15<span>，</span>Precipitation Seasonality (Coefficient of Variation)<span>，降水量季节性变化（</span>mm<span>）；</span></span></p><p><span>bio16<span>，</span>Precipitation of Wettest Quarter<span>，最干季度降水量（</span>mm<span>）；</span></span></p><p><span>bio17<span>，</span>Precipitation of Driest Quarter<span>，最湿季度降水量（</span>mm<span>）；</span></span></p><p><span>bio18<span>，</span>Precipitation of Warmest Quarter<span>，最暖季度降水量（</span>mm<span>）；</span></span></p><p><span>bio19<span>，</span>Precipitation of Coldest Quarter<span>，最冷季度降水量（</span>mm<span>）。</span></span></p><p><span> </span><span> </span></p><section><section><section data-support="96编辑器" data-style-id="24668"><section><section><section><section data-width="100%"><img data-ratio="0.2436548223350254" data-src="https://mmbiz.qpic.cn/mmbiz_gif/Ljib4So7yuWjjvcS70NecHLcxagEodW97PKvzwQ629F5QiayZpnkGL4fcsVzbxXQkSw1hP8sVhGWTa26J1Eul5eQ/640?wx_fmt=gif&amp;wxfrom=5&amp;wx_lazy=1" data-type="gif" data-w="197" data-width="100%" src="https://mmbiz.qpic.cn/mmbiz_gif/Ljib4So7yuWjjvcS70NecHLcxagEodW97PKvzwQ629F5QiayZpnkGL4fcsVzbxXQkSw1hP8sVhGWTa26J1Eul5eQ/640?wx_fmt=gif&amp;wxfrom=5&amp;wx_lazy=1"></section></section><section><section><strong><span>友情链接</span></strong></section></section><section><section><section><img data-ratio="1" data-src="https://mmbiz.qpic.cn/mmbiz_gif/Ljib4So7yuWjjvcS70NecHLcxagEodW97KjMiaXXfqKyB0p1TNAPeGTXG7ibeibar7arBd0OdhYttgW1OI9XR0C16A/640?wx_fmt=gif&amp;wxfrom=5&amp;wx_lazy=1" data-type="gif" data-w="50" data-width="100%" src="https://mmbiz.qpic.cn/mmbiz_gif/Ljib4So7yuWjjvcS70NecHLcxagEodW97KjMiaXXfqKyB0p1TNAPeGTXG7ibeibar7arBd0OdhYttgW1OI9XR0C16A/640?wx_fmt=gif&amp;wxfrom=5&amp;wx_lazy=1"></section></section></section></section></section></section></section></section><p><a target="_blank" href="http://mp.weixin.qq.com/s?__biz=MzIxNzc1Mzk3NQ==&amp;mid=2247490548&amp;idx=3&amp;sn=7c7be1b3d1b512886386f2a865f85b7e&amp;chksm=97f5abeca08222fa9116d5d4dafa50506e6080a185e9147fda9202f148ac7874035ea9497b15&amp;scene=21#wechat_redirect" textvalue="‍经纬度坐标换算地理距离‍" linktype="text" imgurl="" imgdata="null" data-itemshowtype="0" tab="innerlink" data-linktype="2"><span><strong><span></span></strong></span></a></p><p><a target="_blank" href="http://mp.weixin.qq.com/s?__biz=MzIxNzc1Mzk3NQ==&amp;mid=2247490548&amp;idx=3&amp;sn=7c7be1b3d1b512886386f2a865f85b7e&amp;chksm=97f5abeca08222fa9116d5d4dafa50506e6080a185e9147fda9202f148ac7874035ea9497b15&amp;scene=21#wechat_redirect" textvalue="‍经纬度坐标换算地理距离‍" linktype="text" imgurl="" imgdata="null" data-itemshowtype="0" tab="innerlink" data-linktype="2" hasload="1"><span><strong><span>经纬度坐标换算地理距离</span></strong></span></a></p><p><span><strong><a target="_blank" href="http://mp.weixin.qq.com/s?__biz=MzIxNzc1Mzk3NQ==&amp;mid=2247505720&amp;idx=7&amp;sn=ea67aa26226b2f92ed7aecd512bc50c1&amp;chksm=97f66720a081ee36a845eb44b5d94a0eb8897d89001f5cf3bfc240f27318f16b4e63281b832a&amp;scene=21#wechat_redirect" textvalue="使用windy网站查看气象数据" linktype="text" imgurl="" imgdata="null" data-itemshowtype="0" tab="innerlink" data-linktype="2" hasload="1">使用windy网站查看气象数据</a></strong></span></p><p><span><a target="_blank" href="http://mp.weixin.qq.com/s?__biz=MzIxNzc1Mzk3NQ==&amp;mid=2247495674&amp;idx=1&amp;sn=ce4940c50a3006c5fcbfbcd69bcc9330&amp;chksm=97f65fe2a081d6f4f8ecf101a78d51b53f35502ff85505c7f5c954c3440489ab848a8c4fa883&amp;scene=21#wechat_redirect" textvalue="‍海洋遥感数据（SST、Chla、PAR、NPP）‍" linktype="text" imgurl="" imgdata="null" data-itemshowtype="0" tab="innerlink" data-linktype="2" hasload="1"><strong><span><strong><strong><span><strong><span>海洋遥感数据（SST、Chla、PAR、NPP）</span></strong></span></strong></strong></span></strong></a></span></p><p><strong><span><a target="_blank" href="http://mp.weixin.qq.com/s?__biz=MzIxNzc1Mzk3NQ==&amp;mid=2247497201&amp;idx=1&amp;sn=44e225c760ca985033b62ec13ba15bea&amp;chksm=97f645e9a081ccff1d4ae1d0dc1107c7b033eee92635aeef1896b83857a95ccdf1dc0bf68847&amp;scene=21#wechat_redirect" textvalue="预测海洋碳酸盐和营养盐含量（CANYON-B）" linktype="text" imgurl="" imgdata="null" data-itemshowtype="0" tab="innerlink" data-linktype="2" hasload="1">预测海洋碳酸盐和营养盐含量（CANYON-B）</a></span></strong></p><p><a target="_blank" href="http://mp.weixin.qq.com/s?__biz=MzIxNzc1Mzk3NQ==&amp;mid=2247505721&amp;idx=1&amp;sn=4c059decc0a322f834009ffb1c0b00a7&amp;chksm=97f66721a081ee37cbe04f39b4aa310efa86a1c295e450152c22af52132c6fecce3d9044f093&amp;scene=21#wechat_redirect" textvalue="CDOM和FDOM光谱分析" linktype="text" imgurl="" imgdata="null" data-itemshowtype="0" tab="innerlink" data-linktype="2" hasload="1"><strong><span><span>CDOM和FDOM的光谱分析</span></span></strong></a></p><p><a target="_blank" href="http://mp.weixin.qq.com/s?__biz=MzIxNzc1Mzk3NQ==&amp;mid=2247497292&amp;idx=1&amp;sn=27735d868caa51c3418b9d46d1032661&amp;chksm=97f64654a081cf42c1d66be782077ba05993bb7274297bd69518fbfd28c4a8328a21bc599778&amp;scene=21#wechat_redirect" textvalue="ef-ratio的经验公式" linktype="text" imgurl="" imgdata="null" data-itemshowtype="0" tab="innerlink" data-linktype="2" hasload="1"><strong><span>ef-ratio的经验公式</span></strong></a></p><p><strong><span><a target="_blank" href="http://mp.weixin.qq.com/s?__biz=MzIxNzc1Mzk3NQ==&amp;mid=2247497292&amp;idx=2&amp;sn=2126e5681ddd95f1ffe4d16d546a8403&amp;chksm=97f64654a081cf426374dc0510af83ea3bdc6d7f17c7479cc1dd74a0efbf4ab2f135831e1e92&amp;scene=21#wechat_redirect" textvalue="BA、BP、BR、BGE的经验公式" linktype="text" imgurl="" imgdata="null" data-itemshowtype="0" tab="innerlink" data-linktype="2" hasload="1">BA、BP、BR、BGE的经验公式</a></span></strong></p><section><section><img data-ratio="0.08571428571428572" data-src="https://mmbiz.qpic.cn/mmbiz_gif/Ljib4So7yuWiaibnZHYib0rg4wZibRnXvibHQYZZXc5ic2yGZF8dUpficcfTNOUNMjSG8v9CUibQs5GngxGicVBuKtvqoLHg/640?wx_fmt=gif" data-type="gif" data-w="630" src="https://mmbiz.qpic.cn/mmbiz_gif/Ljib4So7yuWiaibnZHYib0rg4wZibRnXvibHQYZZXc5ic2yGZF8dUpficcfTNOUNMjSG8v9CUibQs5GngxGicVBuKtvqoLHg/640?wx_fmt=gif"><span></span></section></section><section><mp-common-profile data-id="MzIxNzc1Mzk3NQ==" data-pluginname="mpprofile" data-headimg="http://mmbiz.qpic.cn/mmbiz_png/Canb3IJn7ED56PWk3ug7tEjUmvZGlbAEULIx7cicgvKSILx5p3dnYvs0wC2PkpoH07lAa0AbCqmUr2P5kic3tI1g/0?wx_fmt=png" data-nickname="小白鱼的生统笔记" data-alias="" data-signature="基因组/微生物组/生态统计/R语言......学习与经验分享 好吧其实我一直是看心情瞎写的" data-from="1" data-is_biz_ban="0" data-weui-theme="light"></mp-common-profile></section><p><mp-style-type data-value="3"></mp-style-type></p></div>

**Comment by zhchbi** [comment]
我想问，这个方法获取的气候信息是哪一年的？如果不同坐标想获取的气温是不同年份的呢？该怎么操作？
