### ISSUE TITLE
听说你只有富集表格还想画 GSEA 图?

### ISSUE THREAD

**Issue by ixxmu** [ixxmu/mp_duty#4272]
https://mp.weixin.qq.com/s/FIMutR3n1QjXdf0Yy3svGg

**Comment by ixxmu** [comment]
听说你只有富集表格还想画 GSEA 图? by 老俊俊的生信笔记
------
<div><section data-tool="mdnice编辑器" data-website="https://www.mdnice.com" data-mpa-powered-by="yiban.io"><h4 data-tool="mdnice编辑器"><span></span></h4><section><mp-common-profile data-pluginname="mpprofile" data-id="MzkyMTI1MTYxNA==" data-headimg="http://mmbiz.qpic.cn/mmbiz_png/G5jjcE4usey42oX5qyLTVibLRO9dz8ic5G4TpEHQc9rICYlpS4MHg6Et8cgXrQDqibvibXombicTro8t9cekJRlDBcw/0?wx_fmt=png" data-nickname="老俊俊的生信笔记" data-alias="JunJunLab" data-signature="老俊俊的生信技能和知识分享,我不是巨人,但你可以站在我的肩膀上更进一步!" data-from="0" data-is_biz_ban="0"></mp-common-profile></section><h4 data-tool="mdnice编辑器"><span></span></h4><h2 data-tool="mdnice编辑器"><span><span>1</span></span><span>引言</span><span></span></h2><blockquote data-tool="mdnice编辑器"><p>首先感谢使用小伙伴的支持和点赞!</p></blockquote><figure data-tool="mdnice编辑器"><img data-imgfileid="100028970" data-ratio="0.2770034843205575" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYGpXjichdBO6JgwHPjEPibQz8xgwIuCIKtCIcRb2Ky2Qnhjto5ibnBcuHA/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="574" src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYGpXjichdBO6JgwHPjEPibQz8xgwIuCIKtCIcRb2Ky2Qnhjto5ibnBcuHA/640?wx_fmt=png&amp;from=appmsg"></figure><blockquote data-tool="mdnice编辑器"><p>我们知道绘制图形是需要对应存储数据的对象的, <strong>clusterProfiler</strong> 的 <strong>gseGO/gseKEGG</strong> 返回一个 <strong>gseaResult</strong> 对象,你可以使用 <strong>gseaplot/gseaplot2</strong> 来绘制图形。<strong>有时候你可能输出完富集的表格后,并没有保存这个对象,然后过段时间回头来又想绘图,但是只有表格却画不了,于是你又重新跑了一次富集分析,但发现和上次富集的结果又不一样了!</strong> 难搞。</p></blockquote><blockquote data-tool="mdnice编辑器"><p>我一般是一起保存富集的 <strong>gseaResult</strong> 对象和富集的表格,这样下次就可以继续绘图了,保证两次结果一致。要是能把富集表格再次转化为 <strong>gseaResult</strong> 岂不是很不错。今天群友分享了一个相关的代码,不过不好用,我们可以根据自己的需求,自己手撸一个这样的代码来做个转换。</p></blockquote><h2 data-tool="mdnice编辑器"><span><span>2</span></span><span>安装</span><span></span></h2><pre data-tool="mdnice编辑器"><span></span><code><span># install.packages("devtools")</span><br>devtools::install_github(<span>"junjunlab/GseaVis"</span>)<br></code></pre><h2 data-tool="mdnice编辑器"><span><span>3</span></span><span>测试</span><span></span></h2><p data-tool="mdnice编辑器">我们先做个简单富集分析:</p><pre data-tool="mdnice编辑器"><span></span><code><span>library</span>(clusterProfiler)<br><span>library</span>(org.Hs.eg.db)<br><span>library</span>(enrichplot)<br><span>library</span>(GseaVis)<br><br><span># load test data</span><br>data(geneList, package=<span>"DOSE"</span>)<br><br><span># check</span><br>head(geneList)<br><span># 4312     8318    10874    55143    55388      991</span><br><span># 4.572613 4.514594 4.418218 4.144075 3.876258 3.677857</span><br><br><span># KEGG enrich</span><br>kk &lt;- gseKEGG(geneList     = geneList,<br>              organism     = <span>'hsa'</span>,<br>              minGSSize    = <span>120</span>,<br>              pvalueCutoff = <span>0.05</span>,<br>              verbose      = <span>FALSE</span>)<br><br>go &lt;- gseGO(geneList = geneList,<br>            ont = <span>"BP"</span>,<br>            keyType = <span>"ENTREZID"</span>,<br>            OrgDb = org.Hs.eg.db,<br>            pvalueCutoff = <span>0.05</span>)<br><br>KK_df &lt;- data.frame(kk)<br><br><span># check</span><br>head(KK_df[<span>1</span>:<span>3</span>,<span>1</span>:<span>5</span>])<br><span>#                ID                             Description setSize enrichmentScore      NES</span><br><span># hsa04110 hsa04110                              Cell cycle     139       0.6637551 2.827249</span><br><span># hsa05169 hsa05169            Epstein-Barr virus infection     193       0.4335010 1.927343</span><br><span># hsa05166 hsa05166 Human T-cell leukemia virus 1 infection     202       0.3893613 1.748318</span><br><br>go_df &lt;- data.frame(go)<br><br><span># check</span><br>head(go_df[<span>1</span>:<span>3</span>,<span>1</span>:<span>5</span>])<br><span>#                    ID                          Description setSize enrichmentScore      NES</span><br><span># GO:0000070 GO:0000070 mitotic sister chromatid segregation     151       0.6795449 2.956225</span><br><span># GO:0000819 GO:0000819         sister chromatid segregation     184       0.6542189 2.891093</span><br><span># GO:0098813 GO:0098813       nuclear chromosome segregation     236       0.6307606 2.868515</span><br></code></pre><h2 data-tool="mdnice编辑器"><span><span>4</span></span><span>dfGO2gseaResult</span><span></span></h2><blockquote data-tool="mdnice编辑器"><p><strong>dfGO2gseaResult</strong> 将 <strong>gseGO</strong> 输出的表格转为 <strong>gseaResult</strong> 对象。</p></blockquote><p data-tool="mdnice编辑器">我们先看看 <strong>go</strong> 对象:</p><figure data-tool="mdnice编辑器"><img data-imgfileid="100028972" data-ratio="0.607095926412615" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYpKfMB0mdHm6MYticS6s4ycnSpxMIkYBuicQic0QeIOySXZ9xxo0ziaXElg/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="761" src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYpKfMB0mdHm6MYticS6s4ycnSpxMIkYBuicQic0QeIOySXZ9xxo0ziaXElg/640?wx_fmt=png&amp;from=appmsg"></figure><p data-tool="mdnice编辑器">转换 <strong>(你需要提供对应的富集表格和排序的 geneList,还有注释文件)</strong>:</p><pre data-tool="mdnice编辑器"><span></span><code>test_go &lt;- dfGO2gseaResult(enrich.df = go_df,<br>                           geneList = geneList,<br>                           OrgDb = org.Hs.eg.db)<br></code></pre><figure data-tool="mdnice编辑器"><img data-imgfileid="100028971" data-ratio="0.6010362694300518" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYn2DRnLhXicuoiavmauIeC3dOKlNVl9NYf3LHWvAibiaPZcdR2jb6TQ1kEg/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="772" src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYn2DRnLhXicuoiavmauIeC3dOKlNVl9NYf3LHWvAibiaPZcdR2jb6TQ1kEg/640?wx_fmt=png&amp;from=appmsg"></figure><p data-tool="mdnice编辑器">对比两个对象的绘图结果(可以看到是一样的):</p><pre data-tool="mdnice编辑器"><span></span><code><span>library</span>(patchwork)<br><br>pnew &lt;- dotplot(test_go)<br>praw &lt;- dotplot(go)<br><br>plot_grid(praw,pnew)<br></code></pre><figure data-tool="mdnice编辑器"><img data-imgfileid="100028974" data-ratio="0.49329569513055754" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYzNDNEYDXBM6fVHDibMsyXeuDGiadko7gDdg8mADuicoyjeopN9I2YzO0A/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="1417" src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYzNDNEYDXBM6fVHDibMsyXeuDGiadko7gDdg8mADuicoyjeopN9I2YzO0A/640?wx_fmt=png&amp;from=appmsg"></figure><p data-tool="mdnice编辑器">绘制 <strong>gsea</strong> 图对比:</p><pre data-tool="mdnice编辑器"><span></span><code>gseaplot2(test_go,geneSetID = <span>"GO:0000070"</span>)<br>gseaplot2(go,geneSetID = <span>"GO:0000070"</span>)<br></code></pre><figure data-tool="mdnice编辑器"><img data-imgfileid="100028973" data-ratio="0.45078196872125115" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYZmibtzIQ1UpglicjnR4jHMG8pibNje8IbGMeaE34yqmsibgr4D6IEX4HgQ/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="1087" src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYZmibtzIQ1UpglicjnR4jHMG8pibNje8IbGMeaE34yqmsibgr4D6IEX4HgQ/640?wx_fmt=png&amp;from=appmsg"></figure><p data-tool="mdnice编辑器">用 <strong>gseaVis</strong> 画个看看:</p><pre data-tool="mdnice编辑器"><span></span><code>praw &lt;- gseaNb(object = go,geneSetID = <span>"GO:0000070"</span>)<br>pnew &lt;- gseaNb(object = test_go,geneSetID = <span>"GO:0000070"</span>)<br><br>plot_grid(praw,pnew)<br></code></pre><figure data-tool="mdnice编辑器"><img data-imgfileid="100028978" data-ratio="0.4667328699106256" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYict5tqTNBpk9fPfoeexcr64iblVypkdwtovPAoOu3ia7OHJuUJOzhjs6w/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="1007" src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYict5tqTNBpk9fPfoeexcr64iblVypkdwtovPAoOu3ia7OHJuUJOzhjs6w/640?wx_fmt=png&amp;from=appmsg"></figure><h2 data-tool="mdnice编辑器"><span><span>5</span></span><span>dfKEGG2gseaResult</span><span></span></h2><blockquote data-tool="mdnice编辑器"><p><strong>dfKEGG2gseaResult</strong> 将 <strong>gseGO</strong> 输出的表格转为 <strong>gseaResult</strong> 对象。</p></blockquote><p data-tool="mdnice编辑器">看一下 <strong>kk</strong> 对象:</p><figure data-tool="mdnice编辑器"><img data-imgfileid="100028977" data-ratio="0.6296296296296297" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYX4Az6QtpLBAFYgR0LoiciaP5j9OZjyTGz5aHBXfibmKWFG5P7r7wMutDg/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="756" src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYX4Az6QtpLBAFYgR0LoiciaP5j9OZjyTGz5aHBXfibmKWFG5P7r7wMutDg/640?wx_fmt=png&amp;from=appmsg"></figure><p data-tool="mdnice编辑器">转换:</p><pre data-tool="mdnice编辑器"><span></span><code>test_KK &lt;- dfKEGG2gseaResult(enrich.df = KK_df,<br>                             geneList = geneList,<br>                             organism = <span>"hsa"</span>)<br></code></pre><figure data-tool="mdnice编辑器"><img data-imgfileid="100028976" data-ratio="0.6157965194109772" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYflyqjQ6Kz4KUFQO50Ex1gxjIcL3BIGFodpOxNQIA43IknHTAe6vtFQ/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="747" src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYflyqjQ6Kz4KUFQO50Ex1gxjIcL3BIGFodpOxNQIA43IknHTAe6vtFQ/640?wx_fmt=png&amp;from=appmsg"></figure><p data-tool="mdnice编辑器">画图对比:</p><pre data-tool="mdnice编辑器"><span></span><code>pnew &lt;- dotplot(test_KK)<br>praw &lt;- dotplot(kk)<br><br>plot_grid(praw,pnew)<br></code></pre><figure data-tool="mdnice编辑器"><img data-imgfileid="100028979" data-ratio="0.4734576757532281" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYyIqtQ4EELvrntLf7S5ja0NtJ2ib1gUq3K0HDiar0UZsbvX7bcHxUAcKQ/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="1394" src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYyIqtQ4EELvrntLf7S5ja0NtJ2ib1gUq3K0HDiar0UZsbvX7bcHxUAcKQ/640?wx_fmt=png&amp;from=appmsg"></figure><pre data-tool="mdnice编辑器"><span></span><code>praw &lt;- gseaNb(object = kk,geneSetID = <span>"hsa04151"</span>)<br>pnew &lt;- gseaNb(object = test_KK,geneSetID = <span>"hsa04151"</span>)<br><br>plot_grid(praw,pnew)<br></code></pre><figure data-tool="mdnice编辑器"><img data-imgfileid="100028975" data-ratio="0.48829787234042554" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYmUeQibrsd0fmWHT3fZCtHNpe9BqsyQBdPZYS8E7m8XQMQgiafEg4KuDg/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="940" src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYmUeQibrsd0fmWHT3fZCtHNpe9BqsyQBdPZYS8E7m8XQMQgiafEg4KuDg/640?wx_fmt=png&amp;from=appmsg"></figure><h2 data-tool="mdnice编辑器"><span><span>6</span></span><span>其它</span><span></span></h2><figure data-tool="mdnice编辑器"><img data-imgfileid="100028985" data-ratio="0.7158570119156737" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYvPrF7GMxiadxLaophEia8BOEs2vV44IfIesfib4ymUNaYhd3Cuib4icV2JQ/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="1091" src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYvPrF7GMxiadxLaophEia8BOEs2vV44IfIesfib4ymUNaYhd3Cuib4icV2JQ/640?wx_fmt=png&amp;from=appmsg"></figure><p data-tool="mdnice编辑器">上面我们看到对应的基因是 <strong>ENTREZID</strong>,我们也可以在转换的对象上应用相关的函数,比如 ID 转换:</p><pre data-tool="mdnice编辑器"><span></span><code>test_KK2 &lt;- setReadable(test_KK,<br>                        OrgDb = <span>"org.Hs.eg.db"</span>,<br>                        keyType = <span>"ENTREZID"</span>)<br></code></pre><figure data-tool="mdnice编辑器"><img data-imgfileid="100028982" data-ratio="0.671244635193133" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYbA6ViaQiaU8rC5DcUEBFqglwYdocoLtjSac5qI2PecfSZUzDzJYsGPVw/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="1165" src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYbA6ViaQiaU8rC5DcUEBFqglwYdocoLtjSac5qI2PecfSZUzDzJYsGPVw/640?wx_fmt=png&amp;from=appmsg"></figure><h2 data-tool="mdnice编辑器"><span><span>7</span></span><span>结尾</span><span></span></h2><blockquote data-tool="mdnice编辑器"><p><strong>路漫漫其修远兮,吾将上下而求索。</strong></p></blockquote><hr data-tool="mdnice编辑器"><p data-tool="mdnice编辑器">欢迎加入生信交流群。加我微信我也拉你进 <strong>微信群聊</strong> <strong>老俊俊生信交流群</strong> <strong>(微信交流群需收取 20 元入群费用,一旦交费,拒不退还!(防止骗子和便于管理))</strong> 。QQ 群可免费加入, 记得进群按格式修改备注哦。</p><section data-tool="mdnice编辑器"><section><p><strong>老俊俊微信：</strong></p><figure><img data-imgfileid="100028983" data-ratio="1" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYrViasyVTI6wekuISWhgpwKiadek7CgIWC0rltw8A1fVia6rWLy0VhHrlA/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="430" src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYrViasyVTI6wekuISWhgpwKiadek7CgIWC0rltw8A1fVia6rWLy0VhHrlA/640?wx_fmt=png&amp;from=appmsg"></figure><figure><img data-imgfileid="100028981" data-ratio="1.3668430335097002" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadY15RWZl4iaSUFYgPibbnicicWGNolFMBGJ9Via6JenMhiaSOdNuuJxSWKTHEA/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="567" src="https://mmbiz.qpic.cn/sz_mmbiz_png/G5jjcE4usewz0RLJw08oiaoibHyHseYiadY15RWZl4iaSUFYgPibbnicicWGNolFMBGJ9Via6JenMhiaSOdNuuJxSWKTHEA/640?wx_fmt=png&amp;from=appmsg"></figure></section><section><p><strong>知识星球：</strong></p><figure><img data-imgfileid="100028984" data-ratio="1.5896226415094339" data-src="https://mmbiz.qpic.cn/sz_mmbiz_jpg/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYw35M8uH9ibGFUm0pZ6PWEEPlMDxTp8MLTc1hfZlQBRQRzdnRlLibicXrQ/640?wx_fmt=jpeg&amp;from=appmsg" data-type="jpeg" data-w="1060" src="https://mmbiz.qpic.cn/sz_mmbiz_jpg/G5jjcE4usewz0RLJw08oiaoibHyHseYiadYw35M8uH9ibGFUm0pZ6PWEEPlMDxTp8MLTc1hfZlQBRQRzdnRlLibicXrQ/640?wx_fmt=jpeg&amp;from=appmsg"></figure></section></section><hr data-tool="mdnice编辑器"><p data-tool="mdnice编辑器"><br></p><center data-tool="mdnice编辑器"><strong> 往期回顾目录</strong></center><blockquote data-tool="mdnice编辑器"><p><br></p><center><strong><a href="https://mp.weixin.qq.com/s?__biz=MzkyMTI1MTYxNA==&amp;mid=2247512269&amp;idx=1&amp;sn=0208555abacffaed2e8a8437c8b43214&amp;chksm=c1848abcf6f303aa83091c6c517b054ba4f7da2edc8de0fb86a2878064a91375a67cee89fd3b&amp;token=864433526&amp;lang=zh_CN&amp;scene=21#wechat_redirect" data-linktype="2">ggSCvis 可视化 dot/heatmap/violin plot 示例</a></strong></center><strong><center><a href="https://mp.weixin.qq.com/s?__biz=MzkyMTI1MTYxNA==&amp;mid=2247512189&amp;idx=1&amp;sn=1cc5cb6167f9d3960922dd691aa376db&amp;chksm=c1848a0cf6f3031a4b9b1ab4195d525269703553f84ef29ea312878c60accfec07ca3a3102d6&amp;token=864433526&amp;lang=zh_CN&amp;scene=21#wechat_redirect" data-linktype="2">给你的亚群添加编号</a></center></strong><strong><center><a href="https://mp.weixin.qq.com/s?__biz=MzkyMTI1MTYxNA==&amp;mid=2247512093&amp;idx=1&amp;sn=b44680cfccfa7c0bb0a59eef29b944fc&amp;chksm=c1848a6cf6f3037ad9e74e898575125b0cbd0d372c25805315559e5e41c9168c6e8612418896&amp;token=1185565850&amp;lang=zh_CN&amp;scene=21#wechat_redirect" data-linktype="2">ggSCvis 让你的单细胞可视化 gg 起来</a></center></strong><strong><center><a href="https://mp.weixin.qq.com/s?__biz=MzkyMTI1MTYxNA==&amp;mid=2247511755&amp;idx=1&amp;sn=b5758249eef3fdf4946aae0f4e7ef592&amp;chksm=c18494baf6f31dacdbf6e4a1ba0a05817b087a9bc1ad2a6b8b79959903ce5b96156e4e1a2faf&amp;token=1185565850&amp;lang=zh_CN&amp;scene=21#wechat_redirect" data-linktype="2">easylift 基因组坐标轻松转换</a></center></strong><strong><center><a href="https://mp.weixin.qq.com/s?__biz=MzkyMTI1MTYxNA==&amp;mid=2247511683&amp;idx=1&amp;sn=289992da1c3a551a4e5b8236fe830e94&amp;chksm=c18494f2f6f31de444ff98d314f7bfea97ade3573babe625200dd89b1cf86ccb47f287548e61&amp;token=1910483679&amp;lang=zh_CN&amp;scene=21#wechat_redirect" data-linktype="2">CCPlotR: 细胞通讯可视化包</a></center></strong><strong><center><a href="https://mp.weixin.qq.com/s?__biz=MzkyMTI1MTYxNA==&amp;mid=2247511206&amp;idx=1&amp;sn=30806bab4936d81aa5b626b3d69d828d&amp;chksm=c18496d7f6f31fc1b8993ebf3b36a9d8a1a5db32181a0cb85297c48016f5debcfb296cf58aa3&amp;token=1910483679&amp;lang=zh_CN&amp;scene=21#wechat_redirect" data-linktype="2">geom_genomicNestedZoom 放大视图</a></center></strong><strong><center><a href="https://mp.weixin.qq.com/s?__biz=MzkyMTI1MTYxNA==&amp;mid=2247511175&amp;idx=1&amp;sn=d88e495e3ecb62a29931bab3cb51d804&amp;chksm=c18496f6f6f31fe0b5d599fb2a8e0c6f001feb8d93ea214ce2ae1a5ea9bf59845739af520c04&amp;token=1304327956&amp;lang=zh_CN&amp;scene=21#wechat_redirect" data-linktype="2">听说你想给 pheatmap 添加感兴趣基因?</a></center></strong><strong><center><a href="https://mp.weixin.qq.com/s?__biz=MzkyMTI1MTYxNA==&amp;mid=2247510846&amp;idx=1&amp;sn=9483f23b436903fd4d74034a64e99e79&amp;chksm=c184914ff6f31859d557c2665f1e09b088ef716c5037f3030f7a12d9cbcd144aa9dd257f08d2&amp;token=843968300&amp;lang=zh_CN&amp;scene=21#wechat_redirect" data-linktype="2">给 heatmap 添加显著性标记</a></center></strong><strong><center><a href="https://mp.weixin.qq.com/s?__biz=MzkyMTI1MTYxNA==&amp;mid=2247510758&amp;idx=1&amp;sn=6a1d78131792e297d7be33aceb4711ba&amp;chksm=c1849097f6f3198159bbb4d66d4d1424d11da9ea07e896128573ebc63860aa2985e31ea5331d&amp;token=843968300&amp;lang=zh_CN&amp;scene=21#wechat_redirect" data-linktype="2">没有文档的 R 包不算好包</a></center></strong><strong><center><a href="https://mp.weixin.qq.com/s?__biz=MzkyMTI1MTYxNA==&amp;mid=2247510747&amp;idx=1&amp;sn=464460e587caf23d74ae7dde559a55c6&amp;chksm=c18490aaf6f319bc66e40f855881ff946d4cc6b2076868ffc18cb699fd89d4126ea2c1e941b8&amp;token=1323965478&amp;lang=zh_CN&amp;scene=21#wechat_redirect" data-linktype="2">听说你想用 ggcirclize 绘制和弦图?</a></center></strong></blockquote></section><p><mp-style-type data-value="3"></mp-style-type></p></div>

**Comment by alannearme** [comment]
普通格式能转换为gseaResult吗？
