### ISSUE TITLE
单细胞联合Bulk反卷积分析之CIBERSORTX

### ISSUE THREAD

**Issue by ixxmu** [ixxmu/mp_duty#4404]
https://mp.weixin.qq.com/s/M0xleUL5NZXCl8McoYN55A

**Comment by ixxmu** [comment]
单细胞联合Bulk反卷积分析之CIBERSORTX by 生信随笔
------
<div><section data-tool="mdnice编辑器" data-website="https://www.mdnice.com"><p data-tool="mdnice编辑器">关于<code>CIBERSORT</code>，两年前我在公众号【生信宝典】上写过一个帖子：</p><ul data-tool="mdnice编辑器"><li><section><a href="https://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247517199&amp;idx=1&amp;sn=5e4a7a51cf6febecab1886289a327bbd&amp;scene=21#wechat_redirect" data-linktype="2">Cibersort免疫浸润的在线分析及R语言代码实现</a></section></li></ul><p data-tool="mdnice编辑器"><code>CIBERSORT</code>（https://cibersortx.stanford.edu/）是Newman等人开发的一种分析工具，可基于基因表达数据估算免疫细胞丰度，最早发表于2015年的Nat Methods，截止2023年12月份总引用量高达8270次：</p><figure data-tool="mdnice编辑器"><img data-imgfileid="100004148" data-ratio="0.41483516483516486" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPZeFkH4kh2IlPFpicJJM0a20tudyvibbUasy5OZUMibKhr8m1K6uTbRFTw/640?wx_fmt=other&amp;from=appmsg" data-type="other" data-w="728" src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPZeFkH4kh2IlPFpicJJM0a20tudyvibbUasy5OZUMibKhr8m1K6uTbRFTw/640?wx_fmt=other&amp;from=appmsg"><figcaption>image-20231218204118001</figcaption></figure><p data-tool="mdnice编辑器">旧版的<code>CIBERSORT</code>算法严重依赖该文章开发的22种免疫细胞的signature matrix。然而随着单细胞转录组的广泛应用，这种不灵活的模式难以满足用户的灵活需求：用户需要基于自己的单细胞数据，然后从Bulk转录组数据中对感兴趣的细胞类型进行解卷积，因此Newman等人针对这个需求开发了<code>CIBERSORTX</code>（https://cibersortx.stanford.edu/）：</p><figure data-tool="mdnice编辑器"><img data-imgfileid="100004150" data-ratio="0.5462686567164179" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPCfItCO5owR9VAbWCOzfdI8CHYWfibWpADopZLHrRp1S63LicAwwWQArA/640?wx_fmt=other&amp;from=appmsg" data-type="other" data-w="670" src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPCfItCO5owR9VAbWCOzfdI8CHYWfibWpADopZLHrRp1S63LicAwwWQArA/640?wx_fmt=other&amp;from=appmsg"><figcaption>image-20231218204040255</figcaption></figure><p data-tool="mdnice编辑器">值得一提的是，尽管2019年的这篇文章目前引用量已达到了2256次，<strong>但是<code>CIBERSORTX</code>并没有提供R语言版本或者Python版本的运行代码，需要用户登录他们的网站进行分析。而且做了很多限制</strong>：</p><ul data-tool="mdnice编辑器"><li><section>首先，用户必须用edu结尾的邮箱进行注册才能成功登录；</section></li><li><section>其次，上传的文件大小受到限制，<code>CIBERSORTX</code>只提供给每个用户1个G大小的储存空间，但是实际上目前不管是单细胞还是Bulk转录组数据，非常容易超过1G的限制，这样的限制我搞不懂目的是啥，提供一个开源版本的R包或者Python包很难吗...</section></li><li><section>第三，<code>CIBERSORTX</code>的使用没有一个完整说明书。实际上，<code>CIBERSORTX</code>所需的文件格式有一些要求，没有经验的用户很容易遇到报错...</section></li></ul><p data-tool="mdnice编辑器">前两点我是没有能力解决的。关于第三点我做了一些笔记记录，现在分享给各位。</p><p data-tool="mdnice编辑器"><strong>本文参考：</strong></p><ul data-tool="mdnice编辑器"><li><section><p><a href="https://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247517199&amp;idx=1&amp;sn=5e4a7a51cf6febecab1886289a327bbd&amp;scene=21#wechat_redirect" data-linktype="2">Cibersort免疫浸润的在线分析及R语言代码实现</a></p></section></li><li><section><p><a href="https://mp.weixin.qq.com/s?__biz=MzI5ODI0NzM2OQ==&amp;mid=2247486221&amp;idx=1&amp;sn=56080af0c37452392631140c11f687db&amp;scene=21#wechat_redirect" data-linktype="2">优秀本科同学分享：CIBERSORTx全套全流程教程！</a>（写的挺好的一个推文，但是这篇推文关于输出数据的制作还有几点瑕疵，例如关于制作的表达矩阵，还需要用户手动打开csv文件输入列名，单细胞文件那么大，用EXCEL打开电脑容易<span>崩溃</span>；另外输出文件用write.table函数，单细胞矩阵比较大，<span>write.</span><span>table输出太慢了，在以下推文中我做了改进，fwrite函数加点参数可以实现秒输出。</span>）</p></section></li></ul><h3 data-tool="mdnice编辑器">一. 数据预处理</h3><p data-tool="mdnice编辑器">输入数据需要</p><ul data-tool="mdnice编辑器"><li><section>单细胞数据；</section></li><li><section>以及Bulk转录组数据。</section></li></ul><p data-tool="mdnice编辑器">关于bulk数据，CibersortX文章（https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7695353/）提示输入数据是芯片数据还是Bulk RNA-seq数据都可以，但是Bulk RNA-seq数据不建议直接使用Count，应使用FPKM或DESEq2标准化后，<strong>特别是TPM的矩阵为宜，没有负值或缺失值</strong>：</p><figure data-tool="mdnice编辑器"><img data-imgfileid="100004149" data-ratio="0.19773429454170957" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPCGpkx6P3NR5EDI0rvdHEia0I8zQg16D7nW1ic7sKbOQgRRKkmyOE23KQ/640?wx_fmt=other&amp;from=appmsg" data-type="other" data-w="971" src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPCGpkx6P3NR5EDI0rvdHEia0I8zQg16D7nW1ic7sKbOQgRRKkmyOE23KQ/640?wx_fmt=other&amp;from=appmsg"><figcaption>image-20231218205824509</figcaption></figure><pre data-tool="mdnice编辑器"><span></span><code><span>library</span>(Seurat)<br><span>library</span>(dplyr)<br><span>library</span>(IOBR)<br><span>library</span>(readr)<br><span>library</span>(data.table)<br><span>library</span>(stringr)<br></code></pre><h4 data-tool="mdnice编辑器">Step1. 读入数据</h4><pre data-tool="mdnice编辑器"><span></span><code><span>## 1.1 单细胞数据</span><br>seurat.data = read_rds(file = <span>"./Rawdata/scRNAseq.tutorial.gbm.rds"</span>)<br></code></pre><pre data-tool="mdnice编辑器"><span></span><code>table(seurat.data$cell.type)<br><span>#endothelial     myeloid       oligo    pericyte       tcell       tumor </span><br><span>#        492        2505         160         489          67       20080 </span><br></code></pre><p data-tool="mdnice编辑器">Bulk数据就是正常的TCGA下载下来的TPM表达矩阵：</p><pre data-tool="mdnice编辑器"><span></span><code><span>## 1.2 bulk数据</span><br>bk.tpm = read_rds(file = <span>"./Rawdata/TCGA.TPM.BulkRNAseq.rds"</span>)<br></code></pre><h4 data-tool="mdnice编辑器">Step2.从Seurat对象中制作单细胞表达矩阵（行为基因，列为细胞）</h4><p data-tool="mdnice编辑器"><strong>2.1 对cell.type进行抽样</strong></p><p data-tool="mdnice编辑器">由于单细胞数据太大，而CibersortX最多只支持1Gb的文件输入，因此需要我们对单细胞数据进行抽样：</p><pre data-tool="mdnice编辑器"><span></span><code><span>## 2.1 对cell.type进行抽样</span><br>Idents(seurat.data) = <span>"cell.type"</span><br>seurat.data.sub = subset(seurat.data, downsample = <span>500</span>)<br>seurat.data.sub<br></code></pre><pre data-tool="mdnice编辑器"><span></span><code>An object of class Seurat <br>60294 features across 2208 samples within 1 assay <br>Active assay: RNA (60294 features, 0 variable features)<br></code></pre><p data-tool="mdnice编辑器">.<strong>2.2 获得矩阵</strong></p><pre data-tool="mdnice编辑器"><span></span><code><span>## 2.2 获得矩阵</span><br>exp_matrix = as.data.frame(seurat.data.sub@assays$RNA@counts) <span>#表达矩阵</span><br>exp_matrix[<span>1</span>:<span>3</span>,<span>1</span>:<span>12</span>]<br><br>exp_matrix = exp_matrix %&gt;% <br> rownames_to_column(var = <span>"GeneSymbol"</span>) %&gt;%<br>      dplyr::select(GeneSymbol,everything())</code><code><span><span>## 2.3 设置细胞名称</span><br><span></span><span>colna</span><span>mes(exp_matrix)[-1] = </span><span>seurat</span><span>.</span><span>data.sub$cell.type</span></span></code></pre><pre data-tool="mdnice编辑器"><span></span><code><span>## 2.4 输出文件</span><br>fwrite(exp_matrix,file = <span>"./Outdata/Step1.CibersortX_scRNAassay.txt"</span>,sep = <span>"\t"</span>,row.names = <span>F</span>)<br></code></pre><h4 data-tool="mdnice编辑器">Step3.输出目标Bulk/芯片数据为txt文件</h4><pre data-tool="mdnice编辑器"><span></span><code>bk.tpm = bk.tpm %&gt;% <br> rownames_to_column(var = <span>"GeneSymbol"</span>) %&gt;%<br>      dplyr::select(GeneSymbol,everything())<br><br><span># 输出文件</span><br>fwrite(bk.tpm,file = <span>"./Outdata/Step1.CibersortX_TCGA_matrix_TPM.txt"</span>,sep = <span>"\t"</span>,row.names = <span>F</span>)<br></code></pre><h4 data-tool="mdnice编辑器">Step4. CibersortX网页操作</h4><p data-tool="mdnice编辑器">登录 https://cibersortx.stanford.edu/，操作如下：</p><figure data-tool="mdnice编辑器"><img data-imgfileid="100004151" data-ratio="0.5898760330578512" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPMpr9ohGDCY9WiaLDp2iaQs7QDN6fNDsSrwrZCVsWNODpbF6xHiaDaaiasQ/640?wx_fmt=other&amp;from=appmsg" data-type="other" data-w="968" src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPMpr9ohGDCY9WiaLDp2iaQs7QDN6fNDsSrwrZCVsWNODpbF6xHiaDaaiasQ/640?wx_fmt=other&amp;from=appmsg"><figcaption>image-20231218210528500</figcaption></figure><figure data-tool="mdnice编辑器"><img data-imgfileid="100004152" data-ratio="0.47962962962962963" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPibGGHia4iaMny8aIA2t2Z4KOBsiaCN9GsXic44O8iaCsHpicvheLN6rvcYpSw/640?wx_fmt=other&amp;from=appmsg" data-type="other" data-w="1080" src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPibGGHia4iaMny8aIA2t2Z4KOBsiaCN9GsXic44O8iaCsHpicvheLN6rvcYpSw/640?wx_fmt=other&amp;from=appmsg"><figcaption>image-20231218210535103</figcaption></figure><figure data-tool="mdnice编辑器"><img data-imgfileid="100004156" data-ratio="0.4816247582205029" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPDxYjKTtrfOic2dplibyRxnGvZLu3b2VQYo1gcS3QRicmeXIiaZRWHJ5ibVg/640?wx_fmt=other&amp;from=appmsg" data-type="other" data-w="1034" src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPDxYjKTtrfOic2dplibyRxnGvZLu3b2VQYo1gcS3QRicmeXIiaZRWHJ5ibVg/640?wx_fmt=other&amp;from=appmsg"><figcaption>image-20231218210546432</figcaption></figure><figure data-tool="mdnice编辑器"><img data-imgfileid="100004157" data-ratio="0.716624685138539" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPlQJB2rCp4trCiab0Tia168wmws5ZEvLe83tCJjt7Hg3lQ1vKicze182iaA/640?wx_fmt=other&amp;from=appmsg" data-type="other" data-w="794" src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPlQJB2rCp4trCiab0Tia168wmws5ZEvLe83tCJjt7Hg3lQ1vKicze182iaA/640?wx_fmt=other&amp;from=appmsg"><figcaption>image-20231218210552202</figcaption></figure><figure data-tool="mdnice编辑器"><img data-imgfileid="100004155" data-ratio="0.7396907216494846" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexP5uia0kttyLhhfhbn79BmRkMxqhxbjHfJmXb9xfrZR2qhMcX4Tqib14ibA/640?wx_fmt=other&amp;from=appmsg" data-type="other" data-w="776" src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexP5uia0kttyLhhfhbn79BmRkMxqhxbjHfJmXb9xfrZR2qhMcX4Tqib14ibA/640?wx_fmt=other&amp;from=appmsg"><figcaption>image-20231218210557817</figcaption></figure><figure data-tool="mdnice编辑器"><img data-imgfileid="100004154" data-ratio="0.7229064039408867" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPia6LVLvUw7eYia7Iib15EtK8nr6jUSwEVcUWN07p6b8GcBs66DmABDQ5Q/640?wx_fmt=other&amp;from=appmsg" data-type="other" data-w="812" src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPia6LVLvUw7eYia7Iib15EtK8nr6jUSwEVcUWN07p6b8GcBs66DmABDQ5Q/640?wx_fmt=other&amp;from=appmsg"><figcaption>image-20231218210603080</figcaption></figure><figure data-tool="mdnice编辑器"><img data-imgfileid="100004153" data-ratio="0.8696319018404908" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPic3B6QbuatQlcMbcd3PdItSepuJyV8jMNlbN2XJP0oN18IbovLickWHw/640?wx_fmt=other&amp;from=appmsg" data-type="other" data-w="652" src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPic3B6QbuatQlcMbcd3PdItSepuJyV8jMNlbN2XJP0oN18IbovLickWHw/640?wx_fmt=other&amp;from=appmsg"><figcaption>image-20231218210612916</figcaption></figure><figure data-tool="mdnice编辑器"><img data-imgfileid="100004162" data-ratio="0.9579124579124579" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexP8JLiahuvCC49QUG5lZmKc314aE114KvcficO38mKr0nxPYxKlAsFEJbA/640?wx_fmt=other&amp;from=appmsg" data-type="other" data-w="594" src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexP8JLiahuvCC49QUG5lZmKc314aE114KvcficO38mKr0nxPYxKlAsFEJbA/640?wx_fmt=other&amp;from=appmsg"><figcaption>image-20231218210619245</figcaption></figure><p data-tool="mdnice编辑器">点击CSV按钮输出结果，然后读入R语言进行可视化。</p><h4 data-tool="mdnice编辑器">Step5. 可视化</h4><p data-tool="mdnice编辑器">可视化内容比较个性化，例如组间差异分析和相关性分析：</p><pre data-tool="mdnice编辑器"><span></span><code><span>library</span>(corrplot)<br><span>if</span>(<span>T</span>){<br>  mytheme &lt;- theme(plot.title = element_text(size = <span>12</span>,color=<span>"black"</span>,hjust = <span>0.5</span>),<br>                   axis.title = element_text(size = <span>12</span>,color =<span>"black"</span>), <br>                   axis.text = element_text(size= <span>12</span>,color = <span>"black"</span>),<br>                   panel.grid.minor.y = element_blank(),<br>                   panel.grid.minor.x = element_blank(),<br>                   axis.text.x = element_text(angle = <span>45</span>, hjust = <span>1</span> ),<br>                   panel.grid=element_blank(),<br>                   legend.position = <span>"top"</span>,<br>                   legend.text = element_text(size= <span>12</span>),<br>                   legend.title= element_text(size= <span>12</span>)<br>  )}<br><br>TME_data &lt;- read.csv(<span>"./Outdata/CIBERSORTx_Job31_Results.csv"</span>,header = <span>T</span>,row.names = <span>1</span>)<br>head(TME_data)<br><br>TME_data = select(TME_data, tumor:oligo)<br><br><span># 5.1 数据粗处理</span><br>TME_New = TME_data<br><br><span>#自行添加分组信息，例如癌和癌旁组：</span><br>TME_New$group &lt;- as.factor(clic$group)<br>TME_New$sample &lt;- row.names(TME_New)<br><br>head(TME_New)<br><br><span># 5.2 融合数据</span><br>TME_New = reshape2::melt(TME_New)<br>colnames(TME_New)=c(<span>"Group"</span>,<span>"Sample"</span>,<span>"Celltype"</span>,<span>"Composition"</span>) <span>#设置行名</span><br>head(TME_New)<br><br><span># 5.3 可视化</span><br>plot_order = TME_New %&gt;% <br>  group_by(Celltype) %&gt;% <br>  summarise(m = median(Composition)) %&gt;% <br>  arrange(desc(m)) %&gt;% <br>  pull(Celltype)<br>plot_order<br><br>TME_New$Celltype = factor(TME_New$Celltype,levels = plot_order)<br><br>ggplot(TME_New, aes(x = Celltype, y = Composition))+ <br>  labs(y=<span>"Cell composition"</span>,x= <span>NULL</span>,title = <span>"TME Cell composition"</span>)+  <br>  geom_boxplot(aes(fill = Group),position=position_dodge(<span>0.5</span>),width=<span>0.5</span>,outlier.alpha = <span>0</span>)+ <br>  scale_fill_manual(values = c(<span>"#1CB4B8"</span>, <span>"#EB7369"</span>))+<br>  theme_classic() + mytheme + <br>  stat_compare_means(aes(group = Group),<br>                     label = <span>"p.signif"</span>,<br>                     method = <span>"wilcox.test"</span>,<br>                     hide.ns = <span>F</span>)<br></code></pre><figure data-tool="mdnice编辑器"><img data-imgfileid="100004158" data-ratio="0.7395437262357415" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPrr5xgsYvyd1CakquXnHAdC4keDIL1oJjv0f2NicnzfvV1Rt1rdYKfMg/640?wx_fmt=other&amp;from=appmsg" data-type="other" data-w="526" src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPrr5xgsYvyd1CakquXnHAdC4keDIL1oJjv0f2NicnzfvV1Rt1rdYKfMg/640?wx_fmt=other&amp;from=appmsg"><figcaption>image-20231218210945468</figcaption></figure><p data-tool="mdnice编辑器">另外，如果还有一些相关性分析的需求：</p><pre data-tool="mdnice编辑器"><span></span><code><span>library</span>(corrplot)<br>corda.cell.type &lt;- psych::corr.test(TME_data, TME_data, method = <span>"sp"</span>)<br>r.df = as.matrix(corda.cell.type$r)<br>p.df = as.matrix(corda.cell.type$p.adj)<br><br>corrplot(as.matrix(r.df),<br>         method = <span>"color"</span>,<br>         col=rev(COL2(<span>"RdBu"</span>, <span>200</span>)),<br>         type = c(<span>"upper"</span>),<br>         p.mat = p.df,<span>#是否添加了P值，如果是NULL，则sig.level到pch.cex参数无效</span><br>         sig.level = <span>0.05</span>,<span>#P值检验水平设置</span><br>         insig = c(<span>"label_sig"</span>),<br>         pch.cex = <span>1</span>, <br>         tl.col = <span>"black"</span>,<br>         tl.cex = <span>0.8</span>,<span>#文本标签的大小</span><br>         na.label = <span>""</span>,<span>#NA值如何表示</span><br>         na.label.col = <span>"#bcb9b5"</span>,<span>#表示NA值符号的颜色</span><br>)<br></code></pre><figure data-tool="mdnice编辑器"><img data-imgfileid="100004160" data-ratio="0.9395348837209302" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPPiaU06HCX9jWGbbQOct6utYUHpKTpD6PZPPib2lodPV14L1ibZN7RPWrA/640?wx_fmt=other&amp;from=appmsg" data-type="other" data-w="430" src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPPiaU06HCX9jWGbbQOct6utYUHpKTpD6PZPPib2lodPV14L1ibZN7RPWrA/640?wx_fmt=other&amp;from=appmsg"><figcaption>image-20231218211059482</figcaption></figure><p data-tool="mdnice编辑器">相关性散点图：</p><pre data-tool="mdnice编辑器"><span></span><code>ggplot(data = TME_data, aes(x = myeloid, y = pericyte)) + <br>  geom_point(size=<span>1</span>,show.legend=<span>T</span>)+ <br>  labs(title = <span>"Myeloid vs. Pericyte"</span>, x=<span>"Proportion of myeloid cells"</span>,y=<span>"Proportion of pericyte cells"</span>) + <br>  geom_smooth(method=<span>"lm"</span>,formula= <span>'y ~ x'</span>,color=<span>"red"</span>,linetype=<span>2</span>,)+theme_bw()+ <br>  stat_cor(method = <span>"sp"</span>,<br>           label.sep = <span>"\n"</span>,<br>           label.y.npc = <span>"top"</span>,<br>           size = <span>2.8</span>) +<br>  mytheme<br></code></pre><figure data-tool="mdnice编辑器"><img data-imgfileid="100004159" data-ratio="0.9625668449197861" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPB8NWrwWBsLZCDdtpEgk6RefnojiaEH5iaZs6F5PSeIOO63mlasjbAw3w/640?wx_fmt=other&amp;from=appmsg" data-type="other" data-w="374" src="https://mmbiz.qpic.cn/mmbiz_jpg/fTW9zRI3eqUIibXn5Uy5sLdsmibbzzJexPB8NWrwWBsLZCDdtpEgk6RefnojiaEH5iaZs6F5PSeIOO63mlasjbAw3w/640?wx_fmt=other&amp;from=appmsg"><figcaption>image-20231218211124457</figcaption></figure><p data-tool="mdnice编辑器">分析结束，希望对各位有帮助！</p><span>- END -</span></section><p><br></p><p><mp-style-type data-value="3"></mp-style-type></p></div>

**Comment by Yinzhou-Feng** [comment]
您好！感谢分享！关于单细胞数据的格式问题想问一下，按照推文中这样写的@assays$RNA@counts获得的是不是稀疏矩阵？是否需要转换成normalized过的dense矩阵再进行上传？
