### ISSUE TITLE
​单细胞专题 | 14 Seurat v5版本融合多样本的单细胞数据以及一些报错问题

### ISSUE THREAD

**Issue by ixxmu** [ixxmu/mp_duty#4729]
https://mp.weixin.qq.com/s/WzgbxctcuIhl2Ox9OcYMng

**Comment by ixxmu** [comment]
​单细胞专题 | 14 Seurat v5版本融合多样本的单细胞数据以及一些报错问题 by 生物信息云
------
<div><section><mp-common-profile data-pluginname="mpprofile" data-id="MzA4NDAzODkzMA==" data-headimg="http://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxWN6ialKv18AuE9NAspKUjBTu1vDKIiaVNfPJmP2iaZGCB4RuvytSBVEqoqMI9mIa91jfCmp1jWwA8g/0?wx_fmt=png" data-nickname="生物信息云" data-alias="MedBioInfoCloud" data-signature="生信菜鸟的云笔记" data-from="0" data-is_biz_ban="0" data-weui-theme="light"></mp-common-profile></section><hr><p><img data-imgfileid="503802200" data-ratio="0.25" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/dREape4YBzyF5jVxNCORGgSJRgWqy8hD1vw3aTCTiauBVLErhPNxeAq1Z3p1iaawPViah3KsJ6q4ibys098ibmnjzcQ/640?wx_fmt=jpeg" data-type="jpeg" data-w="600" src="https://mmbiz.qpic.cn/mmbiz_jpg/dREape4YBzyF5jVxNCORGgSJRgWqy8hD1vw3aTCTiauBVLErhPNxeAq1Z3p1iaawPViah3KsJ6q4ibys098ibmnjzcQ/640?wx_fmt=jpeg"><br></p><hr><p>V5版本的<span>Seurat</span><span>数据对象结构和V4有的差别，在用V4版本的代码分析时，V5在提取counts矩阵时会报错，这里我们介绍一下融合多个样本的数据，以及这个报错的原因。</span></p><hr><p><strong><span>1.数据信息</span></strong><br></p><p><span><span><span>在分离CD45阴性和CD45阳性细胞后，收集CD45阴性细胞用于后续的scRNAseq测序。</span></span></span></p><p><span>https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE130001</span><span><span></span></span></p><p><span>文献：Wang L, Sebra RP, Sfakianos JP, Allette K et al. A reference profile-free deconvolution method to infer cancer cell-intrinsic subtypes and tumor-type-specific stromal profiles. </span><span><span><span>Genome Med</span></span></span><span> 2020 Feb 28;12(1):24. PMID: </span><span>32111252</span><span><span></span></span></p><p><span></span><span><strong><span>2.数据下载</span></strong></span></p><p><span><shape type="#_x0000_t75" filled="f"><imagedata title="rId23"></imagedata></shape><img data-imgfileid="503802213" data-ratio="0.15178571428571427" data-src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzwvk0SjxJUsok468oqfITLuMM8bhf8libtkxvib7OtEPPxIV0pg5T1mAXziaVqfAVBgyF2OSTb0w9k6A/640?wx_fmt=other&amp;tp=webp&amp;wxfrom=5&amp;wx_lazy=1&amp;wx_co=1" data-type="png" data-w="560" src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzwvk0SjxJUsok468oqfITLuMM8bhf8libtkxvib7OtEPPxIV0pg5T1mAXziaVqfAVBgyF2OSTb0w9k6A/640?wx_fmt=other&amp;tp=webp&amp;wxfrom=5&amp;wx_lazy=1&amp;wx_co=1"></span><span><span></span></span></p><p><span>下载解压数据：</span><br></p><p><span><img data-imgfileid="503802215" data-ratio="0.3875" data-src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzwvk0SjxJUsok468oqfITLuUtxiawwib1TqdkwAoEdWUCyEsiab7PoYkbO4nFrrPWUX1Y8SRjUjX4rzw/640?wx_fmt=other&amp;tp=webp&amp;wxfrom=5&amp;wx_lazy=1&amp;wx_co=1" data-type="png" data-w="560" src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzwvk0SjxJUsok468oqfITLuUtxiawwib1TqdkwAoEdWUCyEsiab7PoYkbO4nFrrPWUX1Y8SRjUjX4rzw/640?wx_fmt=other&amp;tp=webp&amp;wxfrom=5&amp;wx_lazy=1&amp;wx_co=1"></span></p><p><span></span><span><strong><span>3.数据预处理</span></strong></span></p><p><span><span><span>这里的数据是10X标准输出的3个文件，这三个文件指的是：barcodes.tsv, features.tsv, matrix.mtx。这个情况就比较好处理了，barcodes.tsv就是 cell id，features.tsv就是 gene id，matrix.mtx就是计数 counts 矩阵。但我们需要整理一下文件。因为文件名多了一些信息，需要为每个样本单独建立一个文件夹，然后将该样本3个文件对应的重命名一下就可以了。就如下面是一个样本重命名后的。</span></span></span></p><p><span><img data-imgfileid="503802214" data-ratio="0.225" data-src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzwvk0SjxJUsok468oqfITLuOiak5b0booJPZ7oCKHhZ78xicWa1cuicJMWu4bia1jy9GicrFqIkTerPw8w/640?wx_fmt=other&amp;tp=webp&amp;wxfrom=5&amp;wx_lazy=1&amp;wx_co=1" data-type="png" data-w="560" src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzwvk0SjxJUsok468oqfITLuOiak5b0booJPZ7oCKHhZ78xicWa1cuicJMWu4bia1jy9GicrFqIkTerPw8w/640?wx_fmt=other&amp;tp=webp&amp;wxfrom=5&amp;wx_lazy=1&amp;wx_co=1"></span><span><span></span></span></p><p><span><br></span></p><p><span>当然，可以用代码解决，需要注意文件路径。</span></p><section><ul><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li></ul><pre data-lang="php"><code><span><span>###============1、准备原始分析数据</span></span></code><code><span>fs = <span>list</span>.files(<span>'./GSE130001_RAW/'</span>,<span>'^GSM'</span>)</span></code><code><span>library(stringr)</span></code><code><span>samples = str_split(fs,<span>'_'</span>,simplify = T)[,<span>1</span>]</span></code><code><span><span># x &lt;- "GSM3729178"</span></span></code><code><span>lapply(unique(samples),<span><span>function</span><span>(x)</span></span>{</span></code><code><span>  y = fs[grepl(x,fs)]</span></code><code><span>  folder = paste0(<span>"GSE130001_RAW/"</span>, x)</span></code><code><span>  dir.create(folder,recursive = T)<span>#为每个样本创建子文件夹</span></span></code><code><span> </span></code><code><span>  <span>#重命名文件，并移动到相应的子文件夹里,注意对应顺序</span></span></code><code><span>  file.rename(paste0(<span>"GSE130001_RAW/"</span>,y[<span>1</span>]),file.path(folder,<span>"barcodes.tsv.gz"</span>))</span></code><code><span>  file.rename(paste0(<span>"GSE130001_RAW/"</span>,y[<span>2</span>]),file.path(folder,<span>"features.tsv.gz"</span>))</span></code><code><span>  file.rename(paste0(<span>"GSE130001_RAW/"</span>,y[<span>3</span>]),file.path(folder,<span>"matrix.mtx.gz"</span>))</span></code><code><span>})</span></code></pre></section><p><span><img data-imgfileid="503802217" data-ratio="0.425" data-src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzwvk0SjxJUsok468oqfITLuRpPn58lWF5YVXN20XepfLb8GuPjKbSaM1rFjzcuB18g8SBdfsUHyUw/640?wx_fmt=other&amp;tp=webp&amp;wxfrom=5&amp;wx_lazy=1&amp;wx_co=1" data-w="560" src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzwvk0SjxJUsok468oqfITLuRpPn58lWF5YVXN20XepfLb8GuPjKbSaM1rFjzcuB18g8SBdfsUHyUw/640?wx_fmt=other&amp;tp=webp&amp;wxfrom=5&amp;wx_lazy=1&amp;wx_co=1"></span></p><p><strong><span>4.读入数据创建Seurat对象</span></strong></p><section><ul><li><li><li><li><li><li><li><li><li><li><li><li><li><li><li></ul><pre data-lang="makefile"><code><span>library(Seurat)</span></code><code><span><span># 循环读取两个文件夹下面的10x的的3个文件</span></span></code><code><span>samples=list.files(<span>"GSE130001_RAW/"</span>)</span></code><code><span>samples</span></code><code><span><br></span></code><code><span>sceList = lapply(samples,function(pro){</span></code><code><span>  folder=file.path(<span>"GSE130001_RAW/"</span>,pro)</span></code><code><span>  CreateSeuratObject(counts = Read10X(folder),</span></code><code><span>                     project = pro )</span></code><code><span>})</span></code><code><span><span>###合并多个样本</span></span></code><code><span>sce.merg&lt;- merge(sceList[[1]],</span></code><code><span>                 y = c(sceList[[2]]),</span></code><code><span>                 add.cell.ids = samples,</span></code><code><span>                 project = <span>"GSE130001"</span>)</span></code></pre></section><p>前面这些操作，在V4和V5版本一样，<span>Seurat</span>数据对象在这两个版本中有点区别。V4版本中提取count数据使用<span>sce.</span><span>all</span><span>@assays$RNA@counts</span>。<span>V5版本中数据结构发生变化。</span></p><p><img data-galleryid="" data-imgfileid="503802218" data-ratio="0.457252641690682" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzwPbxB1yTQ7uvb2W2Xb2GvRPkibyRhFIbia5ia11fpUjr7V1DUTuXtk7nHIaWZvABKjgkdHRJgAXKpog/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="1041" src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzwPbxB1yTQ7uvb2W2Xb2GvRPkibyRhFIbia5ia11fpUjr7V1DUTuXtk7nHIaWZvABKjgkdHRJgAXKpog/640?wx_fmt=png&amp;from=appmsg"></p><p><span>数据多了Layers层，所以使用原来的数据索引方式会报错。正确的索引方式应该是<span>sce.merg@assays[[</span><span>"RNA"</span><span>]]@layers[[</span><span>"counts.GSM3729178"</span><span>]]</span>，但我们发现，我们融合两个样本的数据，它们的counts并没有融合成为一个矩阵。因此我们需要将他融合在一起。我们需要使用<span>JoinLayers()</span>函数将其彻底融合。</span></p><section><ul><li></ul><pre data-lang="css"><code><span><span>sce</span><span>.merg</span> &lt;<span>-</span> <span>JoinLayers</span>(<span>sce</span><span>.merg</span>)</span></code></pre></section><p><img data-galleryid="" data-imgfileid="503802219" data-ratio="0.4856815578465063" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzwPbxB1yTQ7uvb2W2Xb2GvRyr7KibIWC23miacCAYiafG9RKOHZTvm7oTAWI1sIXCc2297msic13S7t8g/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="873" src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzwPbxB1yTQ7uvb2W2Xb2GvRyr7KibIWC23miacCAYiafG9RKOHZTvm7oTAWI1sIXCc2297msic13S7t8g/640?wx_fmt=png&amp;from=appmsg"></p><p><span>提取count矩阵</span></p><p><span>方式1，直接索引：<br></span></p><section><ul><li></ul><pre data-lang="css"><code><span><span>sce</span><span>.merg</span>@<span>assays</span>[["<span>RNA</span>"]]@<span>layers</span>[["<span>counts</span>"]]</span></code></pre></section><p><span>方式2，<span>GetAssayData()</span>函数。</span></p><section><ul><li></ul><pre data-lang="ini"><code><span><span>c2</span> = GetAssayData(object = sce.merg,assay = <span>"RNA"</span>,slot = <span>"counts"</span>)</span></code></pre></section><p><span><span>方式</span><span>3</span><span>，</span><span><span>LayerData</span>()</span><span>函</span><span>数</span><span>。</span></span></p><section><ul><li></ul><pre data-lang="ini"><code><span><span>c3</span> = LayerData(object = sce.merg,assay = <span>"RNA"</span>,layer = <span>"counts"</span>)</span></code></pre></section><p><span>后续的分析几乎差不多，不同样本的单细胞数据，最后是去除批次效应，V5版本里面已经整合了很多去除批次效应的方法。也可参考<a target="_blank" href="http://mp.weixin.qq.com/s?__biz=MzA4NDAzODkzMA==&amp;mid=2651285722&amp;idx=1&amp;sn=6483e7e9002b915d3a9223f52b60f531&amp;chksm=841e8ca7b36905b1b35f2ff7aacf40bcb3090439c11a4171fb2e7399f83a383ab788eb17d478&amp;scene=21#wechat_redirect" textvalue="harmony包整合多批次单细胞数据以去除批次效应（batch effect）" linktype="text" imgurl="" imgdata="null" data-itemshowtype="0" tab="innerlink" data-linktype="2">harmony包整合多批次单细胞数据以去除批次效应（batch effect）</a>。<br></span></p><p><br></p><hr><p><img data-galleryid="" data-imgfileid="503802197" data-ratio="1.0291970802919708" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzwlcDib0ZJoicuLyG92DicwGVnDorFCjt6v1RVJKusT6ib2vicAibS7CvADLziaUWZHqictxy4YkgyhsggMbg/640?wx_fmt=png&amp;wxfrom=5&amp;wx_lazy=1&amp;wx_co=1" data-type="png" data-w="274" src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzwlcDib0ZJoicuLyG92DicwGVnDorFCjt6v1RVJKusT6ib2vicAibS7CvADLziaUWZHqictxy4YkgyhsggMbg/640?wx_fmt=png&amp;wxfrom=5&amp;wx_lazy=1&amp;wx_co=1"></p><p>B站视频合集</p><hr><section><img data-imgfileid="503802199" data-ratio="1" data-src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzw321c7L6nrpqs6Sa0FGFzaFwzp7pdXrJZ5QRhib950DOAUMrj2NDyfuonw7jbnBljp2rxeQJlAyng/640?wx_fmt=png&amp;wxfrom=5&amp;wx_lazy=1&amp;wx_co=1" data-w="400" src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzw321c7L6nrpqs6Sa0FGFzaFwzp7pdXrJZ5QRhib950DOAUMrj2NDyfuonw7jbnBljp2rxeQJlAyng/640?wx_fmt=png&amp;wxfrom=5&amp;wx_lazy=1&amp;wx_co=1"></section><p><a target="_blank" href="http://mp.weixin.qq.com/s?__biz=MzA4NDAzODkzMA==&amp;mid=2651278937&amp;idx=1&amp;sn=70b476a444883a9282efc13ee9c19a72&amp;chksm=841eaa24b3692332de6263a5ed15e2b3da3017845d6e533a0b7944624afd2fc3275710f61439&amp;scene=21#wechat_redirect" textvalue="加入生信学习交流群" linktype="text" imgurl="" imgdata="null" data-itemshowtype="0" tab="innerlink" data-linktype="2" hasload="1"><strong>加入生信学习交流群</strong></a></p><hr><p><br></p><section data-mpa-template="t" mpa-from-tpl="t" data-mpa-powered-by="yiban.io"><section data-mid="" mpa-from-tpl="t"><section data-mid="" mpa-from-tpl="t"><section data-mid="" mpa-from-tpl="t"><section data-mid="" mpa-from-tpl="t"><p data-mid=""><span>经    典    栏    目</span></p></section></section><section data-mid="" mpa-from-tpl="t"><br></section><section data-mid="" mpa-from-tpl="t"><br></section></section></section></section><p><br></p><section data-mpa-template="t" mpa-from-tpl="t"><section data-mid="" mpa-from-tpl="t"><section data-mid="" mpa-from-tpl="t"><section data-mid="" mpa-from-tpl="t"><br></section><section data-mid="" mpa-from-tpl="t"><br></section><section data-mid="" mpa-from-tpl="t"><section data-mid="" mpa-from-tpl="t"><table align="center"><tbody><tr><td width="243" valign="bottom" align="center" height="45"><a target="_blank" href="https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzA4NDAzODkzMA==&amp;action=getalbum&amp;album_id=1338047035672526848#wechat_redirect" textvalue="你已选中了添加链接的内容" tab="innerlink" data-linktype="1"><span data-positionback="static"><img data-ratio="0.2084639498432602" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RNDhkvd0VYruWibnf6I99uicOsqFSIPicvmUP7w8m3ictoTgeAmsmF6v40nqw/640?wx_fmt=png" data-type="png" data-w="638" data-imgfileid="503802201" src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RNDhkvd0VYruWibnf6I99uicOsqFSIPicvmUP7w8m3ictoTgeAmsmF6v40nqw/640?wx_fmt=png"></span></a></td><td width="243" valign="bottom" align="center" height="45"><a target="_blank" href="https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzA4NDAzODkzMA==&amp;action=getalbum&amp;album_id=1385753371944239106#wechat_redirect" textvalue="你已选中了添加链接的内容" tab="innerlink" data-linktype="1"><span data-positionback="static"><img data-ratio="0.2084639498432602" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RND8LOmqZpGNerHE2ib3hrYBm7czV8ibjkg6bgUynABicHtDblDwibcK0iafdg/640?wx_fmt=png" data-type="png" data-w="638" data-imgfileid="503802198" src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RND8LOmqZpGNerHE2ib3hrYBm7czV8ibjkg6bgUynABicHtDblDwibcK0iafdg/640?wx_fmt=png"></span></a></td></tr><tr><td width="243" valign="bottom" align="center" height="45"><a target="_blank" href="https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzA4NDAzODkzMA==&amp;action=getalbum&amp;album_id=1410264757734817793#wechat_redirect" textvalue="你已选中了添加链接的内容" tab="innerlink" data-linktype="1"><span data-positionback="static"><img data-ratio="0.2084639498432602" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RNDnwmiaAUS36yqYw6aeJ9iaNkNUGmcU7ux65wvficPlQXDHQibW3JYrFJFvQ/640?wx_fmt=png" data-type="png" data-w="638" data-imgfileid="503802205" src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RNDnwmiaAUS36yqYw6aeJ9iaNkNUGmcU7ux65wvficPlQXDHQibW3JYrFJFvQ/640?wx_fmt=png"></span></a></td><td width="243" valign="bottom" align="center" height="45"><a target="_blank" href="https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzA4NDAzODkzMA==&amp;action=getalbum&amp;album_id=1369789283514761218#wechat_redirect" textvalue="你已选中了添加链接的内容" tab="innerlink" data-linktype="1"><span data-positionback="static"><img data-ratio="0.20689655172413793" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RNDANc1t4lIm5wTqesgaITcicUlfiaXHrSxrKVeWZYCzlH9MSy7IibTYQLNg/640?wx_fmt=png" data-type="png" data-w="638" data-imgfileid="503802206" src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RNDANc1t4lIm5wTqesgaITcicUlfiaXHrSxrKVeWZYCzlH9MSy7IibTYQLNg/640?wx_fmt=png"></span></a></td></tr><tr><td width="243" valign="bottom" align="center" height="45"><a target="_blank" href="https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzA4NDAzODkzMA==&amp;action=getalbum&amp;album_id=1519504738202025984#wechat_redirect" textvalue="你已选中了添加链接的内容" tab="innerlink" data-linktype="1"><span data-positionback="static"><img data-imgfileid="503802204" data-ratio="0.2084639498432602" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RNDQmkz6ffBVfRj1Ab8ibMyygNmmvL7yia3eoZzJNoWjNW6vwjG4y3PWsNg/640?wx_fmt=png" data-type="png" data-w="638" src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RNDQmkz6ffBVfRj1Ab8ibMyygNmmvL7yia3eoZzJNoWjNW6vwjG4y3PWsNg/640?wx_fmt=png"></span></a></td><td width="243" valign="bottom" align="center" height="45"><a target="_blank" href="https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzA4NDAzODkzMA==&amp;action=getalbum&amp;album_id=1519504738034253825#wechat_redirect" textvalue="你已选中了添加链接的内容" tab="innerlink" data-linktype="1"><span data-positionback="static"><img data-imgfileid="503802202" data-ratio="0.20689655172413793" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RNDCpphsguALa0tR6pfEy8yLBahRX9iaeYdKCwicKFbBd2X1yTSiaZyZwFqA/640?wx_fmt=png" data-type="png" data-w="638" src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RNDCpphsguALa0tR6pfEy8yLBahRX9iaeYdKCwicKFbBd2X1yTSiaZyZwFqA/640?wx_fmt=png"></span></a></td></tr><tr><td width="243" valign="bottom" align="center" height="45"><a target="_blank" href="https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzA4NDAzODkzMA==&amp;action=getalbum&amp;album_id=1687484069455986690#wechat_redirect" textvalue="你已选中了添加链接的内容" tab="innerlink" data-linktype="1"><span data-positionback="static"><img data-imgfileid="503802203" data-ratio="0.2084639498432602" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RND73kOWY2pcLs5dmFMQWCG1Noz1oRR2oBCDHgNjiaAXqEZkLllKtoeO0g/640?wx_fmt=png" data-type="png" data-w="638" src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RND73kOWY2pcLs5dmFMQWCG1Noz1oRR2oBCDHgNjiaAXqEZkLllKtoeO0g/640?wx_fmt=png"></span></a></td><td width="243" valign="bottom" align="center" height="45"><a target="_blank" href="https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzA4NDAzODkzMA==&amp;action=getalbum&amp;album_id=1521974159344533507#wechat_redirect" textvalue="你已选中了添加链接的内容" tab="innerlink" data-linktype="1"><span data-positionback="static"><img data-ratio="0.20689655172413793" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RND6nm4ADziajqL0hpSudJTiacRyqVOg9NpnKoyfmVOgzwp97HicIFjb0gDw/640?wx_fmt=png" data-type="png" data-w="638" data-imgfileid="503802211" src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RND6nm4ADziajqL0hpSudJTiacRyqVOg9NpnKoyfmVOgzwp97HicIFjb0gDw/640?wx_fmt=png"></span></a></td></tr><tr><td width="243" valign="bottom" align="center" height="45"><a target="_blank" href="https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzA4NDAzODkzMA==&amp;action=getalbum&amp;album_id=1715194110111776770#wechat_redirect" textvalue="你已选中了添加链接的内容" tab="innerlink" data-linktype="1"><span data-positionback="static"><img data-imgfileid="503802208" data-ratio="0.2087912087912088" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RNDRBOVZUPB816xXqA1SlbNzDRkmNRSjtCa3pqjuyAoQJxa1drcW0yeZQ/640?wx_fmt=png" data-type="png" data-w="637" src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RNDRBOVZUPB816xXqA1SlbNzDRkmNRSjtCa3pqjuyAoQJxa1drcW0yeZQ/640?wx_fmt=png"></span></a></td><td width="243" valign="bottom" align="center" height="45"><a target="_blank" href="https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzA4NDAzODkzMA==&amp;action=getalbum&amp;album_id=1715194110212440067#wechat_redirect" textvalue="你已选中了添加链接的内容" tab="innerlink" data-linktype="1"><span data-positionback="static"><img data-ratio="0.20689655172413793" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RNDxgtG3pdSyaKcfgvqjDrC2mpKa0MCu1rsbGkQLcOys8c9BVLs2VnjEg/640?wx_fmt=png" data-type="png" data-w="638" data-imgfileid="503802209" src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RNDxgtG3pdSyaKcfgvqjDrC2mpKa0MCu1rsbGkQLcOys8c9BVLs2VnjEg/640?wx_fmt=png"></span></a></td></tr><tr><td width="243" valign="bottom" align="center" height="45"><a target="_blank" href="https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzA4NDAzODkzMA==&amp;action=getalbum&amp;album_id=1712569781846933508#wechat_redirect" textvalue="你已选中了添加链接的内容" tab="innerlink" data-linktype="1"><span data-positionback="static"><img data-imgfileid="503802207" data-ratio="0.20722135007849293" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RNDXqLDtKHqQMBReWKnTibVusnVlY43shlib0iaoluz4tmJPej8ej4vWiaehA/640?wx_fmt=png" data-type="png" data-w="637" src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RNDXqLDtKHqQMBReWKnTibVusnVlY43shlib0iaoluz4tmJPej8ej4vWiaehA/640?wx_fmt=png"></span></a></td><td width="243" valign="bottom" align="center" height="45"><a target="_blank" href="https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzA4NDAzODkzMA==&amp;action=getalbum&amp;album_id=1338481272770953216#wechat_redirect" textvalue="你已选中了添加链接的内容" tab="innerlink" data-linktype="1"><span data-positionback="static"><img data-imgfileid="503802210" data-ratio="0.2084639498432602" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RND3CbMQTDNRO3A5SELiaQ3DDeqQkt5rfZqpwQRsQYyTicQUD9zQlfolIvQ/640?wx_fmt=png" data-type="png" data-w="638" src="https://mmbiz.qpic.cn/mmbiz_png/dREape4YBzxVERm1kp30MnGymicMs1RND3CbMQTDNRO3A5SELiaQ3DDeqQkt5rfZqpwQRsQYyTicQUD9zQlfolIvQ/640?wx_fmt=png"></span></a></td></tr></tbody></table><span></span><img data-imgfileid="503802212" data-ratio="0.4462962962962963" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/dREape4YBzyF5jVxNCORGgSJRgWqy8hD72dmSRN2iaqQ8CibvLricqsLfL7Mauoa1YLLVYDrhp0RNEGsvicky3kibeA/640?wx_fmt=jpeg" data-type="jpeg" data-w="1080" src="https://mmbiz.qpic.cn/mmbiz_jpg/dREape4YBzyF5jVxNCORGgSJRgWqy8hD72dmSRN2iaqQ8CibvLricqsLfL7Mauoa1YLLVYDrhp0RNEGsvicky3kibeA/640?wx_fmt=jpeg"></section></section><section data-mid="" mpa-from-tpl="t"><br></section><section data-mid="" mpa-from-tpl="t"><span></span><br></section></section></section></section><p><br></p><p><mp-style-type data-value="3"></mp-style-type></p></div>

**Comment by Chestnut-L** [comment]
c2 = GetAssayData(object = sce.merg,assay = "RNA",slot = "counts")中，slot应该改为layer，GetAssayData函数在Seurat V5里没有slot参数了
