### ISSUE TITLE
101 种机器学习算法组合筛选最优预后风险模型（Mime 包）

### ISSUE THREAD

**Issue by ixxmu** [ixxmu/mp_duty#5179]
https://mp.weixin.qq.com/s/B_Yvb1jqAI1H2Up411X2Sw

**Comment by ixxmu** [comment]
101 种机器学习算法组合筛选最优预后风险模型（Mime 包） by 生信碱移
------
<div><section data-tool="markdown编辑器" data-website="https://markdown.com.cn/editor"><section data-mpa-powered-by="yiban.io" data-style='white-space: normal; max-width: 100%; letter-spacing: 0.544px; text-size-adjust: auto; background-color: rgb(255, 255, 255); font-family: "Helvetica Neue", Helvetica, "Hiragino Sans GB", "Microsoft YaHei", Arial, sans-serif; box-sizing: border-box !important; overflow-wrap: break-word !important;'><section><section><section><section data-id="85660" data-custom="rgb(117, 117, 118)" data-color="rgb(117, 117, 118)"><section data-style="margin-top: 2em; padding-top: 0.5em; padding-bottom: 0.5em; max-width: 100%; border-style: solid none; text-decoration: inherit; border-top-color: rgb(204, 204, 204); border-bottom-color: rgb(204, 204, 204); border-top-width: 1px; border-bottom-width: 1px; box-sizing: border-box !important; overflow-wrap: break-word !important;"><p><span>生信碱移</span></p><section><strong>Mime 多种机器学习组合</strong></section></section></section></section></section></section></section><section>机器学习算法组合之前咱公众号出了一个，但是仅仅是二分类的，贴子们感兴趣可以点击下面的文字看看：<strong>《</strong><a target="_blank" href="http://mp.weixin.qq.com/s?__biz=MzkyNTIzMzYyMA==&amp;mid=2247490932&amp;idx=1&amp;sn=77b00f1068fda99aef3c8da107701e76&amp;chksm=c1c8e5cff6bf6cd933f796f88e9ad01ad8ab21f3a347417aa3fa7f5dc95fc87334eb9d856b15&amp;scene=21#wechat_redirect" textvalue="重磅课程代码：15种机器学习算法、共207个参数优化组合机器学习模型，适用各种二分类问题，非肿瘤、肿瘤相关预测诊断模型" linktype="text" imgurl="" imgdata="null" data-itemshowtype="0" tab="innerlink" data-linktype="2"><strong>重磅课程代码：15种机器学习算法、共207个参数优化组合机器学习模型，适用各种二分类问题，非肿瘤、肿瘤相关预测诊断模型</strong></a><strong>》</strong>。</section><section>继续说正事，今天冲浪的时候看到一个R包 <span><strong>Mime</strong></span>，今天刚刚发表在 <span><strong>Computational and Structural Biotechnology Journal</strong></span> <strong>[</strong><span><strong>IF: 4.4</strong></span><strong>]</strong> 杂志。<strong>专门针对的就是多种机器学习组合的建模+可视化代码。</strong>别的不说，这个R包做的很齐全易用，趁热给各位老铁们分享一下。</section><section><img data-galleryid="" data-imgfileid="100009766" data-ratio="0.9666666666666667" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_jpg/LvUIqvYKCeU9ZjhI7E4HibHPmCYT7sjNtoBCicB6xT4WZOyEl8OqFA8fjutI3JxORg8GSeiclxmITicMwjledpYkMw/640?wx_fmt=jpeg&amp;from=appmsg" data-type="jpeg" data-w="1080" src="https://mmbiz.qpic.cn/sz_mmbiz_jpg/LvUIqvYKCeU9ZjhI7E4HibHPmCYT7sjNtoBCicB6xT4WZOyEl8OqFA8fjutI3JxORg8GSeiclxmITicMwjledpYkMw/640?wx_fmt=jpeg&amp;from=appmsg"></section><p data-class="mbImgTitle">▲ <strong>DOI: 10.1016/j.csbj.2024.06.035</strong></p><p data-tool="markdown.com.cn编辑器">github 链接如下：</p><ul data-tool="markdown.com.cn编辑器"><li><section>https://github.com/l-magnificence/Mime</section></li></ul><h3 data-tool="markdown.com.cn编辑器"><span>一、安装 R 包</span></h3><section>可以通过以下命令安装代码与相关依赖包：</section><pre data-tool="markdown.com.cn编辑器"><span></span><code>if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")<br><br>depens&lt;-c('GSEABase', 'GSVA', 'cancerclass', 'mixOmics', 'sparrow', 'sva' , 'ComplexHeatmap' )<br>for(i in 1:length(depens)){<br>  depen&lt;-depens[i]<br>  if (!requireNamespace(depen, quietly = TRUE))  BiocManager::install(depen,update = FALSE)<br>}<br><br>if (!requireNamespace("CoxBoost", quietly = TRUE))<br>  devtools::install_github("binderh/CoxBoost")<br><br>if (!requireNamespace("fastAdaboost", quietly = TRUE))<br>  devtools::install_github("souravc83/fastAdaboost")<br><br>if (!requireNamespace("Mime", quietly = TRUE))<br>  devtools::install_github("mumdark/MimeDL")<br></code></pre><section><strong>注意：</strong>我的电脑在这里遇到了一个问题。<code><span>Mime</span></code>包似乎与<code><span>devtools</span></code>的依赖包<code><span>mime</span></code>名称一致，导致安装失败，可能需要改一下R包名称（大家遇到了再说吧）。</section><h3 data-tool="markdown.com.cn编辑器"><span>二、简单的示例</span></h3><p data-tool="markdown.com.cn编辑器"><strong>① </strong><span><strong>加载示例数据</strong></span>（这个治疗反应数据在本文用不上，在官网是用作二分类的的示例，感兴趣的铁子可以自行看看）。：</p><pre data-tool="markdown.com.cn编辑器"><span></span><code><span># 01 加载示例数据</span><br>load(<span>"./External data/Example.cohort.Rdata"</span>) <span># 生存数据与基因表达信息</span><br>list_train_vali_Data[[<span>"Dataset1"</span>]][<span>1</span>:<span>5</span>,<span>1</span>:<span>5</span>]<br><span>#                 ID    OS.time OS   MT-CO1   MT-CO3</span><br><span>#60  TCGA.DH.A66B.01 1281.65322  0 13.77340 13.67931</span><br><span>#234 TCGA.HT.7607.01   96.19915  1 14.96535 14.31857</span><br><span>#42  TCGA.DB.A64Q.01  182.37755  0 13.90659 13.65321</span><br><span>#126 TCGA.DU.8167.01  471.97707  0 14.90695 14.59776</span><br><span>#237 TCGA.HT.7610.01 1709.53901  0 15.22784 14.62756</span><br><br>load(<span>"./External data/Example.ici.Rdata"</span>) <span># 治疗反应数据</span><br>list_train_vali_Data[[<span>"training"</span>]][<span>1</span>:<span>5</span>,<span>1</span>:<span>5</span>]<br><span>#                                                                         ID Var      FTH1   EEF1A1      ACTB</span><br><span>#Mariathasan_UC_pre_aPDL1_combo_tpm.1                        SAMf2ce197162ce   N 10.114846 4.817746 11.230180</span><br><span>#Gide_SKCM_pre_combo.66                                           ERR2208915   Y  2.044180 5.038854  3.977902</span><br><span>#Bruan_RCC_pre_aPD1_combo_tpm.3         G138701_RCCBMS-00141-T_v1_RNA_OnPrem   Y  5.406008 5.341635  5.366668</span><br><span>#Mariathasan_UC_pre_aPDL1_combo_tpm.203                      SAMe41b1e773582   N  9.215794 4.707360 11.412721</span><br><span>#Mariathasan_UC_pre_aPDL1_combo_tpm.58                       SAM5ffd7e4cd794   N  9.003710 3.908884 10.440559</span><br><br>load(<span>"./External data/genelist.Rdata"</span>)    <span># 基因列表</span><br>genelist<br><span># [1] "MYC"    "CTNNB1" "JAG2"   "NOTCH1" "DLL1"   "AXIN2"  "PSEN2"  "FZD1"   "NOTCH4" "LEF1"   "AXIN1"  "NKD1"   "WNT5B"  "CUL1"  </span><br><span>#[15] "JAG1"   "MAML1"  "KAT2A"  "GNAI1"  "WNT6"   "PTCH1"  "NCOR2"  "DKK4"   "HDAC2"  "DKK1"   "TCF7"   "WNT1"   "NUMB"   "ADAM17"</span><br><span>#[29] "DVL2"   "PPARD"  "NCSTN"  "HDAC5"  "CCND2"  "FRAT1"  "CSNK1E" "RBPJ"   "FZD8"   "TP53"   "SKP2"   "HEY2"   "HEY1"   "HDAC11"</span><br></code></pre><section>我们要使用的示例数据是<code><span>list_train_vali_Data</span></code>与<code><span>genelist</span></code>，介绍如下：</section><ul data-tool="markdown.com.cn编辑器"><li><section><strong>list_train_vali_Data</strong>：行是样本，第一列是样本ID，第二列是生存时间（单位year），第三列是生存状态，随后的列都是相应基因的表达量；</section></li><li><section><strong>genelist</strong>：是用于建模的基因列表。</section></li></ul><p data-tool="markdown.com.cn编辑器"><strong>② </strong><span><strong>构建预后模型</strong></span><strong>：</strong></p><pre data-tool="markdown.com.cn编辑器"><span></span><code>load(<span>"./External data/Example.cohort.Rdata"</span>)<br>load(<span>"./External data/genelist.Rdata"</span>)<br>res &lt;- ML.Dev.Prog.Sig(train_data = list_train_vali_Data$Dataset1,<br>                       list_train_vali_Data = list_train_vali_Data,<br>                       unicox.filter.for.candi = <span>T</span>,<br>                       unicox_p_cutoff = <span>0.05</span>,<br>                       candidate_genes = genelist,<br>                       mode = <span>'all'</span>,<br>                       nodesize =<span>5</span>,<br>                       seed = <span>123</span>)<br></code></pre><p><strong>③ </strong><span><strong>cindex 评估预后模型</strong></span>：</p><pre data-tool="markdown.com.cn编辑器"><span></span><code>cindex_dis_all(res,<br>               validate_set = <span>"Dataset2"</span>, <span># 指定测试集的名称</span><br>               order =names(list_train_vali_Data),<br>               width = <span>0.35</span>)<br>cindex_dis_select(res,<br>                  model=<span>"StepCox[forward] + plsRcox"</span>, <span># 指定选择模型</span><br>                  order= names(list_train_vali_Data))<br></code></pre><section><img data-backh="359" data-backw="268" data-galleryid="" data-imgfileid="100009767" data-ratio="1.3413654618473896" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/LvUIqvYKCeU9ZjhI7E4HibHPmCYT7sjNtVPMfbQTxM8v4gLUCT55Jt2Pky7zniawiawTkKH1ILRojRDLTf0iccQQAQ/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="996" src="https://mmbiz.qpic.cn/sz_mmbiz_png/LvUIqvYKCeU9ZjhI7E4HibHPmCYT7sjNtVPMfbQTxM8v4gLUCT55Jt2Pky7zniawiawTkKH1ILRojRDLTf0iccQQAQ/640?wx_fmt=png&amp;from=appmsg"></section><p data-tool="markdown.com.cn编辑器"><strong>④ </strong><span><strong>ROC下面积AUC 评估预后模型</strong></span>（下面展示的是1年的 AUC，通过<code><span>AUC_time</span></code>参数指定）：</p><pre data-tool="markdown.com.cn编辑器"><span></span><code>all.auc.1y &lt;- cal_AUC_ml_res(res.by.ML.Dev.Prog.Sig = res,<br>                             train_data = list_train_vali_Data[[<span>"Dataset1"</span>]],<br>                             inputmatrix.list = list_train_vali_Data,<br>                             mode = <span>'all'</span>,<br>                             AUC_time = <span>1</span>,   <span># 一年生存</span><br>                             auc_cal_method=<span>"KM"</span>)<br>auc_dis_all(all.auc.1y,<br>            dataset = names(list_train_vali_Data),<br>            validate_set=<span>"Dataset1"</span>,<br>            order= names(list_train_vali_Data),<br>            width = <span>0.35</span>,<br>            year=<span>1</span>)<br></code></pre><p><img data-galleryid="" data-imgfileid="100009769" data-ratio="1.3070283600493218" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/LvUIqvYKCeU9ZjhI7E4HibHPmCYT7sjNtANibjPPCnLXC25OIMbWbtm2bnVIMvd0RGXaMWtMic00GOgibbbRpNsubA/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="811" src="https://mmbiz.qpic.cn/sz_mmbiz_png/LvUIqvYKCeU9ZjhI7E4HibHPmCYT7sjNtANibjPPCnLXC25OIMbWbtm2bnVIMvd0RGXaMWtMic00GOgibbbRpNsubA/640?wx_fmt=png&amp;from=appmsg"></p><section><strong>⑤ </strong><span><strong>指定模型的性能评估</strong></span>，通过<code><span>model_name</span></code>参数指定模型。下面给大家介绍几个评估方式。<strong>首先，可以看看指定模型的ROC下面积AUC</strong>（下面展示的是1年的 AUC，通过<code><span>AUC_time</span></code>参数指定）：</section><pre data-tool="markdown.com.cn编辑器"><span></span><code>all.auc.1y &lt;- cal_AUC_ml_res(res.by.ML.Dev.Prog.Sig = res,<br>                             train_data = list_train_vali_Data[[<span>"Dataset1"</span>]],<br>                             inputmatrix.list = list_train_vali_Data,<br>                             mode = <span>'all'</span>,<br>                             AUC_time = <span>1</span>,   <span># 一年生存</span><br>                             auc_cal_method=<span>"KM"</span>)<br>auc_dis_all(all.auc.1y,<br>            dataset = names(list_train_vali_Data),<br>            validate_set=<span>"Dataset1"</span>,<br>            order= names(list_train_vali_Data),<br>            width = <span>0.35</span>,<br>            year=<span>1</span>)<br>roc_vis(all.auc.1y,<br>        model_name = <span>"StepCox[forward] + plsRcox"</span>,<br>        dataset = names(list_train_vali_Data),<br>        order= names(list_train_vali_Data),<br>        anno_position=c(<span>0.65</span>,<span>0.55</span>),<br>        year=<span>1</span>)<br></code></pre><section><img data-galleryid="" data-imgfileid="100009770" data-ratio="0.9308943089430894" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/LvUIqvYKCeU9ZjhI7E4HibHPmCYT7sjNtsbEmAxJ5YTQHX4ia35SBmZIEGENDF6fboHzR8WCSIe2WpBTiboun6nug/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="984" src="https://mmbiz.qpic.cn/sz_mmbiz_png/LvUIqvYKCeU9ZjhI7E4HibHPmCYT7sjNtsbEmAxJ5YTQHX4ia35SBmZIEGENDF6fboHzR8WCSIe2WpBTiboun6nug/640?wx_fmt=png&amp;from=appmsg"></section><section>当然，也可以同时绘制多个年份的：</section><pre data-tool="markdown.com.cn编辑器"><span></span><code>all.auc.3y &lt;- cal_AUC_ml_res(res.by.ML.Dev.Prog.Sig = res,train_data = list_train_vali_Data[[<span>"Dataset1"</span>]],<br>                             inputmatrix.list = list_train_vali_Data,mode = <span>'all'</span>,AUC_time = <span>3</span>,<br>                             auc_cal_method=<span>"KM"</span>)<br>all.auc.5y &lt;- cal_AUC_ml_res(res.by.ML.Dev.Prog.Sig = res,train_data = list_train_vali_Data[[<span>"Dataset1"</span>]],<br>                             inputmatrix.list = list_train_vali_Data,mode = <span>'all'</span>,AUC_time = <span>5</span>,<br>                             auc_cal_method=<span>"KM"</span>)<br>auc_dis_select(list(all.auc.1y,all.auc.3y,all.auc.5y),<br>               model_name=<span>"StepCox[forward] + plsRcox"</span>,<br>               dataset = names(list_train_vali_Data),<br>               order= names(list_train_vali_Data),<br>               year=c(<span>1</span>,<span>3</span>,<span>5</span>))<br></code></pre><section><img data-galleryid="" data-imgfileid="100009771" data-ratio="0.3675925925925926" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/LvUIqvYKCeU9ZjhI7E4HibHPmCYT7sjNt232WBumJIwojyiaeS66HNfTyicKxganLoobsEKsRd7CQGR5UKl1Pab6A/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="1080" src="https://mmbiz.qpic.cn/sz_mmbiz_png/LvUIqvYKCeU9ZjhI7E4HibHPmCYT7sjNt232WBumJIwojyiaeS66HNfTyicKxganLoobsEKsRd7CQGR5UKl1Pab6A/640?wx_fmt=png&amp;from=appmsg"></section><section><strong>其次，可以看看指定模型的生存曲线</strong>：</section><pre data-tool="markdown.com.cn编辑器"><span></span><code>rs_sur(res, <br>       model_name = <span>"StepCox[forward] + plsRcox"</span>,  <span># 选择你的模型</span><br>       dataset = <span>"Dataset1"</span>,<br>       <span>#color=c("blue","green"),</span><br>       median.line = <span>"hv"</span>,<br>       cutoff = <span>0.5</span>,<br>       conf.int = <span>T</span>,<br>       xlab=<span>"Day"</span>,pval.coord=c(<span>1000</span>,<span>0.9</span>))<br></code></pre><p><img data-galleryid="" data-imgfileid="100009772" data-ratio="0.985524728588661" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/LvUIqvYKCeU9ZjhI7E4HibHPmCYT7sjNtwHVJcrXlD5YfHaoNrjPlDrWJjjUZMWIJ3eicnJy8iaVcia9y5VwpJaSsg/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="829" src="https://mmbiz.qpic.cn/sz_mmbiz_png/LvUIqvYKCeU9ZjhI7E4HibHPmCYT7sjNtwHVJcrXlD5YfHaoNrjPlDrWJjjUZMWIJ3eicnJy8iaVcia9y5VwpJaSsg/640?wx_fmt=png&amp;from=appmsg"></p><section><strong>最后，可以看看指定模型的森林图</strong>：</section><pre data-tool="markdown.com.cn编辑器"><span></span><code>unicox.rs.res &lt;- cal_unicox_ml_res(res.by.ML.Dev.Prog.Sig = res,<br>                                   optimal.model = <span>"StepCox[forward] + plsRcox"</span>,<br>                                   type =<span>'categorical'</span>)<br>metamodel &lt;- cal_unicox_meta_ml_res(input = unicox.rs.res)<br>meta_unicox_vis(metamodel,<br>                dataset = names(list_train_vali_Data))<br></code></pre><p><img data-galleryid="" data-imgfileid="100009773" data-ratio="0.30185185185185187" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/LvUIqvYKCeU9ZjhI7E4HibHPmCYT7sjNtP9eib3I2n7wCAuKQjv3q4cTZNRTOSD4JziaSn76N6iaxWdXrG7KGBV5Jg/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="1080" src="https://mmbiz.qpic.cn/sz_mmbiz_png/LvUIqvYKCeU9ZjhI7E4HibHPmCYT7sjNtP9eib3I2n7wCAuKQjv3q4cTZNRTOSD4JziaSn76N6iaxWdXrG7KGBV5Jg/640?wx_fmt=png&amp;from=appmsg"></p><p data-tool="markdown.com.cn编辑器"><strong>⑥ </strong><span><strong>与其他已发表文章的模型比较</strong></span>（作者仅仅提供了胶质瘤发表文章的模型）:</p><p data-tool="markdown.com.cn编辑器"><strong>首先是Cindex的比较</strong>：</p><pre data-tool="markdown.com.cn编辑器"><span></span><code>cc.glioma.lgg.gbm &lt;- cal_cindex_pre.prog.sig(use_your_own_collected_sig = <span>F</span>,<br>                                             type.sig = c(<span>'Glioma'</span>,<span>'LGG'</span>,<span>'GBM'</span>),<br>                                             list_input_data = list_train_vali_Data)<br>cindex_comp(cc.glioma.lgg.gbm,<br>            res,<br>            model_name=<span>"StepCox[forward] + plsRcox"</span>,<br>            dataset=names(list_train_vali_Data))<br></code></pre><p><img data-galleryid="" data-imgfileid="100009774" data-ratio="1.3038095238095238" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/LvUIqvYKCeU9ZjhI7E4HibHPmCYT7sjNtibIXUfVMIS0iccY48OFCmqzKEqyHEeKl9s6TnQIO5ZCwiaRQXF5UdBLvA/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="1050" src="https://mmbiz.qpic.cn/sz_mmbiz_png/LvUIqvYKCeU9ZjhI7E4HibHPmCYT7sjNtibIXUfVMIS0iccY48OFCmqzKEqyHEeKl9s6TnQIO5ZCwiaRQXF5UdBLvA/640?wx_fmt=png&amp;from=appmsg"></p><p data-tool="markdown.com.cn编辑器"><strong>然后是 AUC的比较</strong>：</p><pre data-tool="markdown.com.cn编辑器"><span></span><code>auc.glioma.lgg.gbm.1 &lt;- cal_auc_pre.prog.sig(use_your_own_collected_sig = <span>F</span>,<br>                                             type.sig = c(<span>'Glioma'</span>,<span>'LGG'</span>,<span>'GBM'</span>),<br>                                             list_input_data = list_train_vali_Data,<br>                                             AUC_time = <span>1</span>,<br>                                             auc_cal_method = <span>'KM'</span>)<br>auc_comp(auc.glioma.lgg.gbm.1,<br>         all.auc.1y,<br>         model_name=<span>"StepCox[forward] + plsRcox"</span>,<br>         dataset=names(list_train_vali_Data))<br></code></pre><p><img data-galleryid="" data-imgfileid="100009775" data-ratio="1.2858546168958742" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/LvUIqvYKCeU9ZjhI7E4HibHPmCYT7sjNtOt8xVdZalRAw87JZNia3enfuFSemtXNgdGJmqZgdjtO9kT7fuSdSicHQ/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="1018" src="https://mmbiz.qpic.cn/sz_mmbiz_png/LvUIqvYKCeU9ZjhI7E4HibHPmCYT7sjNtOt8xVdZalRAw87JZNia3enfuFSemtXNgdGJmqZgdjtO9kT7fuSdSicHQ/640?wx_fmt=png&amp;from=appmsg"></p><p data-tool="markdown.com.cn编辑器">这个r包功能还有其他功能，包括其他潜在的参数大家都可以自行看看文档。</p><section><strong><strong><span><span><strong><span>今天碰巧撞上这个包</span></strong></span></span></strong></strong></section><section><strong><strong><span><span><strong><span>就分享到这<br></span></strong></span></span></strong></strong></section><p><strong><span>欢迎点击关注<img data-src="https://res.wx.qq.com/t/wx_fed/we-emoji/res/v1.3.10/assets/newemoji/Yellowdog.png" data-ratio="1" data-w="128" src="https://res.wx.qq.com/t/wx_fed/we-emoji/res/v1.3.10/assets/newemoji/Yellowdog.png"><img data-src="https://res.wx.qq.com/t/wx_fed/we-emoji/res/v1.3.10/assets/newemoji/smiley_83b.png" data-ratio="1" data-w="128" src="https://res.wx.qq.com/t/wx_fed/we-emoji/res/v1.3.10/assets/newemoji/smiley_83b.png"><img data-src="https://res.wx.qq.com/t/wx_fed/we-emoji/res/v1.3.10/assets/Expression/Expression_64@2x.png" data-ratio="1" data-w="128" src="https://res.wx.qq.com/t/wx_fed/we-emoji/res/v1.3.10/assets/Expression/Expression_64@2x.png"></span></strong></p><section><mp-common-profile data-id="MzkyNTIzMzYyMA==" data-pluginname="mpprofile" data-headimg="http://mmbiz.qpic.cn/mmbiz_png/LvUIqvYKCeXYZNMxRMnjiaicO2a27jDZ2FgQga8TdeQcsGRJRIn2IInkKtfcbbMXOBSViaPXpTOBulUlNzd11pzow/0?wx_fmt=png" data-nickname="生信碱移" data-alias="liudoufu307" data-signature="春来秋至，分享我的所见与所识" data-from="2" data-weuitheme="light"></mp-common-profile></section><section><br></section><section><strong><span>END~</span></strong><br></section><p><span><strong>仅供粉丝老铁们参考</strong></span></p><p><strong>如有侵权或错误，请联系删除改正～</strong><span></span></p></section><p><mp-style-type data-value="3"></mp-style-type></p></div>

**Comment by ixxmu** [comment]
这tm都直接写个R包，当个人吧！

**Comment by ZimLea** [comment]
为什么Mime包无法正常安装

**Comment by jdjsm021** [comment]
求教安装不了，怎么解决

**Comment by ZimLea** [comment]
请问你是？

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月23日 23:24 |
| 收件人 | ixxmu/mp_duty ***@***.***> |
| 抄送人 | LeeZhen ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [ixxmu/mp_duty] 101 种机器学习算法组合筛选最优预后风险模型（Mime 包） (Issue #5179) |

求教安装不了，怎么解决
