### ISSUE TITLE
使用大语言模型的生物嵌入，后续应该会有很多类似文章出来！

### ISSUE THREAD

**Issue by ixxmu** [ixxmu/mp_duty#6238]
https://mp.weixin.qq.com/s/5a2ZI3QEJ5uNZWpDMPtNuw

**Comment by yingnanyou** [comment]
Hi, I encountered an error while using the miRTalk package and would appreciate your help.
1.I ran the following code:
obj <- find_miRNA(object = obj, mir_info = mir_info, mir2tar = mir2tar)
2.Expected result: The function should identify miRNAs in the single-cell data.
3.Actual result: The following error occurred:
Error in find_miRNA(object = obj, mir_info = mir_info, mir2tar = mir2tar) :
No miRNAs found in sc_data!
R Version: [R 4.3.0]
